### PR TITLE
Add the API Surface tasks file to the documentation.

### PR DESCRIPTION
**Pull request by millenomi**
This file tracks what symbols are missing on purpose (and generally why), vs. what symbols are missing that we would like to have.

### CODE REVIEW

**Comment by millenomi** [comment]
@swift-ci please test and merge

**Comment by shahmishal** [comment]
@swift-ci please test and merge

**Comment by spevans** [comment]
@swift-ci please test and merge

**Comment by millenomi** [comment]
@swift-ci please test and merge

**Pull request merged**
