### PR TITLE
[5.3] SR-12833: processInfo.activeProcessorCount ignores CFS quotas

### PR DESCRIPTION
**Pull request by spevans**
- For Linux, take into account CFS quotes eg, if running under Docker.

(cherry picked from commit 57bc80c1b32aad1cdef9192f3d867e97346bb707)

### CODE REVIEW

**Comment by spevans** [comment]
@swift-ci test

**Comment by spevans** [comment]
@swift-ci test

**Comment by spevans** [comment]
@swift-ci test

**Comment by tomerd** [comment]
@spevans should we merge this while within the 5.3.3 window?

**Comment by spevans** [comment]
@swift-ci test

**Pull request merged**
