### PR TITLE
Fix for memory leak in NSUUID

### PR DESCRIPTION
**Pull request by nethraravindran**

### CODE REVIEW

**Comment by parkera** [comment]
@swift-ci please test and merge

**Comment by ianpartridge** [comment]
Does `init?(uuidString: String)` also leak? Looks like that one allocates 16 bytes too.

**Comment by nethraravindran** [comment]
Hi @ianpartridge Have provided the fix for the leaks in ` init?(uuidString: String)`  and ` init?(coder: NSCoder)` as well. Thanks!

**Comment by parkera** [comment]
@swift-ci please test and merge

**Pull request merged**
