### PR TITLE
Added getStreamsToHost and getStreamsTo

### PR DESCRIPTION
**Pull request by amraboelela**

### CODE REVIEW

**Comment by parkera** [comment]
These new classes and functions don't appear to be part of the Foundation API. Am I missing something?

**Comment by amraboelela** [comment]
getStreamsToHost is part of the API

extension Stream {

    
    @available(iOS 8.0, *)
    open class func getStreamsToHost(withName hostname: String, port: Int, inputStream: AutoreleasingUnsafeMutablePointer<InputStream?>?, outputStream: AutoreleasingUnsafeMutablePointer<OutputStream?>?)
}


Stream.getStreamsTo(socket: CFSocketNativeHandle(socket), inputStream: &inputStream, outputStream: &outputStream)

Is done by CFStreamCreatePairWithSocket in CoreFoundation but we can keep this temporary till the CFStreamCreatePairWithSocket is ready which might take time. Or put it in Foundation and make it private.

**Comment by parkera** [comment]
`getStreamsTo` should be private (actually it would be named something else anyway, like `getStreams(to:)`). The other classes should also be explicitly marked private.

Can you add some tests to this PR?

**Comment by amraboelela** [comment]
Ok, changed them to private. And here is a simple test case

    func testGetStreamsToHost() {
        var inputStream: InputStream? = nil
        var outputStream: OutputStream? = nil
        
        Stream.getStreamsToHost(withName: "127.0.0.1", port: 1000, inputStream: &inputStream, outputStream: &outputStream)
        inputStream?.schedule(in: RunLoop.current, forMode: .defaultRunLoopMode)
        outputStream?.schedule(in: RunLoop.current, forMode: .defaultRunLoopMode)
        outputStream?.open()
        inputStream?.open()
    }

**Comment by parkera** [comment]
Can the test be put into the automated unit tests we have for other functionality?

We recently added a loopback server there for testing `URLSession`, so this seems like it should be testable using that infrastructure.

**Comment by amraboelela** [comment]
yes it should be ok, just put the right ip address and port number of the loopback server

**Comment by amraboelela** [comment]
To test it with a delegate, you can use the following:

func testGetStreamsToHost() {
    var inputStream: InputStream? = nil
    var outputStream: OutputStream? = nil
    Stream.getStreamsToHost(withName: "127.0.0.1", port: 1000, inputStream: &inputStream, outputStream: &outputStream)
    outputStream?.delegate = self
    inputStream?.delegate = self
    inputStream?.schedule(in: RunLoop.current, forMode: .defaultRunLoopMode)
    outputStream?.schedule(in: RunLoop.current, forMode: .defaultRunLoopMode)
    outputStream?.open()
    inputStream?.open()
}

    public func stream(_ aStream: Stream, handleEvent eventCode: Stream.Event) {
        if aStream == inputStream {
            switch eventCode {
            case Stream.Event.openCompleted:
                print("Input stream NSStreamEventOpenCompleted")
            case Stream.Event.hasBytesAvailable:
                    print("Input stream NSStreamEventHasBytesAvailable")
            case Stream.Event.endEncountered:
                print("Input stream NSStreamEventEndEncountered")
                self.close()
            default:
                print("eventCode: \(eventCode)")
            }
        }
        if aStream == outputStream {
            switch eventCode {
            case Stream.Event.openCompleted: 
                  print("outputStream stream NSStreamEventOpenCompleted")
            case Stream.Event.hasSpaceAvailable: 
               print("outputStream stream NSStreamEventHasBytesAvailable")
            case Stream.Event.endEncountered:
                print("Output stream NSStreamEventEndEncountered")
                outputStream.close()
            default:
                print("eventCode: \(eventCode)")
            }
        }
    }

**Comment by parkera** [comment]
Sorry, I realize that my comment earlier was not too clear.

Since you're the author of this PR, I'd like you to be the one to add those tests to the test suite as part of this change.

**Comment by amraboelela** [comment]
When I tested TestURLSession in Linux, I got the following errors:

Test Suite 'TestURLSession' started at 01:24:06.030
Test Case 'TestURLSession.test_dataTaskWithURL' started at 01:24:06.030
*** Error in `/home/amr/swift/swift-corelibs-foundation/.build/debug/swift-corelibs-foundationPackageTests.xctest': double free or corruption (fasttop): 0x00007f7374000b70 ***

**Comment by amraboelela** [comment]
I got the same double free or corruption (fasttop) error for every test function in TestURLSession.swift file

**Comment by amraboelela** [comment]
Can't believe this PR still open :)
I think we already merged those changes throw another PR, so probably we can close this one.

**Comment by ianpartridge** [comment]
OK, thanks @amraboelela :)

**Comment by luisdelarosa** [comment]
@amraboelela I looked at the latest code for getStreamsToHost() with NSUnimpemented(). Could we re-open this or is there another PR that I overlooked? All of the PRs that I found that had made changes were all closed, none were merged: https://github.com/pulls?q=is%3Apr+getStreamsToHost+is%3Aclosed

**Comment by amraboelela** [comment]
Yes we can re-open it, but I don't have ability to re-open it. Also you can create another PR with the changes you need, if you want.

**Comment by alblue** [comment]
The pull request can't be re-opened because the repository that submitted this pull request has been deleted, according to GitHub.

Can you rebase the changes and create a new request?

**Comment by amraboelela** [comment]
Can someone else do it?

I am busy with android build stuff.

**Pull request closed without merging**
