### PR TITLE
Cater for new Swift reference count representation

### PR DESCRIPTION
**Pull request by johnno1962**
Shouldn’t this fix for 32 bit systems be on the 4.2 branch? ARM Ports are coming up against this problem. https://github.com/uraimo/buildSwiftOnARM/issues/15

### CODE REVIEW

**Comment by parkera** [comment]
For cherry picks to 4.2 it helps to have a reference to the master commit so we don't have to go searching for it.

**Comment by johnno1962** [comment]
There you go: https://github.com/apple/swift-corelibs-foundation/pull/1525

**Comment by parkera** [comment]
Cool, thanks!

**Comment by parkera** [comment]
@swift-ci test and merge

**Comment by johnno1962** [comment]
What happened there?

**Comment by parkera** [comment]
Not sure. Let's try that again

**Comment by parkera** [comment]
@swift-ci test and merge

**Comment by johnno1962** [comment]
Thanks @parkera, good to see this merged. I can PR the other Android changes into 3.2 if you like i.e. https://github.com/apple/swift-corelibs-foundation/pull/1518 but this was the most important.

**Comment by parkera** [comment]
If you have any others, now is a good time to propose them.

**Comment by johnno1962** [comment]
OK, I’ve created https://github.com/apple/swift-corelibs-foundation/pull/1631

**Pull request merged**
