### PR TITLE
[cmake] Find ICU in CoreFoundation.

### PR DESCRIPTION
**Pull request by drodriguez**
ICU is also included in CoreFoundation, but the include paths were
not used, which meant that the headers were probably the system
headers, if they were there. This might have work in Ubuntu, but
might not work in other systems with older ICUs.

The patch passes the ICU_ROOT from the top level CMakeList.txt into
the CoreFoundation one and performs a find_package to find the right
include path.

/cc @compnerd

### CODE REVIEW

**Comment by spevans** [comment]
Should probably keep the addition of `"${CMAKE_CURRENT_SOURCE_DIR}/../cmake/modules"` to `CMAKE_MODULE_PATH` as well and get rid of the duplicate of `FindICU.cmake` that I made

**Comment by drodriguez** [comment]
I hope this was what you both were intending: I removed the duplicated script and I passed `ICU_ROOT` instead of `ICU_INCLUDE_DIR`.

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test and merge

**Comment by millenomi** [comment]
@swift-ci please test and merge

**Pull request merged**
