### PR TITLE
Remove unused variable in CFStringUtilities.c

### PR DESCRIPTION
**Pull request by valeriyvan**

### CODE REVIEW

**Comment by spevans** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@millenomi lmk if you'd like to review trivial PRs such as this, or I could merge them otherwise

**Comment by millenomi** [comment]
I have these patches on temporary pause — the Core Foundation sources in this repo are produced by processing other source. Historically, every fall we merge in code to master from new releases, and I'm in the middle of figuring out how to do that for this year, and each small change adds some burden to that.

As soon as the new merge-in PR is posted, these then become good to merge.

**Comment by valeriyvan** [comment]
How may I know that we could move further? I see a lot of other things like these ones which could and should be fixed.

**Comment by valeriyvan** [comment]
ping

**Comment by valeriyvan** [comment]
ping

**Comment by AtariDreams** [comment]
ping @spevans

**Comment by AtariDreams** [comment]
Any update on this @parkera

**Comment by valeriyvan** [comment]
ping

**Review by parkera — APPROVED** [review]

**Comment by parkera** [comment]
Thanks!

**Pull request merged**
