### PR TITLE
Implement Decimal.init?<T : BinaryInteger>(exactly source: T)

### PR DESCRIPTION
**Pull request by spevans**
- This still requires some tests with a BinaryInteger larger
  then UInt64.

### CODE REVIEW

**Comment by spevans** [comment]
@swift-ci test

**Comment by spevans** [comment]
@swift-ci test macos

**Comment by spevans** [comment]
@swift-ci test macos

**Comment by weissi** [comment]
@swift-ci test macos

**Comment by spevans** [comment]
@swift-ci test and merge

**Comment by spevans** [comment]
@swift-ci test and merge

**Pull request merged**
