### PR TITLE
add support for riscv64

### PR DESCRIPTION
**Pull request by futurejones**
Add support for `riscv64` as host architecture.

### CODE REVIEW

**Comment by parkera** [comment]
Thanks @futurejones -- we are working on a brand new set of CMake configs in the `package` branch [over here](https://github.com/apple/swift-corelibs-foundation/pull/4959) -- we should rebase this on top of that once it lands.

**Comment by jmschonfeld** [comment]
I believe @iCharlesHu's changes to the cmake for the `package` branch will actually remove this manual list of architectures and instead ask the compiler for the architecture (which should eliminate the need for this change and others like it in the future). We should double check to confirm, but hopefully this should "Just Work" with the new cmake setup

**Comment by iCharlesHu** [comment]
Ditto to what @jmschonfeld said. We are removing this list with https://github.com/apple/swift-corelibs-foundation/pull/4959 and just ask the compiler at runtime.

**Comment by futurejones** [comment]
@parkera @jmschonfeld @iCharlesHu 
https://github.com/apple/swift-corelibs-foundation/pull/4959 has now been merged but it appears no changes were made the use of the `SwiftSupport.cmake` file.
The file still exists and is is still referenced in the `CMakeLists.txt` file.
https://github.com/apple/swift-corelibs-foundation/blob/ca3669eb9ac282c649e71824d9357dbe140c8251/CMakeLists.txt#L67
https://github.com/apple/swift-corelibs-foundation/blob/main/cmake/modules/SwiftSupport.cmake

Am I missing something?
Thanks.

**Comment by jmschonfeld** [comment]
@futurejones that PR was merged into the `package` branch, which is where ongoing work is taking place to re-core this repo on the new swift-foundation repo. That branch is expected to be merged into `main` imminently as soon as we resolve the final blockers. You can view the new contents of that file on the `package` branch at https://github.com/apple/swift-corelibs-foundation/blob/package/cmake/modules/FoundationSwiftSupport.cmake and this is the file that will be merged to `main` shortly (and you can see in that file that the list of architectures is removed)

**Comment by jmschonfeld** [comment]
The `package` branch has now been merged to `main` so I believe this support should now be available for you on `main`

**Comment by futurejones** [comment]
@jmschonfeld Thank you,
Closing this PR as issue has been solved with PR #4959

**Pull request closed without merging**
