### PR TITLE
test_redirectionWithSetCookies fails nondeterministically

### PR DESCRIPTION
**Pull request by millenomi**
XFAIL it for now on master.

### CODE REVIEW

**Comment by millenomi** [comment]
@swift-ci please test and merge

**Comment by drodriguez** [comment]
Some days ago we found out that those cookie tests were dependent on the previous tests. I uploaded #2527 to make those test independent. It might be good to see if the non-determinism can be removed with that new version.

**Comment by shahmishal** [comment]
```
/home/buildnode/jenkins/workspace/swift-corelibs-foundation-PR-Linux@2/swift-corelibs-foundation/TestFoundation/TestURLSession.swift:754: error: TestURLSession.test_postWithEmptyBody : XCTAssertNil failed: "Error Domain=NSURLErrorDomain Code=-1011 "(null)"" - error = Error Domain=NSURLErrorDomain Code=-1011 "(null)"
19:16:06 Fatal error: file /home/buildnode/jenkins/workspace/swift-corelibs-foundation-PR-Linux@2/swift-corelibs-foundation/TestFoundation/TestURLSession.swift, line 755
19:16:06 Current stack trace:
19:16:06 0    libswiftCore.so                    0x00007f5ef1393d00 swift_reportError + 50
19:16:06 1    libswiftCore.so                    0x00007f5ef1404c70 _swift_stdlib_reportFatalErrorInFile + 115
19:16:06 2    libswiftCore.so                    0x00007f5ef110f2ee <unavailable> + 1381102
19:16:06 3    libswiftCore.so                    0x00007f5ef110eef7 <unavailable> + 1380087
19:16:06 4    libswiftCore.so                    0x00007f5ef110f522 <unavailable> + 1381666
19:16:06 5    libswiftCore.so                    0x00007f5ef110d620 _assertionFailure(_:_:file:line:flags:) + 520
19:16:06 6    TestFoundation                     0x000055936caf434a <unavailable> + 9388874
19:16:06 7    libFoundationNetworking.so         0x00007f5eef061ba4 <unavailable> + 1399716
19:16:06 8    libFoundation.so                   0x00007f5eef8c4fec <unavailable> + 7954412
19:16:06 9    libFoundation.so                   0x00007f5eef8dd8d1 <unavailable> + 8054993
19:16:06 10   libFoundation.so                   0x00007f5eef8c511c <unavailable> + 7954716
19:16:06 11   libFoundation.so                   0x00007f5eef8cfb40 BlockOperation.main() + 1196
19:16:06 12   libFoundation.so                   0x00007f5eef8d7a90 OperationQueue._execute(_:) + 523
19:16:06 13   libFoundation.so                   0x00007f5eef8ca310 Operation.start() + 2591
19:16:06 14   libFoundation.so                   0x00007f5eef8d6a60 OperationQueue._schedule(_:) + 237
19:16:06 15   libFoundation.so                   0x00007f5eef8daf09 <unavailable> + 8044297
19:16:06 16   libFoundation.so                   0x00007f5eef4ec0f0 <unavailable> + 3920112
19:16:06 17   libdispatch.so                     0x00007f5ef04646e5 <unavailable> + 214757
19:16:06 18   libdispatch.so                     0x00007f5ef045df6b <unavailable> + 188267
19:16:06 19   libdispatch.so                     0x00007f5ef045ec4a <unavailable> + 191562
19:16:06 20   libdispatch.so                     0x00007f5ef0466a73 <unavailable> + 223859
19:16:06 21   libpthread.so.0                    0x00007f5ef0da86ba <unavailable> + 30394
19:16:06 22   libc.so.6                          0x00007f5eeec493b0 clone + 109
```

**Comment by stephentyrone** [comment]
@swift-ci please test linux

**Comment by drodriguez** [comment]
From the little information from https://ci.swift.org/job/swift-PR-Linux-smoke-test/17459/console and tracking up the code, it doesn't seem that the fixes in the other PR might fix anything.

It seems that the server is not returning anything (or that's what I understand from the cURL error code). Something that makes the problem a little harder is that the test triggers two requests: the first one is suppose to be a redirection, the second one is the redirected request. It is a little bit impossible from the test failure to know which of the two is actually failing.

Sorry I cannot be of more help at the moment.

**Comment by stephentyrone** [comment]
@millenomi do we now want to merge this over the other change?

**Comment by stephentyrone** [comment]
@swift-ci please test linux

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by shahmishal** [comment]
This PR will disable the test suite  - https://github.com/apple/swift-corelibs-foundation/pull/2533

**Comment by drodriguez** [comment]
It seems that the problem moving to the next test might be a resource usage problem (no more file descriptors? but as far as I can see in the code, either HTTPServer or cURL should fail more obviously because of that).

I really hope nobody takes this the wrong way, but from what I can find in failures linked here, it might had happen just after the revert from Thursday (https://github.com/apple/swift-corelibs-foundation/pull/2528). I wonder if some piece of code was added after the reverted commit that relied on it. I have reviewed the log, and I don’t see how one of those could have created the problem, though, but somebody else might see something.

**Comment by stephentyrone** [comment]
@drodriguez That revert was to 5.1-branch, while the failures in question are happening on master; what am I missing?

**Comment by drodriguez** [comment]
There was a similar revert in the master branch: https://github.com/apple/swift-corelibs-foundation/pull/2529

**Pull request closed without merging**
