### PR TITLE
NSSet/CFSet bridging

### PR DESCRIPTION
**Pull request by henrybetts**
Implements the bridge between NSSet and CFSet in the same way as the other NSCF classes.
I believe that NSSet member() now behaves as expected, returning the actual object stored in the set, rather than the compared value.

Also includes a fix that allows bridged dictionaries to be copied.

### CODE REVIEW

**Comment by parkera** [comment]
@phausler can you take a look at this?

**Comment by parkera** [comment]
@henrybetts In the meantime, it would be great to add some test cases here.

**Comment by phausler** [comment]
as a cursory glance this looks about right

@swift-ci Please test

**Comment by parkera** [comment]
Thanks!

**Pull request merged**
