### PR TITLE
[5.2] fix convenience accessors on CocoaError and URLError

### PR DESCRIPTION
**Pull request by glessard**
- fixes SR-13037 (https://bugs.swift.org/browse/SR-13037)

(previously merged to master in https://github.com/apple/swift-corelibs-foundation/pull/2828)

### CODE REVIEW

**Comment by spevans** [comment]
cc @drexin

**Comment by spevans** [comment]
@swift-ci test

**Comment by glessard** [comment]
note: merged to the 5.3 branch in #2845

**Comment by drexin** [comment]
@swift-ci test 5.2 macos

**Comment by drexin** [comment]
@swift-ci test 5.2 macos

**Pull request merged**
