### PR TITLE
[gardening] Prefer `Array(seq)` over `seq.map { $0 }`

### PR DESCRIPTION
**Pull request by ikesyo**

### CODE REVIEW

**Comment by ikesyo** [comment]
@swift-ci please test

**Comment by pushkarnk** [comment]
@ikesyo I'm just curious if there a reason (performance or only elegance?) why we should prefer `Array(seq)` over `seq.map { $0 }`. Thanks.

**Comment by ikesyo** [comment]
@pushkarnk I think that the former would/should be more efficient and the intent would be clearer (and also the latter looks a bit weird to me).

- [`Array.init`](https://github.com/apple/swift/blob/swift-DEVELOPMENT-SNAPSHOT-2017-02-01-a/stdlib/public/core/Arrays.swift.gyb#L1036-L1043)
- [`Sequence.map`](https://github.com/apple/swift/blob/swift-DEVELOPMENT-SNAPSHOT-2017-02-01-a/stdlib/public/core/Sequence.swift#L811-L829)
- [`Collection.map`](https://github.com/apple/swift/blob/swift-DEVELOPMENT-SNAPSHOT-2017-02-01-a/stdlib/public/core/Collection.swift#L1297-L1318)

See also an issue on SwiftLint project: https://github.com/realm/SwiftLint/issues/1271.

**Comment by parkera** [comment]
For the files that are also part of the overlay, let's also raise a PR there to make the same changes.

**Comment by ikesyo** [comment]
Submitted https://github.com/apple/swift/pull/7243.

**Comment by parkera** [comment]
LGTM

**Comment by ikesyo** [comment]
@swift-ci test and merge

**Pull request merged**
