### PR TITLE
Base.subproject: correct home directory handling on Windows

### PR DESCRIPTION
**Pull request by compnerd**
While we can enumerate the users using `NetUserEnum`, that does not guarantee that we get the full user information.  Perform an explicit `NetUserGetInfo` to query the user information to get the home directory.

Additionally, correct the `CFString` handling within the function where we were improperly using `CFStringCreateWithBytesNoCopy` which requires that the string is 8-bit encoded.  We now use
`CFStringCreateWithCharacters[NoCopy]` to properly create the `CFString` with unicode characters.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
CC: @parkera @lorentey

**Review by lorentey — APPROVED** [review]

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Pull request merged**
