### PR TITLE
Implement the rest of the FileHandle API

### PR DESCRIPTION
**Pull request by millenomi**
- Ensure tests always source the stdlib from the toolchain.

- Implement the missing `FileHandle` API: `readabilityHandler` and `writeabilityHandler`, and the `…InBackgroundAndNotify` and `…InBackgroundAndNotify(for:)` family of methods.

- Test it.

### CODE REVIEW

**Comment by millenomi** [comment]
cc @spevans

**Comment by millenomi** [comment]
@swift-ci please test

**Comment by millenomi** [comment]
@swift-ci please test

**Comment by millenomi** [comment]
@swift-ci please test

**Comment by millenomi** [comment]
@swift-ci please test

**Comment by spevans** [comment]
Is it valid to allow `waitForDataInBackgroundAndNotify()` or `acceptConnectionInBackgroundAndNotify()` to be active alongside a `readabilityHandler` ?
It looks like `readabilityHandler` is not setting `currentBackgroundActivityOwner` - is this correct?

**Comment by spevans** [comment]
Only other comment: Given the amount of `lock()` / `unlock()` pairs, would it be better to use `privateAsyncVariablesLock.synchronized { }` internal extension to make the locking a bit more readable?

**Comment by millenomi** [comment]
Respectively: yes, it is in Darwin; and yeah, good call.

**Comment by millenomi** [comment]
@swift-ci please test

**Comment by millenomi** [comment]
@swift-ci please test

**Comment by millenomi** [comment]
@swift-ci please test

**Comment by millenomi** [comment]
@swift-ci please test

**Comment by millenomi** [comment]
@swift-ci please test

**Comment by millenomi** [comment]
@swift-ci please test

**Comment by millenomi** [comment]
@swift-ci please test

**Comment by millenomi** [comment]
@swift-ci please test

**Comment by millenomi** [comment]
@swift-ci please test

**Comment by millenomi** [comment]
@swift-ci please test

**Comment by millenomi** [comment]
@swift-ci please test

**Comment by millenomi** [comment]
@swift-ci please test

**Comment by millenomi** [comment]
@swift-ci please test

**Comment by millenomi** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
This broke the Windows build :-(

**Pull request merged**
