### PR TITLE
fix Operation.isExecuting

### PR DESCRIPTION
**Pull request by weissi**

### CODE REVIEW

**Comment by weissi** [comment]
@swift-ci please test

**Comment by weissi** [comment]
@swift-ci please test

**Comment by phausler** [comment]
@swift-ci please test and merge

**Comment by weissi** [comment]
@phausler I can't see the results of the CI run here even though we both asked to test it. Any idea what's going on?

**Comment by weissi** [comment]
@swift-ci please test and merge

**Comment by weissi** [comment]
@swift-ci please test and merge

**Comment by phausler** [comment]
Sometimes swift-ci ignores certain channels for some reason. This change looks solid to me.

**Comment by weissi** [comment]
@phausler dang, forgot to record a little change in the tests so tests will fail :\. Pushing a new commit any second now

**Comment by weissi** [comment]
@swift-ci please test

**Comment by weissi** [comment]
@swift-ci please test

**Comment by weissi** [comment]
@phausler this now passed the checks. Didn't merge it as I made some (cosmtic) changes in the tests and wanted to give you the chance to have a look at that.

**Pull request merged**
