### PR TITLE
[NSCalendar] match Darwin API

### PR DESCRIPTION
**Pull request by damuellen**
On Darwin .currentCalendar() is now imported as .current()

### CODE REVIEW

**Comment by modocache** [comment]
@swift-ci please test

**Comment by modocache** [comment]
I'd merge if the tests pass.

@shahmishal, this looks like another instance of non-Apple committers being unable to trigger CI. I experienced the same issue last night, see: https://github.com/apple/swift-corelibs-xctest/pull/106#issuecomment-219345298.

**Comment by parkera** [comment]
@swift-ci please test

**Comment by damuellen** [comment]
@modocache I am puzzled that still no one has merged this pr. please test again and merge.

**Comment by modocache** [comment]
Sorry, @damuellen! I don't get a notification when Swift CI passes, which means I sometimes forget to check back 😭 

Could you rebase your changes? It looks like it can no longer be merged. Sorry!!

**Comment by damuellen** [comment]
@modocache I tried to rebase, but it didn't work, I will close this pr now, and create new one.

**Pull request closed without merging**
