### PR TITLE
Foundation: sundry fixes for Windows port

### PR DESCRIPTION
**Pull request by compnerd**
Adjust the source for LLP64 (Windows x64/AArch64) and account for
non-POSIX environment.  Collect them into a single change as they are
small enough to not be a problem to really inspect in a single batch.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by jakepetroules** [comment]
Looks generally fine to me

**Pull request merged**
