### PR TITLE
Implemented FileManager.temporaryDirectory

### PR DESCRIPTION
**Pull request by dplanitzer**

### CODE REVIEW

**Comment by phausler** [comment]
@swift-ci please test and merge

**Comment by spevans** [comment]
@swift-ci please test and merge

**Comment by pushkarnk** [comment]
```
FAIL: Swift(linux-x86_64) :: ClangImporter/clang_builtins.swift (10348 of 10368)
******************** TEST 'Swift(linux-x86_64) :: ClangImporter/clang_builtins.swift' FAILED ********************
```

**Comment by pushkarnk** [comment]
Retrying

@swift-ci please test and merge

**Comment by pushkarnk** [comment]
@swift-ci please test and merge

**Pull request merged**
