### PR TITLE
compatibility with ObjCBool

### PR DESCRIPTION
**Pull request by weissi**
we need to be compatible with https://developer.apple.com/documentation/objectivec/objcbool

### CODE REVIEW

**Comment by weissi** [comment]
CC @lukasa

**Comment by ianpartridge** [comment]
https://github.com/apple/swift-corelibs-foundation/pull/1223 🙂

**Comment by spevans** [comment]
I think this is actually a better solution than mine in https://github.com/apple/swift-corelibs-foundation/pull/1223, see my comment about using the struct from the stdlib.

**Comment by ianpartridge** [comment]
Hi @weissi - I think the merging of https://github.com/apple/swift-corelibs-foundation/pull/1223 supercedes this. Please reopen this PR if you disagree for any reason!

**Comment by weissi** [comment]
@ianpartridge indeed, thanks 👍

**Pull request closed without merging**
