### PR TITLE
Store cookies in XDG_DATA_HOME instead of XDG_CONFIG_HOME

### PR DESCRIPTION
**Pull request by mamabusi**

### CODE REVIEW

**Comment by pushkarnk** [comment]
1000th pull request !

**Comment by pushkarnk** [comment]
@swift-ci test

**Comment by pushkarnk** [comment]
@swift-ci test

**Comment by pushkarnk** [comment]
@swift-ci please test

**Comment by mamabusi** [comment]
@pushkarnk Could you please run the CI Build again. I have pushed in the necessary changes to fix the test-failures.

**Comment by parkera** [comment]
@swift-ci please test

**Comment by pushkarnk** [comment]
@swift-ci please test

**Comment by mamabusi** [comment]
@pushkarnk @parkera The test-failure is because of a bug in Cookie Storage where it fails to create non-existing parent directories. A fix for this is already available in the open PR: https://github.com/apple/swift-corelibs-foundation/pull/1003

**Comment by pushkarnk** [comment]
We have #1003 merged now. Lets try to merge this one as well.

@swift-ci test and merge

**Comment by pushkarnk** [comment]
@swift-ci test and merge

**Pull request merged**
