### PR TITLE
Re-core Foundation on top of swift-foundation (merge package branch into main)

### PR DESCRIPTION
**Pull request by jmschonfeld**
This change merges the `package` branch (tracking all of our work to re-core Foundation on top of swift-foundation that many folks have been working on) into the `main` branch. At this point, all tests pass on Linux and Windows and we're able to produce functional Linux and Windows toolchains in swift-ci. This change may be too large to review itself, but this work has been reviewed in pieces over the course of a number of months via PRs to the `package` branch.

Resolves https://github.com/apple/swift-corelibs-foundation/issues/5001

### CODE REVIEW

**Review by parkera — APPROVED** [review]

**Comment by jmschonfeld** [comment]
https://github.com/swiftlang/swift/pull/75255
https://github.com/swiftlang/swift-installer-scripts/pull/312

@swift-ci please test

**Review by iCharlesHu — APPROVED** [review]
Yayyyyyyy

**Comment by jmschonfeld** [comment]
https://github.com/swiftlang/swift-installer-scripts/pull/312

@swift-ci please test Linux platform

**Comment by jmschonfeld** [comment]
The macOS failure is known - this repo no longer builds for macOS and macOS testing is no longer required. Linux and Windows test have now passed which means we're clear to merge the re-core

**Pull request merged**
