### PR TITLE
Linux: ProcessInfo.activeProcessorCount: Allow for bad data in CFS quota files

### PR DESCRIPTION
**Pull request by spevans**

### CODE REVIEW

**Comment by spevans** [comment]
@swift-ci test

**Comment by spevans** [comment]
@swift-ci test

**Comment by spevans** [comment]
@swift-ci test

**Comment by spevans** [comment]
@swift-ci test

**Comment by spevans** [comment]
@swift-ci test linux

**Comment by spevans** [comment]
@swift-ci test linux

**Comment by spevans** [comment]
@swift-ci test linux

**Comment by tomerd** [comment]
@spevans is this ready for review / merge?

**Comment by spevans** [comment]
@swift-ci test and merge

**Pull request merged**
