### PR TITLE
[5.0] SR-10619: Order in which DateFormatter settings are set up matters on…

### PR DESCRIPTION
**Pull request by weissi**
… Linux

- Ensure the setting of .dateStyle and .timeStyle isnt dependant on the
  current setting of .locale.

(cherry picked from commit 3ceecb1)
original PR #2265

### CODE REVIEW

**Comment by kevints** [comment]
@swift-ci please test

**Comment by kevints** [comment]
@weissi this one needs a rebase

**Comment by weissi** [comment]
thanks @kevints, done

**Comment by kevints** [comment]
@swift-ci test and merge

**Comment by millenomi** [comment]
@swift-ci please test and merge

**Pull request merged**
