### PR TITLE
[5.5] test_requestWithNonEmptyBody is failing consistently and blocking the Amazon Linux CI

### PR DESCRIPTION
**Pull request by millenomi**
Same as the main branch patch.

(cherry picked from commit 631abc69d45743bb241652552126fd010909a162)

### CODE REVIEW

**Comment by millenomi** [comment]
cc @tomerd — PR as requested by @shahmishal

**Comment by millenomi** [comment]
@swift-ci please test

**Comment by tomerd** [comment]
thanks ro looping me in @millenomi are we sure this only a test issue and not a real issue the test is pointing to?

cc @drexin

**Comment by millenomi** [comment]
@shahmishal is asking to stop this either way because, issue or not, it's blocking CI and we have a zero CI block policy.

Since nothing changed in FoundationNetworking, I strongly suspect a node or test setup issue.

**Pull request merged**
