### PR TITLE
[4.0] SR-5640: JSONEncoder misrepresents UInt.max

### PR DESCRIPTION
**Pull request by ianpartridge**
Cherry-pick of #1173 to `swift-4.0-branch`.

### CODE REVIEW

**Comment by ianpartridge** [comment]
@swift-ci please test

**Comment by parkera** [comment]
I think we're still waiting on an official tag for swift-4.0 before we continue to make fixes on this branch.

**Comment by ianpartridge** [comment]
Reopening to get this into the 4.0 branch.

**Comment by ianpartridge** [comment]
@swift-ci please test

**Comment by ianpartridge** [comment]
@swift-ci please test

**Comment by ianpartridge** [comment]
@swift-ci please test

**Comment by ianpartridge** [comment]
@swift-ci please test and merge

**Comment by ianpartridge** [comment]
@swift-ci please test and merge

**Pull request merged**
