### PR TITLE
CountableRange is deprecated, renamed to Range

### PR DESCRIPTION
**Pull request by spevans**
- Replace NSRange.toCountableRange() with Range.init?(_:)

- Update Test cases.

### CODE REVIEW

**Comment by spevans** [comment]
@swift-ci please test

**Comment by parkera** [comment]
@airspeedswift does this line up with the changes you've been working on here too?

**Comment by airspeedswift** [comment]
Please don't make this change. I already made it originally and had to revert it, because we don't have a 5.0 branch for corelibs-foundation, so Linux testing of the 5.0 swift branch started failing.

That said, it is a good point that the `toCountableRange` method should be replaced by just a `Range.init`. But that'll break stuff too so please hold off for now. 5.0 branch will rebranch soon, then we can do it.

**Comment by spevans** [comment]
@swift-ci please test

**Comment by airspeedswift** [comment]
Now that the conditionally-conforming `Range` is available on 4.2, I think this is gtm.

**Comment by spevans** [comment]
@swift-ci please test and merge

**Pull request merged**
