### PR TITLE
Build fix: XCAssertEqual -> XCTAssertEqual

### PR DESCRIPTION
**Pull request by millenomi**
Fixes a build break where a merge happened without me reinvoking tests on it. (Whoops.)

### CODE REVIEW

**Comment by millenomi** [comment]
@swift-ci please test and merge

**Comment by millenomi** [comment]
@swift-ci please test and merge

**Comment by compnerd** [comment]
@swift-ci please test and merge

**Comment by compnerd** [comment]
@swift-ci please test and merge

**Comment by compnerd** [comment]
@swift-ci please test and merge

**Pull request merged**
