### PR TITLE
[5.0] Cherry-pick: Speedup for NSString -getCharacters:range

### PR DESCRIPTION
**Pull request by Catfish-Man**
See https://github.com/apple/swift-corelibs-foundation/pull/1928

### CODE REVIEW

**Comment by millenomi** [comment]
@swift-ci please test 5.0

**Comment by millenomi** [comment]
@swift-ci please test

**Comment by millenomi** [comment]
LGTM.

**Comment by spevans** [comment]
@weissi I tested this on Ubuntu18.04 and it seems to cause the `swift-5.0-branch` to fail some (unrelated) tests. 

Where reverting back to before this commit, the tests pass. Most odd.

```
/home/spse/swift-source/swift-corelibs-foundation/TestFoundation/TestURLSession.swift:175: error: TestURLSession.test_dataTaskWithHttpInputStream : Asynchronous wait failed - Exceeded timeout of 12.0 seconds, with unfulfilled expectations: POST http://127.0.0.1:36679/echo: with HTTP Body as InputStream
Test Case 'TestURLSession.test_dataTaskWithHttpInputStream' failed (12.001 seconds)
Test Case 'TestURLSession.test_downloadTaskWithURL' started at 2019-04-19 17:04:29.634
Test Case 'TestURLSession.test_downloadTaskWithURL' passed (8.0 seconds)
Test Case 'TestURLSession.test_downloadTaskWithURLRequest' started at 2019-04-19 17:04:37.634
Test Case 'TestURLSession.test_downloadTaskWithURLRequest' passed (8.0 seconds)
Test Case 'TestURLSession.test_downloadTaskWithRequestAndHandler' started at 2019-04-19 17:04:45.634
/home/spse/swift-source/swift-corelibs-foundation/TestFoundation/TestURLSession.swift:214: error: TestURLSession.test_downloadTaskWithRequestAndHandler : Asynchronous wait failed - Exceeded timeout of 12.0 seconds, with unfulfilled expectations: Download GET http://127.0.0.1:36679/country.txt: with a completion handler
/home/spse/swift-source/swift-corelibs-foundation/TestFoundation/TestURLSession.swift:210: error: TestURLSession.test_downloadTaskWithRequestAndHandler : XCTAssertNil failed: "URLError(_nsError: The operation could not be completed)" - error = URLError(_nsError: The operation could not be completed)
Test Case 'TestURLSession.test_downloadTaskWithRequestAndHandler' failed (20.002 seconds)
Test Case 'TestURLSession.test_downloadTaskWithURLAndHandler' started at 2019-04-19 17:05:05.636
Test Case 'TestURLSession.test_downloadTaskWithURLAndHandler' passed (8.001 seconds)
Test Case 'TestURLSession.test_finishTaskAndInvalidate' started at 2019-04-19 17:05:13.637
/home/spse/swift-source/swift-corelibs-foundation/TestFoundation/TestURLSession.swift:161: error: TestURLSession.test_finishTaskAndInvalidate : XCTAssertNotNil failed - 
/home/spse/swift-source/swift-corelibs-foundation/TestFoundation/TestURLSession.swift:162: error: TestURLSession.test_finishTaskAndInvalidate : XCTAssertNotNil failed - 
/home/spse/swift-source/swift-corelibs-foundation/TestFoundation/TestURLSession.swift:163: error: TestURLSession.test_finishTaskAndInvalidate : XCTAssertNil failed: "URLError(_nsError: The operation could not be completed)" - 
/home/spse/swift-source/swift-corelibs-foundation/TestFoundation/TestURLSession.swift:167: error: TestURLSession.test_finishTaskAndInvalidate : failed - response (nil) invalid
Test Case 'TestURLSession.test_finishTaskAndInvalidate' failed (3.998 seconds)
```

**Pull request merged**
