### PR TITLE
Update legacy constructors, functions, and constants

### PR DESCRIPTION
**Pull request by rauhul**
- replaces *Make constructors with swift initializers
- replaces NSZeroPoint/Size/Rect with .zero

### CODE REVIEW

**Comment by rauhul** [comment]
@swift-ci please test

**Comment by spevans** [comment]
@swift-ci test

**Comment by rauhul** [comment]
@parkera it doesn't seem like these failures are related to my changes. Is there something I'm missing?

**Comment by parkera** [comment]
Let's try again...

**Comment by parkera** [comment]
@swift-ci clean test

**Comment by rauhul** [comment]
@swift-ci clean test

**Comment by rauhul** [comment]
@parkera it seems like swift-ci isn't launching new tests, any thoughts?

**Comment by rauhul** [comment]
@swift-ci please test

**Comment by spevans** [comment]
@swift-ci test

**Comment by alblue** [comment]
Looks like related test failures on the Linux build; can you investigate?

> 03:11:36 TestFoundation/TestNSGeometry.swift:964: error: TestNSGeometry.test_NSUnionRect : XCTAssertTrue failed - 
> 03:11:36 TestFoundation/TestNSGeometry.swift:965: error: TestNSGeometry.test_NSUnionRect : XCTAssertTrue failed - 
>

**Comment by rauhul** [comment]
So I've been having a pretty terrible time trying to get an ubuntu area working. Regardless I did some tests on macOS and I'm not even sure how the macOS test passed:
``` swift 
Welcome to Apple Swift version 4.2 (swiftlang-1000.11.37.1 clang-1000.11.45.1). Type :help for assistance.
  1> import Foundation
  2> let r1 = NSRect(x: CGFloat(1.2), y: CGFloat(3.1), width: CGFloat(10.0), height: CGFloat(10.0))
r1: NSRect = (origin = (x = 1.2, y = 3.1000000000000001), size = (width = 10, height = 10))
  3> let r2 = NSRect(x: CGFloat(10.2), y: CGFloat(2.5), width: CGFloat(5.0), height: CGFloat(5.0))
r2: NSRect = (origin = (x = 10.199999999999999, y = 2.5), size = (width = 5, height = 5))
  4> NSIsEmptyRect(NSRect.zero.union(NSRect.zero))
$R0: Bool = true
  5> NSEqualRects(r1, r1.union(NSRect.zero))
$R1: Bool = false
  6> NSEqualRects(r2, NSRect.zero.union(r2))
$R2: Bool = false
  7> NSIsEmptyRect(NSUnionRect(NSZeroRect, NSZeroRect))
$R3: Bool = true
  8> NSEqualRects(r1, NSUnionRect(r1, NSZeroRect))
$R4: Bool = true
  9> NSEqualRects(r2, NSUnionRect(NSZeroRect, r2))
$R5: Bool = true
```
I'm going to look into the difference between NSRect.zero and NSZeroRect on macOS to start.

**Comment by rauhul** [comment]
It seems like CGRect.union and NSUnionRect have completely different behaviors.

https://github.com/apple/swift-corelibs-foundation/blob/a61b058ed53b00621e7acba4c53959e3ae01a254/Foundation/NSGeometry.swift#L303-L323

https://github.com/apple/swift-corelibs-foundation/blob/a61b058ed53b00621e7acba4c53959e3ae01a254/Foundation/NSGeometry.swift#L852-L867

@parkera is this expected?

**Comment by parkera** [comment]
Honestly, not sure about this one. You're saying the behavior is different on Darwin too?

**Comment by rauhul** [comment]
Yeah it seems like they do behave differently. I tested with a small macOS command line application [testapp.zip](https://github.com/apple/swift-corelibs-foundation/files/2443197/testapp.zip)

**Application output**
``` groovy
Rectangles
r1: (1.2, 3.1, 10.0, 10.0)
r2: (10.2, 2.5, 5.0, 5.0)

CoreGraphics Implementations
r1 union zero: (0.0, 0.0, 11.2, 13.1)
zero union r2: (0.0, 0.0, 15.2, 7.5)

NSGeometry Implementations
r1 union zero: (1.2, 3.1, 10.0, 10.0)
zero union r2: (10.2, 2.5, 5.0, 5.0)
```

I guess I should revert the test changes, however I'm not sure how "Swift Test macOS Platform" passed.

**Comment by spevans** [comment]
@rauhul I think the "Swift Test macOS Platform"  just compiles the code but it doesn't run the tests.

**Comment by rauhul** [comment]
@swift-ci test

**Comment by millenomi** [comment]
@swift-ci test

**Comment by millenomi** [comment]
@swift-ci please test

**Comment by millenomi** [comment]
@swift-ci please test and merge

**Pull request merged**
