### PR TITLE
Fix Notification API signatures to match Darwin

### PR DESCRIPTION
**Pull request by ianpartridge**

### CODE REVIEW

**Comment by ianpartridge** [comment]
@swift-ci please test

**Comment by ianpartridge** [comment]
@swift-ci please test and merge

**Comment by atrick** [comment]
I'm not sure why this passed PR testing. CI testing on Ubuntu 16 reports

Test Case 'TestNotificationCenter.test_postNotification' started at 2017-08-02 22:33:02.555
/home/buildnode/jenkins/workspace/oss-swift-incremental-RA-linux-ubuntu-16_10/swift/utils/build-script-impl: line 261: 36420 Segmentation fault      "$@"
/home/buildnode/jenkins/workspace/oss-swift-incremental-RA-linux-ubuntu-16_10/swift/utils/build-script: fatal error: command terminated with a non-zero exit status 139, aborting
/home/buildnode/jenkins/workspace/oss-swift-incremental-RA-linux-ubuntu-16_10/swift/utils/build-script: fatal error: command terminated with a non-zero exit status 1, aborting

https://ci.swift.org/job/oss-swift-incremental-RA-linux-ubuntu-16_10/4985/

**Comment by atrick** [comment]
It looks like this only failed on Ubuntu 16.10, any ideas?

**Pull request merged**
