### PR TITLE
[NSNotificationCenter] Implement observation with optional queues.

### PR DESCRIPTION
**Pull request by swizzlr**
Please review!

Pending fix of OperationQueue.

### CODE REVIEW

**Comment by parkera** [comment]
This looks good to me although we could use some tests as well. To @phausler for review.

**Comment by phausler** [comment]
Looks good to me

@swift-ci Please test

**Comment by swizzlr** [comment]
Oops, yes.

**Comment by parkera** [comment]
Let us know when you've added a test case for this and we'll get it merged.

**Comment by swizzlr** [comment]
Hey all, sorry for the delay in this. The above commit adds the tests; however it is incorrectly named: NSOperation has a bug that is beyond the scope of this PR IMO, with terrible queue handling. Will be filing a PR to fix soon, so this PR can depend on that.

**Comment by parkera** [comment]
Ok so you're saying here that this test won't pass until the other PR is merged?

**Comment by swizzlr** [comment]
@parkera yes; or I need to rewrite the test to not relay on OperationQueue.current – but I can't think of a good way to test this without basically doing the work needed to fix OperationQueue. Please review the tests as you like; I will do my best to fix soon.

**Comment by parkera** [comment]
Test looks good to me.

**Comment by ikesyo** [comment]
`Docs/Status.md` should be updated as well. 😉

**Comment by alblue** [comment]
This pull request has gone stale. If you can rebase against master and re-run the tests, feel free to reopen this pull request.

**Pull request closed without merging**
