### PR TITLE
More tests for OperationQueue/Operaion

### PR DESCRIPTION
**Pull request by lxbndr**
There are some issues in current implementation. To keep things simple, I'd like to extend
test coverage of problem area first. Not all of new tests are expected to fail, but I find them useful
to have.

CC @compnerd

### CODE REVIEW

**Comment by spevans** [comment]
@swift-ci test linux

**Comment by spevans** [comment]
@swift-ci test linux

**Comment by spevans** [comment]
@swift-ci test linux

**Comment by compnerd** [comment]
Windows Run: https://dev.azure.com/compnerd/swift-build/_build/results?buildId=30724&view=results

**Pull request merged**
