### PR TITLE
[SR-7938] Add URLProtectionSpace.description

### PR DESCRIPTION
**Pull request by cmilr**
Hi, first-time contributor here—_hoping this PR is useful_. It was actually harder to implement than I was expecting.

### CODE REVIEW

**Comment by spevans** [comment]
You may need to change `XCTAssert(space.description.hasPrefix("<URLProtectionSpace "))` to `XCTAssert(space.description.hasPrefix("<\(type(of: space)) "))` since Darwin looks to use `NSURLProtectionSpace` internally

**Comment by spevans** [comment]
@swift-ci please test

**Comment by cmilr** [comment]
@spevans the DarwinCompatabilityTests crash on running, before I even add my test file. I'm getting:

`Thread 1: Fatal error: The unit test must specify the correct number of flags and arguments.` in the xdgTestHelper.

**Comment by cmilr** [comment]
@spevans in `DarwinCompatibilityTests` I had to comment out a couple of tests in `TestBundle`, as they were causing the project not to build. Not sure if I should leave them commented out, or how that works? Otherwise, I got my code passing with one minor tweak to my test file. Now it passes in both.

**Comment by parkera** [comment]
Welcome @cmilr and thanks for the contribution!

**Comment by spevans** [comment]
@swift-ci please test and merge

**Pull request merged**
