### PR TITLE
[gardening] Remove unnecessary `break`s

### PR DESCRIPTION
**Pull request by ikesyo**

### CODE REVIEW

**Comment by parkera** [comment]
Could we also apply the changes to the value type classes to the overlay in the Swift project as well?

**Comment by parkera** [comment]
@swift-ci please test and merge

**Comment by ikesyo** [comment]
> Could we also apply the changes to the value type classes to the overlay in the Swift project as well?

I will tackle it.

**Comment by ikesyo** [comment]
https://github.com/apple/swift/pull/6735

**Pull request merged**
