### PR TITLE
build: Add scripts to build and test using Xcode

### PR DESCRIPTION
**Pull request by spevans**
- xcode-build.sh builds and optionally tests SwiftFoundation.
  usage: ./xcode-build.sh [--clean] [--test]

- DarwinCompatibilityTests/xcode-build.sh builds and tests using
  the DarwinCompatibilityTests.
  usage: DarwinCompatibilityTests/xcode-build.sh [--clean]

This adds two shell scripts for building/testing scl-foundation using Xcode as a check that changes don't break the Xcode builds for `TestFoundation` and `DarwinCompatibilityTests`. A recent toolchain snapshot is required. The idea is that both scripts could be hooked up to `swift-ci test` commands to enable extra CI testing. If these scripts look OK, I will open a jira to get swift-ci updated.

The `DarwinCompatibiltyTests` only includes test classes that currently work without any failing test cases.

### CODE REVIEW

**Comment by spevans** [comment]
cc @millenomi @shahmishal

**Comment by spevans** [comment]
@swift-ci test

**Comment by spevans** [comment]
@swift-ci test linux

**Comment by millenomi** [comment]
Why do we need the script again?

**Comment by spevans** [comment]
I want to get a swift-ci target setup that allows testing a PR against the Dawin Compatibility Tests. 
A second one can be setup to build/run the normal `TestFoundation` tests so that we can catch issues that break the Xcode build. These can be built against snapshot toolchains so should be quite quick to run.

**Comment by millenomi** [comment]
Good enough. Do you want to set the toolchain in the script?

**Comment by spevans** [comment]
@millenomi Im not sure how to set the toolchain, ideally the swift-ci would just use the latest one available, I assume it would need to download it and set it as the default in Xcode as part of its setup before invoking the script.

**Comment by spevans** [comment]
@swift-ci test

**Comment by gottesmm** [comment]
@spevans We do that for the protobuf builds. E.x.:

https://ci.swift.org/view/all/job/swift-protobuf-linux-ubuntu-16_04/1222/consoleFull

I would talk with Mishal about the frequency though. I imagine that we probably want to run it only when the toolchain changes.

**Comment by gottesmm** [comment]
And if that, probably at most once a day (if not once a week).

**Comment by spevans** [comment]
@gottesmm I opened https://bugs.swift.org/browse/SR-10990 for getting the test setup. For now I just want the ability to run them manually as there will be times when they would fail (eg with a PR dependant on a PR in another repo where its not in a toolchain) , eventually they may get added to the swift-ci test for scl-f alongside linux and macos

**Comment by spevans** [comment]
Please test with following PR:

apple/swift-integration-tests#58
@swift-ci test

**Comment by spevans** [comment]
@swift-ci test

**Comment by spevans** [comment]
@swift-ci test and merge

**Pull request merged**
