### PR TITLE
[3.1] Backport HTTPCookieStorage

### PR DESCRIPTION
**Pull request by ianpartridge**
Now that #889 is merged to `master` we would like to add this to the 3.1 branch too.

### CODE REVIEW

**Comment by pushkarnk** [comment]
@swift-ci please test

**Comment by pushkarnk** [comment]
@ianpartridge This needs the implementation of `Process.terminationReason` - [this commit](https://github.com/apple/swift-corelibs-foundation/commit/4dd7b98012fe84e42a8b010bec5b2857bca6276b) on the master is missing from 3.1

**Comment by ianpartridge** [comment]
Thanks @pushkarnk I'll port that as well.  Do you think it would be better as a separate PR?

**Comment by pushkarnk** [comment]
Yes, I'd suggest doing it in a separate PR.

**Comment by ianpartridge** [comment]
@pushkarnk - #964 is merged, can you re-run the CI please?

**Comment by pushkarnk** [comment]
@swift-ci test and merge

**Pull request merged**
