### PR TITLE
Cherry-pick NSJSONSerialization fixes for 3.0.1

### PR DESCRIPTION
**Pull request by pushkarnk**

### CODE REVIEW

**Comment by pushkarnk** [comment]
@swift-ci please test

**Comment by pushkarnk** [comment]
Thanks @parkera

**Comment by pushkarnk** [comment]
@parkera : Do we have a plan to make these available in preview 4?

**Comment by parkera** [comment]
They should be available in the next branch/tag off of swift-3.0-branch.

**Pull request merged**
