### PR TITLE
Remove hasPrefix/Suffix as they are now on String for Linux 

### PR DESCRIPTION
**Pull request by airspeedswift**
Needs coordination with apple/swift#14390, which introduces the `String` versions.

### CODE REVIEW

**Comment by airspeedswift** [comment]
Test with https://github.com/apple/swift/pull/14390

@swift-ci please test

**Comment by spevans** [comment]
@airspeedswift `Foundation/NSString.swift` has `hasPrefix/hasSuffix` extensions for both `NSString` and `String`. I think the wrong pair got removed here.

**Comment by airspeedswift** [comment]
@spevans yup/oops

**Comment by airspeedswift** [comment]
Test with apple/swift#14390

@swift-ci please test

**Comment by airspeedswift** [comment]
Test with apple/swift#14390

@swift-ci please test

**Comment by airspeedswift** [comment]
Test with apple/swift#14390

@swift-ci please test

**Comment by airspeedswift** [comment]
@parkera OK with you to merge this? I'll merge the stdlib change onto the 5.0 branch too to keep the 5.0 bots working.

**Comment by parkera** [comment]
Does this really have the same behavior? The previous code used `kCFCompareNonliteral` ("If specified, loose equivalence is performed (o-umlaut == o, umlaut)").

**Comment by parkera** [comment]
If so perhaps we should encapsulate that behavior in a unit test just so we have it documented as behaving as expected.

**Comment by airspeedswift** [comment]
@parkera Yes, this will consider the two compositions of `ö` the same, since it uses `Character.==` which has that behavior. The tests on the stdlib version are pretty extensive already for this and cover lots of different compositions.

**Comment by airspeedswift** [comment]
(and the Linux version will now be covered by those tests too)

**Comment by parkera** [comment]
Ok

**Pull request merged**
