### PR TITLE
Create StringMap.swift

### PR DESCRIPTION
**Pull request by omarshariffathi**
This is a fast way to search and match strings from a String Array

This implementation is mainly improving the time taken to match a string from a string array. This isn't a complex or long implementation like other implementations, yet drastically reduces the time taken to do such searching and matching tasks. 

This is a faster implementation for String `hasSuffix` & `hasPrefix` & == but for large String arrays.
This is a short yet efficient and to the point implementation. No concurrency.

### CODE REVIEW

**Comment by parkera** [comment]
Hi @omarshariffathi. In general, we are not adding new API to swift-corelibs-foundation but instead focusing on finishing up the implementation of the APIs we already have. We can discuss more on the mailing list if you like, but for now I'll go ahead and close this. Thanks.

**Comment by parkera** [comment]
This functionality seems like a great candidate of something to ship via the Swift package manager, actually.

**Comment by omarshariffathi** [comment]
Yea so I should first ship it via SPM, I have a copy live on Cocoapods now but I will make it available for SPM as well, thanks @parkera

**Comment by o-micron** [comment]
This is a quick update, I have create a SPM for StringMap here https://github.com/o-micron/StringMap,
and here is a quick gist showing the huge performance gain using StringMap for full matching Strings compared to google's RE2.

**Pull request closed without merging**
