### PR TITLE
Add missing `NSNotification.Name.init(_:)`

### PR DESCRIPTION
**Pull request by ikesyo**
https://developer.apple.com/documentation/foundation/nsnotification/name/1924168-init

### CODE REVIEW

**Comment by ikesyo** [comment]
@swift-ci Please test

**Comment by ikesyo** [comment]
@swift-ci Please test Linux

**Comment by ikesyo** [comment]
@swift-ci Please test Linux

**Comment by ikesyo** [comment]
@swift-ci Please clean test Linux

**Comment by ikesyo** [comment]
@swift-ci Please test Linux

**Comment by spevans** [comment]
@swift-ci test linux

**Comment by ikesyo** [comment]
@swift-ci Please clean test Linux platform

**Comment by spevans** [comment]
@swift-ci test linux

**Comment by millenomi** [comment]
@swift-ci please test and merge

**Pull request merged**
