### PR TITLE
Adds nullability annotations to _CFStringCreateByRemovingPercentEncoding

### PR DESCRIPTION
**Pull request by brownleej**

### CODE REVIEW

**Comment by parkera** [comment]
@swift-ci please test

**Comment by parkera** [comment]
Looks good to me; let's try running it through the shiny new CI.

**Comment by shahmishal** [comment]
@swift-ci please test

**Comment by shahmishal** [comment]
@swift-ci please test

**Comment by shahmishal** [comment]
@swift-ci Please test

**Pull request merged**
