### PR TITLE
Optimize some CF Functions

### PR DESCRIPTION
**Pull request by AtariDreams**
A lot of these checks are redundant and would be better if grouped together in a control flow

### CODE REVIEW

**Comment by millenomi** [comment]
@swift-ci please test

**Comment by AtariDreams** [comment]
This originally failed because of a server issue, not a code issue. Can we please try this one more time

**Comment by AtariDreams** [comment]
@millenomi @parkera Any updates?

**Comment by parkera** [comment]
@AtariDreams a lot of these are in conflict now; is it still worth pursuing?

**Pull request closed without merging**
