### PR TITLE
NSOrderedSet: Implement more functionality

### PR DESCRIPTION
**Pull request by spevans**
- Add copy() and mutableCopy().

- Add .set and .array to return immumtable views of the current
  contents.

- Implement index(of:inSortedRange:options:usingComparator cmp:)
  by calling NSArray()'s version on ._orderedStorage.

- Implement description(withLocale:), description(withLocale:indent:),
  .description and .customMirror.

- NSCoding still needs to be implemented.

### CODE REVIEW

**Comment by spevans** [comment]
@swift-ci test

**Comment by spevans** [comment]
Note: Need to add some tests.

**Comment by millenomi** [comment]
Fixes https://bugs.swift.org/browse/SR-10405, https://bugs.swift.org/browse/SR-10406, https://bugs.swift.org/browse/SR-10407, https://bugs.swift.org/browse/SR-10408

**Comment by millenomi** [comment]
Can you use `storage._swiftObject` instead?

**Comment by spevans** [comment]
I looked at how `NSArray` and `NSSet` implemented `copy` and `mutableCopy` and didn't see the use of `_swiftObject` there. Is it needed even though the types of the `Set` and `Array` are Swift not CF Types?

**Comment by spevans** [comment]
@swift-ci test linux

**Comment by spevans** [comment]
@swift-ci test linux

**Comment by spevans** [comment]
@swift-ci test linux

**Comment by millenomi** [comment]
@swift-ci please test

**Comment by millenomi** [comment]
The idea here is that we're hitting a compiler bug around casting, which is often problematic while developing s-c-f because s-c-f is part of the implementation of casting itself (and also has to coexist with the bridging setup on Darwin.) The guideline going forward is to avoid bridging casts and use `_swiftObject`, `_cfObject` and `_nsObject` where they exist, and `__SwiftValue.store(…)/.fetch(…)` otherwise if all you have is an `Any` or `AnyObject` (which will do the right thing wrt interacting with bridged values coming from the ObjC Foundation onDarwin). This only applies to s-c-f's codebase; outside, including in TestFoundation, it is okay to use bridging as usual.

**Comment by spevans** [comment]
@swift-ci  test

**Comment by spevans** [comment]
@swift-ci test

**Pull request merged**
