### PR TITLE
[SE-0069] UUID Value Type

### PR DESCRIPTION
**Pull request by colemancda**
Implements SE-0069 and potentially fixes [SR-1756](https://bugs.swift.org/browse/SR-1756).

### CODE REVIEW

**Comment by colemancda** [comment]
@parkera Can we test this please?

**Comment by michael-lehew** [comment]
@swift-ci please test

**Comment by parkera** [comment]
```
Foundation/NSUUID.swift:31:14: error: argument labels '(uuidBytes:)' do not match any available overloads
        self.init(uuidBytes: buffer)
             ^   ~~~~~~~~~~~~~~~~~~~
Foundation/NSUUID.swift:31:14: note: overloads for 'NSUUID.init' exist with these partially matching parameter lists: (uuidString: String), (UUIDBytes: UnsafePointer<UInt8>), (coder: NSCoder)
        self.init(uuidBytes: buffer)
             ^
Foundation/NSUUID.swift:71:18: error: argument labels '(uuidBytes:)' do not match any available overloads
            self.init(uuidBytes: buffer)
                 ^   ~~~~~~~~~~~~~~~~~~~
Foundation/NSUUID.swift:71:18: note: overloads for 'NSUUID.init' exist with these partially matching parameter lists: (uuidString: String), (UUIDBytes: UnsafePointer<UInt8>), (coder: NSCoder)
            self.init(uuidBytes: buffer)
                 ^
```

**Comment by colemancda** [comment]
I am confused `self.init(uuidBytes: buffer)` is the correct syntax. This should not be failing.

**Comment by phausler** [comment]
I manually merged this and corrected the failures on Linux

**Pull request closed without merging**
