### PR TITLE
change FileManager.default() class function to static let

### PR DESCRIPTION
**Pull request by jpsim**
to match Darwin version as of Xcode 8

### CODE REVIEW

**Comment by parkera** [comment]
Looks good.

**Comment by parkera** [comment]
@swift-ci please test

**Comment by CodaFi** [comment]
@jpsim This needs rebasing.

**Comment by jpsim** [comment]
rebased

**Comment by CodaFi** [comment]
LGTM as well.

@swift-ci please test and merge.

**Comment by CodaFi** [comment]
@swift-ci please test.

**Comment by CodaFi** [comment]
@jpsim Looks like you missed something in `NSTask.swift`.

**Comment by jpsim** [comment]
Indeed. Fixed.

**Comment by CodaFi** [comment]
Once more, with feeling.

@swift-ci please test.

**Comment by jpsim** [comment]
This should be merged with apple/swift-package-manager#584

**Comment by ddunbar** [comment]
Unfortunately this has been conflicted... @jpsim I can shepherd landing this (swift-ci can't handle multi-repo PRs yet) if someone rebases it.

**Comment by jpsim** [comment]
@ddunbar rebased again 😅

**Comment by ddunbar** [comment]
Thanks, testing now...

**Comment by ddunbar** [comment]
Merged, thank you!

**Pull request merged**
