### PR TITLE
Parity: FileManager: File display names.

### PR DESCRIPTION
**Pull request by millenomi**
Implement displayName(atPath:) insofar as is possible in a cross-platform manner, and componentsToDisplay(forPath:) as a function of that.

### CODE REVIEW

**Comment by millenomi** [comment]
Fixes https://bugs.swift.org/browse/SR-10359

**Comment by millenomi** [comment]
@swift-ci please test and merge

**Comment by millenomi** [comment]
@swift-ci please test

**Comment by millenomi** [comment]
@swift-ci please test and merge

**Comment by millenomi** [comment]
@swift-ci please test and merge

**Comment by spevans** [comment]
@swift-ci please test and merge

**Pull request merged**
