### PR TITLE
SR-11411: Update GettingStarted.md

### PR DESCRIPTION
**Pull request by spevans**
Update the document to reflect current `cmake` usage.

@compnerd @millenomi This is based on the commands I use, do you have anything to add/alter?

### CODE REVIEW

**Comment by compnerd** [comment]
Thanks for adding the blurb on running individual tests, thats extremely valuable.  LGTM (might be nice to wait a day or so to see if @millenomi chimes in)

**Comment by spevans** [comment]
@swift-ci test and merge

**Comment by compnerd** [comment]
macOS builds are known to be broken due to the dysmutil issue.  Im going to merge this as is.  If you know how to convert the build from `dwarf-with-dsym` to `dwarf`, would you mind putting up a PR to switch modes?

**Comment by spevans** [comment]
The macOS build is actually pointless in this repo as according to `build-scrip-impl`:
```
if [[ ${host} == "macosx"* ]]; then
    echo "Skipping Foundation on OS X -- use the Xcode project instead"
    continue
fi
```

**Pull request merged**
