### PR TITLE
Disable TestNSString#test_FromContentsOfURL as being flaky

### PR DESCRIPTION
**Pull request by xedin**
https://bugs.swift.org/browse/SR-10505

### CODE REVIEW

**Comment by xedin** [comment]
@swift-ci please test Linux platform

**Comment by millenomi** [comment]
@swift-ci please test and merge

**Comment by xedin** [comment]
@swift-ci please test and merge

**Comment by xedin** [comment]
@swift-ci please test

**Comment by xedin** [comment]
Linux is having really bad day today

**Comment by millenomi** [comment]
@swift-ci please test linux

**Comment by millenomi** [comment]
No patches are mergeable today until we un-flake the tests.

**Comment by spevans** [comment]
Doesn't this need to be disabled in the list of tests at the top?

**Comment by spevans** [comment]
Doesn't this need to be disabled in the list of tests at the top?

**Comment by compnerd** [comment]
@spevans - yeah, this wouldn't build on Linux

**Comment by millenomi** [comment]
Good morning.

**Comment by millenomi** [comment]
@swift-ci please clean test

**Comment by millenomi** [comment]
@swift-ci please clean build

**Comment by millenomi** [comment]
@swift-ci please test

**Comment by millenomi** [comment]
@swift-ci please clean test

**Comment by millenomi** [comment]
@swift-ci please test

**Comment by millenomi** [comment]
@swift-ci please test

**Comment by millenomi** [comment]
@shahmishal Linux testing isn't triggering; is something off?

**Comment by shahmishal** [comment]
It will trigger soon, the load on Linux is high right now.

https://ci.swift.org/label/linux-pr/load-statistics?type=min

**Comment by shahmishal** [comment]
@swift-ci test Linux

**Comment by xedin** [comment]
This has been done in the separate PR.

**Pull request closed without merging**
