### PR TITLE
Updates for SE-0110 Part I

### PR DESCRIPTION
**Pull request by dduan**
For more information, see https://github.com/apple/swift/pull/3895

### CODE REVIEW

**Comment by CodaFi** [comment]
Confirming the NFC-ness of this change on my machine.  In the meantime can you squash this?

**Comment by dduan** [comment]
@CodaFi squashed. Good to merge?

**Comment by dduan** [comment]
Or should we wait for all dependencies to be verified to minimize the impact?

**Comment by CodaFi** [comment]
Because all of these patches are NFC I think they can go in as fast as you can serve them.  I have a machine setup that I'm going to keep rebasing onto these branches as you submit them and in the end I'm going to rebase onto the swift changes and run the whole thing.

**Comment by CodaFi** [comment]
@swift-ci please test.

**Comment by CodaFi** [comment]
🎆

**Pull request merged**
