### PR TITLE
Fix memory leaks by using more specialized xml*Free functions.

### PR DESCRIPTION
**Pull request by mattrajca**
Fixes https://bugs.swift.org/browse/SR-5256.

### CODE REVIEW

**Comment by parkera** [comment]
Does our current test case hit these lines?

**Comment by spevans** [comment]
TestXMLDocument.test_xpath() covers them.

**Comment by djones6** [comment]
I can confirm this fixes the leak. Thanks @mattrajca !

**Comment by ianpartridge** [comment]
@swift-ci please test and merge

**Comment by ianpartridge** [comment]
FYI @svanimpe this fixes the XML memory leak you reported on the Kitura slack 🙂

**Pull request merged**
