### PR TITLE
Fix StringTransform usage of forced casts.

### PR DESCRIPTION
**Pull request by drodriguez**
In Linux, a (constant?) CFString cannot be force casted to String
directly. The code generated for those values with optimizations enabled
was simply a crash. The changes uses `_swiftObject` to correctly
transform to a `Swift.String`.

There some other cases in Foundation where other enums are initialized
from CF values, but in those cases the literals of the CF values are
used, which avoids this problem.

Should fix the problems introduced in #2087 in Linux.

PD: I still think that #2087 changes the meaning of the test. It should be reverted or removed.

### CODE REVIEW

**Comment by millenomi** [comment]
… Oh, yep, that makes sense.

I have disabled a test that likely tripped on this issue in https://github.com/apple/swift-corelibs-foundation/pull/2142/files — can you revert the `testExpectedToFail` line about `test_substringFromCFString` and see if this fixes that?

**Comment by drodriguez** [comment]
I re-enabled the test (I didn’t pull from last night, so in my working directory it wasn’t disabled). Should be ready to test.

**Comment by millenomi** [comment]
@swift-ci please test

**Comment by drodriguez** [comment]
I think I pushed the new version before the test finished, and CI didn’t start a new test run.

**Comment by millenomi** [comment]
@swift-ci please test

**Pull request merged**
