### PR TITLE
Foundation: attempt a first pass symlink resolution

### PR DESCRIPTION
**Pull request by compnerd**
On Windows, rather than recursively expanding a path component by component, perform a first pass resolution at the given path.  This potentially influences the path resolution as the component traversal would possibly fail to resolve cross-drive references.

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @parkera

**Comment by compnerd** [comment]
@swift-ci please test

**Review by parkera — APPROVED** [review]
Do we need some kind of windows-specific unit test?

**Comment by compnerd** [comment]
@parkera I think it could be nice to do that, but I didn't want to put in the effort if this code path is unlikely to survive the rewrite of Foundation.  This was something that I ran across when getting the SourceKit-LSP tests resolved, so it is definitely something we hit.  The one thing that I worry about a test case for this is that it will potentially require running with elevated privileges (i.e. as "root") to create the symbolic links to traverse.  However, if we have existing test cases which do that and are passing, we should be able to accommodate that.

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by parkera** [comment]
Ok, that makes sense. LGTM then and thank you.

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Pull request merged**
