### PR TITLE
partially restructure the source tree

### PR DESCRIPTION
**Pull request by compnerd**
Restructure the Foundation modules into subdirectories for ease of discoverability.  This restructures the tree into the standard Apple framework-like layout with a subdirectory for each Swift "framework" module.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
Test with following PRs:
apple/swift#29634

@swift-ci please test Linux platform

**Comment by spevans** [comment]
Looks like there is a duplicate copy of `Boxing.swift` in `./Sources/FoundationNetworking/URLSession/Boxing.swift` even though the `./Sources/FoundationNetworking/CMakeLists.txt` refers to the one in `../Foundation/Boxing.swift`

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by compnerd** [comment]
@spevans removed the duplicate copy, thanks for pointing that out

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by spevans** [comment]
What is the benefit of moving all of the files around? Doesnt it now require knowledge of which subdirectory a file is in? Im not sure this actually helps in anyway.

**Comment by compnerd** [comment]
@spevans it actually helps quite a bit with discoverability.  It also makes it easier to grep within a single target (e.g. `FoundationNetworking` vs `FoundationXML`).

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please clean test

**Comment by compnerd** [comment]
@swift-ci please clean test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
Please test with following PRs:
apple/swift#29804

@swift-ci please test Linux platform

**Comment by compnerd** [comment]
Please test with following PRs:
apple/swift#29804

@swift-ci please test Linux platform

**Comment by compnerd** [comment]
Please test with following PRs:
apple/swift#29804

@swift-ci please test Linux platform

**Comment by compnerd** [comment]
Please test with following PRs:
apple/swift#29804

@swift-ci please test Linux platform

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by compnerd** [comment]
Please test with following PRs:
apple/swift-corelibs-xctest#298

@swift-ci please test Linux platform

**Comment by compnerd** [comment]
Please test with following PRs:
apple/swift-corelibs-xctest#298

@swift-ci please test Linux platform

**Comment by compnerd** [comment]
Please test with following PRs:
apple/swift-corelibs-xctest#298

@swift-ci please test Linux platform

**Comment by compnerd** [comment]
Please test with following PRs:
apple/swift-corelibs-xctest#298

@swift-ci please test Linux platform

**Pull request merged**
