### PR TITLE
fix two non-owned strings being freed

### PR DESCRIPTION
**Pull request by weissi**
fixes https://bugs.swift.org/browse/SR-4860

### CODE REVIEW

**Comment by weissi** [comment]
@swift-ci please test

**Comment by parkera** [comment]
Looks good, thanks.

**Comment by weissi** [comment]
@parkera thanks! Do you want me to merge?

**Comment by weissi** [comment]
@parkera oh and is there anything special to do to get this into Swift 4.0?

**Comment by parkera** [comment]
We're still merging from master to swift 4, so we're good there.

**Pull request merged**
