### PR TITLE
[Need Feedback]: Added bounds checking to NSArray subscript

### PR DESCRIPTION
**Pull request by KaiCode2**
Completed bounds checking however I need feedback on what should should be done if the index is out of range.

### CODE REVIEW

**Comment by KaiCode2** [comment]
@phausler I corrected the PR to incorporate the changes you mentioned. Let me know if there is anything else to add 🙂

**Comment by parkera** [comment]
Thanks, this looks good. Could you rebase this into a single commit for us to merge in?

**Comment by Adlai-Holler** [comment]
Would `precondition(idx >= 0 && idx < count)` be a cleaner equivalent?

**Comment by KaiCode2** [comment]
@parkera finished the rebase, let me know if it's all good.

**Comment by parkera** [comment]
@Adlai-Holler precondition sounds like it might be good too, since it takes the optimization level into account. We can consider that as another change (also perhaps moving this into the objectAtIndex call itself as discussed on mailing list).

**Comment by KaiCode2** [comment]
@Adlai-Holler I think the issue with the precondition is the lack of an error message if the condition fails. Providing an error message is something I think is quite important to do.

**Comment by gribozavr** [comment]
You can provide a message as the second parameter to `precondition()`.  The message is displayed in debug builds.

**Pull request merged**
