### PR TITLE
Guard clauses for NSRequiresConcreteImplementation

### PR DESCRIPTION
**Pull request by kouky**
Use `guard` statements to exit early with `NSRequiresConcreteImplementation()`. This approach is more succinct, and has the added safety of `guard` requiring a transfer of program control.

### CODE REVIEW

**Comment by parkera** [comment]
@swift-ci please test

**Comment by kouky** [comment]
@parkera the CI failure is the same for PR #372 

`_swift_stdlib_unicode_strToLower' can not be used when making a shared object`

I've been working off the `swift-3.0-preview-1-branch` as a base as `master` has build failures on OSX when running the latest swift toolchain for Xcode. Merging master into this PR branch might fix the issue.

Just before I do can you please run CI against current master? It would be helpful to have a green baseline.

**Comment by parkera** [comment]
Yah we're in a bad state with the CI right now. I think it's going to clear up soon.

**Comment by parkera** [comment]
@swift-ci please test

**Comment by kouky** [comment]
@parkera i've merged master into this branch, the base commit for this branch is too old. Can we please run CI against it again?

**Comment by parkera** [comment]
This should be good to go now

**Comment by parkera** [comment]
@swift-ci please test

**Comment by kouky** [comment]
@parkera awesome, my first PR merged 🎉

**Comment by parkera** [comment]
Congrats and thank you!

**Pull request merged**
