### PR TITLE
Fixed documentation on Calendar.compare()

### PR DESCRIPTION
**Pull request by ArtSabintsev**
The `compare` method on `Calendar` said `orderedAscending` twice, when it meant to say `orderedAscending` and `orderedDescending`.

### CODE REVIEW

**Comment by alblue** [comment]
Looks good, but can you squash these into a single commit and rebase onto master, instead of having the merge node?

**Comment by ArtSabintsev** [comment]
Sure, though, I think squashing will require and rebasing will require another PR. Let me try that and open a new one up. I'll keep this one open until then.

**Comment by parkera** [comment]
Do we have the same error in the Swift overlay version?

**Comment by ArtSabintsev** [comment]
Going to close this PR in favor of a new one that has everything merged-up properly.

**Pull request closed without merging**
