### PR TITLE
Merge Swift 3.1 branch into master

### PR DESCRIPTION
**Pull request by swizzlr**
Bring in Swift-3.1 fixes.

### CODE REVIEW

**Comment by swizzlr** [comment]
#843

**Comment by parkera** [comment]
This already has conflicts.

In general what we've been doing is this: putting changes in master, then cherry-picking to swift-3.1-branch. It's the process the other projects are using.

Personally I prefer to target fixes at the branch and merge to master, but that's not the current setup. I think we could revisit that next time we branch for a release.

**Comment by swizzlr** [comment]
Ah - ok. Is this documented anywhere or shall I add to README?

**Comment by parkera** [comment]
Mostly it's just emails to the various dev lists.

**Comment by parkera** [comment]
Let's certainly cherry-pick your fix in #843 to master though.

**Comment by UberJason** [comment]
Hello, did the cherry-pick of #843 into master end up happening? The latest snapshot (02-05) still seems to fail to build CoreFoundation - at least, a Vapor project I'm working with fails to import Foundation with the same errors as those referenced in #843.

**Comment by CodaFi** [comment]
Cherry Pick is happening in #868.

**Pull request closed without merging**
