### PR TITLE
build: migrate swift to CMake 3.15.1

### PR DESCRIPTION
**Pull request by compnerd**
This migrates Foundation to CMake 3.15.1 and uses the new export targets from
libdispatch to enable simpler builds with better dependency tracking.

### CODE REVIEW

**Comment by compnerd** [comment]
Please test with following PR:
apple/swift-corelibs-libdispatch#525

@swift-ci please test

**Comment by compnerd** [comment]
Please test with following PR:
apple/swift-corelibs-libdispatch#525
apple/swift#27434

@swift-ci please test

**Comment by compnerd** [comment]
Please test with following PR:
apple/swift-corelibs-libdispatch#525
apple/swift#27438

@swift-ci please test

**Comment by compnerd** [comment]
Please test with following PR:
apple/swift-corelibs-libdispatch#525
apple/swift#27438

@swift-ci please test

**Comment by compnerd** [comment]
Please test with following PR:
apple/swift-corelibs-libdispatch#525
apple/swift#27438

@swift-ci please test

**Comment by compnerd** [comment]
Please test with following PR:
apple/swift-corelibs-libdispatch#530
apple/swift#27438

@swift-ci please test

**Comment by compnerd** [comment]
Please test with following PR:
apple/swift-corelibs-libdispatch#530
apple/swift#27438
apple/swift-llbuild#568

@swift-ci please test

**Comment by compnerd** [comment]
Please test with following PR:
apple/swift#27438
apple/swift-llbuild#568
apple/swift-package-manager#2359

@swift-ci please test

**Comment by compnerd** [comment]
Please test with following PR:
apple/swift-package-manager#2359

@swift-ci please test

**Comment by compnerd** [comment]
Please test with following PR:
apple/swift-package-manager#2359

@swift-ci please test

**Comment by compnerd** [comment]
Please test with following PR:
apple/swift-package-manager#2359
apple/swift#27657

@swift-ci please test Linux platform

**Comment by spevans** [comment]
Please test with following PR:
apple/swift-package-manager#2359
apple/swift#27657

@swift-ci please test Linux platform

**Comment by spevans** [comment]
Please test with following PR:
apple/swift#27657

@swift-ci please test Linux platform

**Comment by compnerd** [comment]
Please test with following PR:
apple/swift#27657

@swift-ci please test Linux platform

**Comment by compnerd** [comment]
Please test with following PR:
apple/swift#27853

@swift-ci please test Linux platform

**Comment by norio-nomura** [comment]
FYI, building toolchain package using this PR fails with following error:
```terminal.sh-session
CMake Error at Tools/plutil/cmake_install.cmake:41 (file):
  file INSTALL cannot find
  "/Users/norio/github/swift-dev/swift-corelibs-foundation/Tools/plutil/plutil".
Call Stack (most recent call first):
  Tools/cmake_install.cmake:42 (include)
  cmake_install.cmake:52 (include)


FAILED: CMakeFiles/install.util 
cd /Users/norio/github/swift-dev/build/buildbot_linux/foundation-linux-x86_64 && /Users/norio/github/swift-dev/build/cmake-linux-x86_64/bin/cmake -P cmake_install.cmake
ninja: build stopped: subcommand failed.
swift/utils/build-script: fatal error: command terminated with a non-zero exit status 1, aborting
swift/utils/build-script: fatal error: command terminated with a non-zero exit status 1, aborting
```
I guess that is not reproduced with the test triggered by https://github.com/apple/swift-corelibs-foundation/pull/2524#issuecomment-545632559

**Comment by compnerd** [comment]
Ugh, seems that `PROGRAMS` uses the `FILES` path, not the `TARGETS` path, which is probably why it fails.  Should be trivial to fix... changing `PROGRAMS` to `TARGETS`.

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by spevans** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by norio-nomura** [comment]
building toolchain package with updated commit fails with following error:
```terminal.sh-session
CMake Error at cmake_install.cmake:93 (file):
  file INSTALL cannot find
  "/Users/norio/github/swift-dev/build/buildbot_linux/foundation-linux-x86_64/plutil".


FAILED: CMakeFiles/install.util 
cd /Users/norio/github/swift-dev/build/buildbot_linux/foundation-linux-x86_64 && /Users/norio/github/swift-dev/build/cmake-linux-x86_64/bin/cmake -P cmake_install.cmake
ninja: build stopped: subcommand failed.
swift/utils/build-script: fatal error: command terminated with a non-zero exit status 1, aborting
swift/utils/build-script: fatal error: command terminated with a non-zero exit status 1, aborting
```
`plutil` seems to be created at `/Users/norio/github/swift-dev/build/buildbot_linux/foundation-linux-x86_64/Tools/plutil/plutil`.

**Comment by compnerd** [comment]
That is the correct location; I wonder why its looking for `plutil` in the wrong location.  Did you do a clean build @norio-nomura?

**Comment by norio-nomura** [comment]
> Did you do a clean build @norio-nomura?

No.
I'll try again with removing `foundation-linux-x86_64`.

**Comment by norio-nomura** [comment]
> I'll try again with removing `foundation-linux-x86_64`.

I got same result.
regenerated `build/buildbot_linux/foundation-linux-x86_64/cmake_install.cmake` has entry:
```cmake
file(INSTALL DESTINATION "/usr/bin" TYPE PROGRAM FILES "/Users/norio/github/swift-dev/build/buildbot_linux/foundation-linux-x86_64/plutil")
```
but, `plutil` is placed at:

`…/build/buildbot_linux/foundation-linux-x86_64/Tools/plutil/plutil`

instead of 

`…/build/buildbot_linux/foundation-linux-x86_64/plutil`

that `cmake_install.cmake` expects.

**Comment by compnerd** [comment]
Something seems cached there, this is what is getting generated for me:

```
if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE EXECUTABLE FILES "S:/b/foundation/Tools/plutil/plutil.exe")
  if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/bin/plutil.exe" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/bin/plutil.exe")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "S:/b/toolchain/bin/strip.exe" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/bin/plutil.exe")
    endif()
  endif()
endif()
```

**Comment by norio-nomura** [comment]
I tried again with removing `buildbot_linux` directory, but got same result.

Your code in https://github.com/apple/swift-corelibs-foundation/pull/2524#issuecomment-546444965 seems to be generated at
`build/buildbot_linux/foundation-linux-x86_64/Tools/plutil/cmake_install.cmake`

But the packaging error is caused at
`build/buildbot_linux/foundation-linux-x86_64/cmake_install.cmake:93`.
following is `build/buildbot_linux/foundation-linux-x86_64/cmake_install.cmake:84-94`:
```cmake
if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  list(APPEND CMAKE_ABSOLUTE_DESTINATION_FILES
   "/usr/bin/plutil")
  if(CMAKE_WARN_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(WARNING "ABSOLUTE path INSTALL DESTINATION : ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
  if(CMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION)
    message(FATAL_ERROR "ABSOLUTE path INSTALL DESTINATION forbidden (by caller): ${CMAKE_ABSOLUTE_DESTINATION_FILES}")
  endif()
file(INSTALL DESTINATION "/usr/bin" TYPE PROGRAM FILES "/Users/norio/github/swift-dev/build/buildbot_linux/foundation-linux-x86_64/plutil")
endif()
```
Maybe it needs additional changes like following:
```patch
diff --git a/CMakeLists.txt b/CMakeLists.txt
index cc2afed71b90c01bc6eeaca481e116bc86c78f38..ecc6c3c9e30c51e70c1c7ed2f2bd074befd824e3 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -85,7 +85,3 @@ install(FILES
           CoreFoundation/Parsing.subproj/module.map
         DESTINATION
           lib/swift/CFXMLInterface)
-install(PROGRAMS
-          ${CMAKE_CURRENT_BINARY_DIR}/plutil${CMAKE_EXECUTABLE_SUFFIX}
-        DESTINATION
-          ${CMAKE_INSTALL_FULL_BINDIR})
```

**Comment by compnerd** [comment]
@norio-nomura nice catch, that slipped through because I didn't notice it, thinking that only the CF headers were being installed

**Comment by norio-nomura** [comment]
building toolchain package with updated commit fails with following error:
```terminal.sh-session
+ /Users/norio/github/swift-dev/indexstore-db/Utilities/build-script-helper.py build --verbose --package-path /Users/norio/github/swift-dev/indexstore-db --build-path /Users/norio/github/swift-dev/build/buildbot_linux/indexstoredb-linux-x86_64 --configuration release --toolchain /Users/norio/github/swift-dev/build/swift-nightly-install --ninja-bin /Users/norio/github/swift-dev/build/buildbot_linux/ninja-build/ninja
/Users/norio/github/swift-dev/build/swift-nightly-install/usr/bin/swift build --package-path /Users/norio/github/swift-dev/indexstore-db --build-path /Users/norio/github/swift-dev/build/buildbot_linux/indexstoredb-linux-x86_64 --configuration release --verbose -Xcxx -I -Xcxx /Users/norio/github/swift-dev/build/swift-nightly-install/usr/lib/swift -Xcxx -I -Xcxx /Users/norio/github/swift-dev/build/swift-nightly-install/usr/lib/swift/Block
lsb_release -r
/Users/norio/github/swift-dev/build/swift-nightly-install/usr/bin/swiftc --driver-mode=swift -L /Users/norio/github/swift-dev/build/swift-nightly-install/usr/lib/swift/pm/4_2 -lPackageDescription -swift-version 4.2 -I /Users/norio/github/swift-dev/build/swift-nightly-install/usr/lib/swift/pm/4_2 -sdk / -package-description-version 4.2 /Users/norio/github/swift-dev/indexstore-db/Package.swift -fileno 7
/Users/norio/github/swift-dev/indexstore-db: error: manifest parse error(s):
/Users/norio/github/swift-dev/indexstore-db/Package.swift:3:8: error: missing required module 'Foundation'
import PackageDescription
       ^
Traceback (most recent call last):
  File "/Users/norio/github/swift-dev/indexstore-db/Utilities/build-script-helper.py", line 94, in <module>
    main()
  File "/Users/norio/github/swift-dev/indexstore-db/Utilities/build-script-helper.py", line 83, in main
    swiftpm('build', swift_exec, swiftpm_args, env)
  File "/Users/norio/github/swift-dev/indexstore-db/Utilities/build-script-helper.py", line 15, in swiftpm
    subprocess.check_call(cmd, env=env)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/norio/github/swift-dev/build/swift-nightly-install/usr/bin/swift', 'build', '--package-path', '/Users/norio/github/swift-dev/indexstore-db', '--build-path', '/Users/norio/github/swift-dev/build/buildbot_linux/indexstoredb-linux-x86_64', '--configuration', 'release', '--verbose', '-Xcxx', '-I', '-Xcxx', '/Users/norio/github/swift-dev/build/swift-nightly-install/usr/lib/swift', '-Xcxx', '-I', '-Xcxx', '/Users/norio/github/swift-dev/build/swift-nightly-install/usr/lib/swift/Block']' returned non-zero exit status 1
swift/utils/build-script: fatal error: command terminated with a non-zero exit status 1, aborting
swift/utils/build-script: fatal error: command terminated with a non-zero exit status 1, aborting
```
It seems to fail while building `indexstore-db` with packaging toolchain at `build/swift-nightly-install`.
It looks that this PR changes locations where Foundation related files are installed.
```terminal.sh-session
$ docker-swiftnightly-run find /usr/lib/ -name "*Foundation*"|sort>nightly20191024.txt
$ (cd build/swift-nightly-install; find . -name "*Foundation*"|sed "s/^\.//"|sort)>pr-2524.txt
$ diff -u nightly20191024.txt pr-2524.txt
--- nightly20191024.txt	2019-10-27 09:03:51.000000000 +0900
+++ pr-2524.txt	2019-10-27 09:03:57.000000000 +0900
@@ -7,17 +7,17 @@
 /usr/lib/swift/CoreFoundation/CoreFoundation.h
 /usr/lib/swift/CoreFoundation/ForFoundationOnly.h
 /usr/lib/swift/CoreFoundation/ForSwiftFoundationOnly.h
-/usr/lib/swift/linux/libFoundation.so
-/usr/lib/swift/linux/libFoundationNetworking.so
-/usr/lib/swift/linux/libFoundationXML.so
-/usr/lib/swift/linux/x86_64/Foundation.swiftdoc
-/usr/lib/swift/linux/x86_64/Foundation.swiftmodule
-/usr/lib/swift/linux/x86_64/FoundationNetworking.swiftdoc
-/usr/lib/swift/linux/x86_64/FoundationNetworking.swiftmodule
-/usr/lib/swift/linux/x86_64/FoundationXML.swiftdoc
-/usr/lib/swift/linux/x86_64/FoundationXML.swiftmodule
 /usr/lib/swift/shims/CoreFoundationOverlayShims.h
 /usr/lib/swift/shims/CoreFoundationShims.h
 /usr/lib/swift/shims/FoundationOverlayShims.h
 /usr/lib/swift/shims/FoundationShimSupport.h
 /usr/lib/swift/shims/FoundationShims.h
+/usr/lib/x86_64-linux-gnu/libFoundation.so
+/usr/lib/x86_64-linux-gnu/libFoundationNetworking.so
+/usr/lib/x86_64-linux-gnu/libFoundationXML.so
+/usr/lib/x86_64-linux-gnu/swift/linux/x86_64/Foundation.swiftdoc
+/usr/lib/x86_64-linux-gnu/swift/linux/x86_64/Foundation.swiftmodule
+/usr/lib/x86_64-linux-gnu/swift/linux/x86_64/FoundationNetworking.swiftdoc
+/usr/lib/x86_64-linux-gnu/swift/linux/x86_64/FoundationNetworking.swiftmodule
+/usr/lib/x86_64-linux-gnu/swift/linux/x86_64/FoundationXML.swiftdoc
+/usr/lib/x86_64-linux-gnu/swift/linux/x86_64/FoundationXML.swiftmodule
```

**Comment by compnerd** [comment]
The previous install path was wrong, but, I suppose that going for parity for now is okay; we can cross the location bridge later.  I'll adjust the install path in a bit.

**Comment by compnerd** [comment]
It seems that `CMAKE_INSTALL_LIBDIR` is different now?  Is it being specified explicitly?  It should be `lib` by default. which would give the same path as previously.

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please clean test

**Comment by compnerd** [comment]
@swift-ci please clean test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by compnerd** [comment]
Please test with following PR:
apple/swift-corelibs-xctest#287

@swift-ci please test Linux platform

**Comment by shahmishal** [comment]
Please test with following PR:
apple/swift-corelibs-xctest#287

@swift-ci please test Linux platform

**Comment by compnerd** [comment]
Please test with following PR:
apple/swift-corelibs-xctest#287

@swift-ci please test Linux platform

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Pull request merged**
