### PR TITLE
[NSGeometry] Use CGFloat.NativeType instead of hardcoded Double

### PR DESCRIPTION
**Pull request by rintaro**
`CGFloat.NativeType` is `Float` on 32bit platforms.

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci please test

**Comment by rintaro** [comment]
@swift-ci please test

**Comment by rintaro** [comment]
@swift-ci please test

**Comment by parkera** [comment]
We are having a related discussion about this in #622. Should some of the changes to CGFloat there be in this PR instead?

**Comment by parkera** [comment]
Also #628

**Comment by xwu** [comment]
IMO, this PR has standalone value as it fixes issues on 32-bit platforms independent of the Android-related issues. The remaining CGFloat issues may have to do with build configuration tweaking specific to Android.

**Comment by johnno1962** [comment]
This version compiles fine for Android. I’ll close my PR and revert CGFloat.swift and merge this file.

**Pull request merged**
