### PR TITLE
Revert "revert string comparison changes"

### PR DESCRIPTION
**Pull request by lancep**
This reverts commit e51fb9b10a79ecf319a736ca95d1643dea175dc1.

### CODE REVIEW

**Comment by lancep** [comment]
Please test with following pull request:
https://github.com/apple/swift/pull/14694

@swift-ci please test

**Comment by lancep** [comment]
Please test with following pull request:
apple/swift#14694

@swift-ci please test

**Comment by lancep** [comment]
Please test with following pull request:
apple/swift#14694

@swift-ci please test

**Comment by lancep** [comment]
Please test with following pull request:
apple/swift#14694

@swift-ci please test

**Comment by lancep** [comment]
Please test with following pull request:
apple/swift#14694

@swift-ci please test

**Comment by lancep** [comment]
Please test with following pull request:
apple/swift#14694

@swift-ci please test

**Comment by lancep** [comment]
Please test with following pull request:
apple/swift#14694

@swift-ci please test

**Comment by lancep** [comment]
Please test with following pull request:
apple/swift#14694

@swift-ci please test

**Comment by lancep** [comment]
Please test with following pull request:
apple/swift#14694

@swift-ci please test

**Comment by milseman** [comment]
@lancep is this the one that needs to merge to fix testing on Linux? If so, ask @shahmishal or someone with merge access

**Comment by lancep** [comment]
@swift-ci please test

**Comment by shahmishal** [comment]
Discussed offline with @lancep, we will wait until current build completes before merging the PR.

**Comment by shahmishal** [comment]
Merged to unblock CI

**Pull request merged**
