### PR TITLE
TestFoundation: port TestURL to FileManager

### PR DESCRIPTION
**Pull request by compnerd**
Update TestURL to use FileManager for the file system work rather than
dropping down to the C/POSIX interfaces which are not universally
available.

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @millenomi @spevans

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by spevans** [comment]
LGTM

**Comment by millenomi** [comment]
@swift please test and merge

**Comment by compnerd** [comment]
@swift-ci please test and merge

**Comment by compnerd** [comment]
@swift-ci please test and merge

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by spevans** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by compnerd** [comment]
@swift-ci please test

**Pull request merged**
