### PR TITLE
Make Foundation compile in Xcode again

### PR DESCRIPTION
**Pull request by spevans**
- The code is still using version 3 syntax so pass the
  -swift-version 3 flag

### CODE REVIEW

**Comment by spevans** [comment]
@phausler This allowed foundation to compile in Xcode with latest toolchain

**Comment by ianpartridge** [comment]
It seems like we're not too far away from being Swift 4 compliant, so maybe hold off on this?

**Comment by parkera** [comment]
@swift-ci test and merge

**Comment by parkera** [comment]
Actually let's just merge this since it's Mac only.

**Pull request merged**
