### PR TITLE
SR-7195: JSONSerialization encodes Double differently on Darwin and Linux

### PR DESCRIPTION
**Pull request by spevans**
- Use .description property of numbers to encode as String
  instead of using CFNumberFormatter for Float/Double,
  and serialising integers explictly.

### CODE REVIEW

**Comment by spevans** [comment]
@swift-ci please test

**Comment by itaiferber** [comment]
Looks reasonable — can we add a unit test to cover the specific values mentioned in SR-7195 so we can ensure that this at least helps with the round-tripping?

**Comment by spevans** [comment]
@swift-ci test

**Comment by spevans** [comment]
@swift-ci test and merge

**Comment by spevans** [comment]
@swift-ci test and merge

**Pull request merged**
