### PR TITLE
Revert "Add support and tests for URLComponents.percentEncodedQueryItems"

### PR DESCRIPTION
**Pull request by shahmishal**
Reverts apple/swift-corelibs-foundation#2940

We are seeing following failures on Linux bots:

The following tests FAILED:
	1370 - TestFoundation.TestURLComponents-test_queryItems (ILLEGAL)
	1376 - TestFoundation.TestURLComponents-test_createURLWithComponents (ILLEGAL)
	1379 - TestFoundation.TestURLComponents-test_percentEncodedQueryItems (ILLEGAL)

https://ci.swift.org/job/oss-swift-package-linux-ubuntu-16_04/5723/console
https://ci.swift.org/job/oss-swift-package-amazon-linux-2/953/console
https://ci.swift.org/job/oss-swift-package-centos-7/403/console
https://ci.swift.org/job/oss-swift-package-linux-ubuntu-18_04/3533/console
https://ci.swift.org/job/oss-swift-package-ubuntu-20_04/718/console

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by rauhul** [comment]
What in the world... is it possible to get a backtrace from these failures?

**Review by rauhul — APPROVED** [review]
@spevans any new ideas on why this is failing 😓

**Comment by shahmishal** [comment]
> What in the world... is it possible to get a backtrace from these failures?

Do you know where the backtrace is saved? I can try to find it on the server.

**Comment by shahmishal** [comment]
@swift-ci test Linux

**Comment by shahmishal** [comment]
```
18:05:01 Failed Tests (3):
18:05:01   swift-package-tests :: swift-build.txt
18:05:01   swift-package-tests :: swift-package-with-spaces.txt
18:05:01   swift-package-tests :: test-foundation-package/test-foundation-xml.txt
```
These failure does not look related to the changes, may be the foundation test is. 

```
18:04:55 ******************** TEST 'swift-package-tests :: test-foundation-package/test-foundation-xml.txt' FAILED ********************
18:04:55 Script:
18:04:55 --
18:04:55 : 'RUN: at line 2';   rm -rf /home/buildnode/jenkins/workspace/swift-corelibs-foundation-PR-Linux/buildbot_linux/none-swift_package_sandbox_linux-x86_64/tests/test-foundation-package/Output/test-foundation-xml.txt.tmp
18:04:55 : 'RUN: at line 3';   mkdir -p /home/buildnode/jenkins/workspace/swift-corelibs-foundation-PR-Linux/buildbot_linux/none-swift_package_sandbox_linux-x86_64/tests/test-foundation-package/Output/test-foundation-xml.txt.tmp
18:04:55 : 'RUN: at line 4';   /home/buildnode/jenkins/workspace/swift-corelibs-foundation-PR-Linux/buildbot_linux/none-swift_package_sandbox_linux-x86_64/usr/bin/swiftc  -o /home/buildnode/jenkins/workspace/swift-corelibs-foundation-PR-Linux/buildbot_linux/none-swift_package_sandbox_linux-x86_64/tests/test-foundation-package/Output/test-foundation-xml.txt.tmp/test-foundation-xml /home/buildnode/jenkins/workspace/swift-corelibs-foundation-PR-Linux/swift-integration-tests/test-foundation-package/test-foundation-xml.swift
18:04:55 : 'RUN: at line 5';   /home/buildnode/jenkins/workspace/swift-corelibs-foundation-PR-Linux/buildbot_linux/none-swift_package_sandbox_linux-x86_64/tests/test-foundation-package/Output/test-foundation-xml.txt.tmp/test-foundation-xml | /home/buildnode/jenkins/workspace/swift-corelibs-foundation-PR-Linux/buildbot_linux/llvm-linux-x86_64/bin/FileCheck /home/buildnode/jenkins/workspace/swift-corelibs-foundation-PR-Linux/swift-integration-tests/test-foundation-package/test-foundation-xml.txt
18:04:55 --
18:04:55 Exit Code: 1
18:04:55 
18:04:55 Command Output (stdout):
18:04:55 --
18:04:55 $ ":" "RUN: at line 2"
18:04:55 $ "rm" "-rf" "/home/buildnode/jenkins/workspace/swift-corelibs-foundation-PR-Linux/buildbot_linux/none-swift_package_sandbox_linux-x86_64/tests/test-foundation-package/Output/test-foundation-xml.txt.tmp"
18:04:55 $ ":" "RUN: at line 3"
18:04:55 $ "mkdir" "-p" "/home/buildnode/jenkins/workspace/swift-corelibs-foundation-PR-Linux/buildbot_linux/none-swift_package_sandbox_linux-x86_64/tests/test-foundation-package/Output/test-foundation-xml.txt.tmp"
18:04:55 $ ":" "RUN: at line 4"
18:04:55 $ "/home/buildnode/jenkins/workspace/swift-corelibs-foundation-PR-Linux/buildbot_linux/none-swift_package_sandbox_linux-x86_64/usr/bin/swiftc" "-o" "/home/buildnode/jenkins/workspace/swift-corelibs-foundation-PR-Linux/buildbot_linux/none-swift_package_sandbox_linux-x86_64/tests/test-foundation-package/Output/test-foundation-xml.txt.tmp/test-foundation-xml" "/home/buildnode/jenkins/workspace/swift-corelibs-foundation-PR-Linux/swift-integration-tests/test-foundation-package/test-foundation-xml.swift"
18:04:55 # command stderr:
18:04:55 <unknown>:0: error: module file '/home/buildnode/.cache/clang/ModuleCache/2YQE78DQEDMHK/CoreFoundation-5XW88J8P5C88.pcm' is out of date and needs to be rebuilt: signature mismatch
18:04:55 <unknown>:0: note: imported by module 'CFXMLInterface' in '/home/buildnode/.cache/clang/ModuleCache/2YQE78DQEDMHK/CFXMLInterface-33KQ6TD0RL6QE.pcm'
18:04:55 
/home/buildnode/jenkins/workspace/swift-corelibs-foundation-PR-Linux/swift-integration-tests/test-foundation-package/test-foundation-xml.swift:2:8: error: missing required modules: 'CFXMLInterface', 'CoreFoundation'
18:04:55 import FoundationXML
18:04:55        ^
18:04:55 
18:04:55 error: command failed with exit status: 1
18:04:55 
18:04:55 --
```

**Comment by shahmishal** [comment]
Going to merge this PR to unblock CI, and we can look into the swift integration test failures after.

**Comment by buttaface** [comment]
I can confirm that those same three tests failed for me on Android.

**Pull request merged**
