### PR TITLE
[Bundle] Implement `unload()`

### PR DESCRIPTION
**Pull request by ikesyo**

### CODE REVIEW

**Comment by ikesyo** [comment]
@swift-ci please test

**Comment by parkera** [comment]
I'm not sure bundle unloading will ever work for Swift. The runtime folks tell us it's basically unsupported (cc @gparker42).

**Comment by ianpartridge** [comment]
@ikesyo @parkera should we just close this PR?

**Comment by parkera** [comment]
Yes, that's fine with me.

**Pull request closed without merging**
