### PR TITLE
Changed NSDate, NSTimeZone, NSDateFormatter API to match Darwin version

### PR DESCRIPTION
**Pull request by rfdickerson**
This change is [Reviewable](https://reviewable.io/reviews/apple/swift-corelibs-foundation/325)

### CODE REVIEW

**Comment by parkera** [comment]
@swift-ci please test

**Comment by rfdickerson** [comment]
Ok, fixing test cases.

**Comment by rfdickerson** [comment]
@swift-ci please test

**Comment by parkera** [comment]
@swift-ci please test

**Pull request merged**
