### PR TITLE
SR-10596: Prevent Float being deserialized into an Int

### PR DESCRIPTION
**Pull request by hungtruong**
Check for the NSNumber's underlying value and throw an error if it is a floating point number when deserializing from JSON into an Int.
https://bugs.swift.org/browse/SR-10596

### CODE REVIEW

**Comment by spevans** [comment]
@swift-ci test

**Comment by brentdax** [comment]
@swift-ci test

**Comment by parkera** [comment]
I recall some discussion around intentionally allowing this.

**Comment by hungtruong** [comment]
@itaiferber yeah I think that makes sense if JSON itself doesn't have a concept of the difference between `1` and `1.0`. I do agree with the original reporter of the bug that the current inconsistency could also cause issues but I suppose it's not enough of a reason to change the status quo. Thanks for commenting!

**Pull request closed without merging**
