### PR TITLE
[SR-2151]NSJSONSerialization.data produces illegal JSON code #2

### PR DESCRIPTION
**Pull request by DaveLiu888**
Old PR https://github.com/apple/swift-corelibs-foundation/pull/540 reverted due to build break after merge. 
Was asked to refile against master

- [ ] @parkera 
- [ ] @phausler

### CODE REVIEW

**Comment by DaveLiu888** [comment]
@swift-ci please test linux

**Comment by parkera** [comment]
@swift-ci please test linux

**Comment by DaveLiu888** [comment]
@parkera thanks, thought i'd give swift-ci a try, figured Jenkins git hook was whitelisted.
The tests are good tho 🎉

**Comment by DaveLiu888** [comment]
thanks  @parkera

**Pull request merged**
