### PR TITLE
[gardening] Prefer `isEmpty` over `count` check

### PR DESCRIPTION
**Pull request by ikesyo**
Refs: https://github.com/apple/swift/pull/15335, https://github.com/apple/swift/pull/15326

### CODE REVIEW

**Comment by ikesyo** [comment]
@swift-ci Please test

**Comment by ikesyo** [comment]
@swift-ci Please test

**Comment by ikesyo** [comment]
@swift-ci Please test

**Comment by ikesyo** [comment]
@swift-ci Please test

**Comment by alblue** [comment]
LGTM

**Pull request merged**
