### PR TITLE
Add Conformance of 'DateInterval' to protocol 'Decodable'

### PR DESCRIPTION
**Pull request by damuellen**
Add Conformance of 'DateInterval' to protocol 'Decodable'  to match Darwin.

### CODE REVIEW

**Comment by millenomi** [comment]
Can you add tests?

Good catch — I need to figure out a good way to API diff to finish catching these cases.

**Comment by millenomi** [comment]
Actually. I would like to write those tests, I think (I want to extend fixtures to add Codable support).

**Comment by millenomi** [comment]
@swift-ci please test Linux

**Comment by xwu** [comment]
Hmm, in the Swift overlay, the `Codable` conformance is synthesized. Why does this diverge from that?

**Pull request merged**
