### PR TITLE
DRY `|| value is Float || value is Float ||`

### PR DESCRIPTION
**Pull request by Dante-Broggi**

### CODE REVIEW

**Comment by ianpartridge** [comment]
LGTM. @millenomi has been working in this area so should review and merge.

**Comment by millenomi** [comment]
Good catch. LGTM, but please reword the commit message.

**Comment by ianpartridge** [comment]
@swift-ci please test

**Comment by millenomi** [comment]
@swift-ci please test

**Comment by alblue** [comment]
Closing, as this has gone stale. If reopening, please squash all commits to a single one (with a sufficient message) and rebase on top of master.

**Pull request closed without merging**
