### PR TITLE
Make `totalDownloaded` to be specific to HTTPURLProtocol

### PR DESCRIPTION
**Pull request by nethraravindran**

### CODE REVIEW

**Comment by alblue** [comment]
Why should this be specific to an HTTPURLDownloadTask? Other URL download types could potentially have a total download as well.

**Comment by pushkarnk** [comment]
@swift-ci please test

**Comment by nethraravindran** [comment]
@alblue  `totalDownloaded` is being used to track the progress of HTTP downloads. Other protocols may use their own mechanism to track downloads. Hence it makes more sense to make `totalDownloaded` specific to HTTPURLProtocol for now.

**Comment by pushkarnk** [comment]
Looks good to me, for now. I also agree that, in future, we are going to have some common attributes between the different protocols and we have to figure out the best way to factor them out so that there is no redundancies - whether URLSessionTask is the best place to hold these attributes or we need a generic protocol class is something we'd need to look into.

**Comment by pushkarnk** [comment]
@swift-ci please test and merge

**Comment by pushkarnk** [comment]
@swift-ci please test and merge

**Pull request merged**
