### PR TITLE
Drop NS prefix from some files to match the class names

### PR DESCRIPTION
**Pull request by ikesyo**

### CODE REVIEW

**Comment by ikesyo** [comment]
@swift-ci Please test

**Comment by ianpartridge** [comment]
Could we make this change in `swift-3.1-branch` too? It will make porting and cherry-picking changes between the branches in future easier.

**Comment by parkera** [comment]
Sure

**Comment by ianpartridge** [comment]
@ikesyo are you willing to cherry-pick this for `swift-3.1-branch`?

**Pull request merged**
