### PR TITLE
Remove additional/redundant case let as Date.

### PR DESCRIPTION
**Pull request by justinmcp**
Case accidentally included twice, remove a copy.

### CODE REVIEW

**Comment by YOCKOW** [comment]
@swift-ci Please test

**Comment by justinmcp** [comment]
That's a mighty log file. Error seems unrelated though.

```
/home/buildnode/jenkins/workspace/swift-corelibs-foundation-PR-Linux/swift-docc/Tests/SwiftDocCTests/Indexing/NavigatorIndexTests.swift:250: error: NavigatorIndexingTests.testNavigationTreeLargeDumpAndReadAsync : Asynchronous wait failed - Exceeded timeout of 10.0 seconds, with unfulfilled expectations: Load the tree asynchronously.
```

**Comment by justinmcp** [comment]
FYII, tat test reads from a custom binary format, naught to do with JSON. Timing in tests is notoriously difficult, running again is probably the quickest option.

**Comment by YOCKOW** [comment]
@swift-ci Please test Linux platform

**Comment by YOCKOW** [comment]
@swift-ci Please test Linux platform

**Comment by justinmcp** [comment]
Different error on latest, a compile error;
```
/home/buildnode/jenkins/workspace/swift-corelibs-foundation-PR-Linux/swift/test/SILGen/moveonly_builtin.swift:35:11: error: _move applied to value that the compiler does not support checking
```

Unrelated again. 

Pure curiosity, any docs on the testing methodology?

**Comment by YOCKOW** [comment]
> Pure curiosity, any docs on the testing methodology?

I'm not sure which you mean, but docs are available such as below:
- Debugging The Compiler: https://github.com/apple/swift/blob/main/docs/DebuggingTheCompiler.md
- Continuous Integration for Swift: https://github.com/apple/swift/blob/main/docs/ContinuousIntegration.md
- Testing `swift-corelibs-foundation`: https://github.com/apple/swift-corelibs-foundation/blob/main/Docs/Testing.md

**Comment by YOCKOW** [comment]
@swift-ci Please test Linux platform

**Comment by justinmcp** [comment]
@YOCKOW Thanks for those links.

I'm sure to be biased, I wouldn't be after testing downstream projects like this, for example, so I wanted to read about the testing strategy.

Docs looks comprehensive, I'll have a read later tonight, thanks again.

**Comment by YOCKOW** [comment]
https://github.com/apple/swift-docc/pull/70 should resolve the CI failure. (Thanks to @d-ronnqvist )

**Comment by YOCKOW** [comment]
@swift-ci Please test Linux platform

**Pull request merged**
