### PR TITLE
TEST - DO NOT MERGE

### PR DESCRIPTION
**Pull request by spevans**
Re-enable TestNString.test_completePathIntoString() to see if it works on Windows

### CODE REVIEW

**Comment by spevans** [comment]
@compnerd Could you test this on windows please, I need to know if it ever worked, thanks

**Comment by compnerd** [comment]
CI run: https://dev.azure.com/compnerd/swift-build/_build/results?buildId=24927&view=results

**Comment by compnerd** [comment]
Results: https://dev.azure.com/compnerd/swift-build/_build/results?buildId=25000&view=logs&j=ec47c80d-c7cf-5f2b-7138-13cd268bea3d&t=5cfc8e20-74e6-5b9b-ff2a-9c787c40fff4

**Comment by spevans** [comment]
Just reenabling some other tests to see if they now work.

**Comment by spevans** [comment]
@swift-ci test

**Comment by spevans** [comment]
@swift-ci test

**Comment by spevans** [comment]
@swift-ci test linux

**Comment by spevans** [comment]
@swift-ci test linux

**Comment by spevans** [comment]
@swift-ci test linux

**Comment by spevans** [comment]
@swift-ci test linux

**Comment by spevans** [comment]
@swift-ci test

**Comment by spevans** [comment]
@swift-ci  test linux

**Comment by spevans** [comment]
@swift-ci test linux

**Comment by spevans** [comment]
@swift-ci test linux

**Comment by spevans** [comment]
@swift-ci test linux

**Comment by shahmishal** [comment]
The Swift project moved the default branch to `main` and deleted `master` branch, so GitHub automatically closed the PR. Please re-create pull request with main branch.

More detail about the branch update - https://forums.swift.org/t/updating-branch-names/40412

**Pull request closed without merging**
