### PR TITLE
[gardening] Use `defer` for end-of-scope calls

### PR DESCRIPTION
**Pull request by naithar**

### CODE REVIEW

**Comment by naithar** [comment]
@parkera please review

**Comment by parkera** [comment]
The `free` and `stream.close` are ok, but I'm not a fan of using defer to unlock locks. It is super important to be very aware of exactly where the lock becomes unlocked, and personally I prefer to do that explicitly.

**Comment by naithar** [comment]
Reverted `defer` for `lock()`/`unlock()`.

**Comment by parkera** [comment]
@swift-ci please test

**Comment by naithar** [comment]
The [build job](https://ci.swift.org/job/swift-corelibs-foundation-PR-Linux/678/) finished successfuly

**Comment by parkera** [comment]
@swift-ci please test

**Comment by alblue** [comment]
@parkera these tests finished last week - any objections to merge?

**Comment by parkera** [comment]
@swift-ci please test and merge

**Comment by naithar** [comment]
[Build job](https://ci.swift.org/job/swift-corelibs-foundation-PR-Linux/703) failed with 
``Test Case 'TestURLSession.test_cancelTask' started at 12:20:09.578
/home/buildnode/jenkins/workspace/swift-corelibs-foundation-PR-Linux/swift/utils/build-script-impl: line 262:  3781 Segmentation fault      (core dumped) "$@"``
This doesn't seem to be related

**Comment by alblue** [comment]
@swift-ci please test and merge

**Pull request merged**
