### PR TITLE
Update NSFileHandle public API to match Darwin Foundation.

### PR DESCRIPTION
**Pull request by kareman**
Has been tested on Ubuntu 15.10 and OS X.

### CODE REVIEW

**Comment by kareman** [comment]
I realise this breaks the Swift package manager:

```
/home/name/swift/swiftpm/Sources/Utility/File.swift:54:9: error: value of type 'NSFileHandle' has no member 'writeData'
        handle.writeData(data)
        ^~~~~~ ~~~~~~~~~
/home/name/swift/swiftpm/Sources/Utility/File.swift:65:9: error: value of type 'NSFileHandle' has no member 'writeData'
        handle.writeData(data)
        ^~~~~~ ~~~~~~~~~
```

What is the policy on changes that affect other repositories?

**Comment by ianpartridge** [comment]
Raise a PR against swiftpm too, I think :)

**Comment by kareman** [comment]
Yes I realised the changes needed to swiftpm were very simple so that's what I did.

**Comment by kareman** [comment]
I see this has been implemented in https://github.com/apple/swift-corelibs-foundation/commit/658474c7ade18e8990cff933303ec92db2d6f080 .

**Pull request closed without merging**
