### PR TITLE
copyItem Implementation with Tests.

### PR DESCRIPTION
**Pull request by halfcharged**
Original pull request was #660.  This just adds the tests that were requested.

Don't know if creating a separate pull request was the thing to do here.  Is it possible to modify a pull request if you are not the owner/maintainer??

### CODE REVIEW

**Comment by parkera** [comment]
This is a good starting point, but it does seem inefficient to read the whole file into memory so we can write it out again. A more efficient implementation would read it in chunks. This one uses an arbitrarily large amount of memory...

**Comment by parkera** [comment]
@swift-ci please test

**Comment by amraboelela** [comment]
Instead of creating a new PR, wasn't it possible to push into the same PR of #660 ?

**Comment by parkera** [comment]
Not sure if everyone has permission to do that; in any case this one has your commits in it still.

**Comment by amraboelela** [comment]
Oh, cool, I see now that you guys merged my commits into this pull request. Thanks :)

**Pull request merged**
