### PR TITLE
[WIP] NSHTTPCookie initializer, getters, and tests

### PR DESCRIPTION
**Pull request by tptee**
Most of version 0 cookies are covered in the test cases with version 1 tests on the way. Still some edge cases to iron out, esp. when the dictionary key accepts multiple types.

### CODE REVIEW

**Comment by ChrisChares** [comment]
@tptee that pull request rebases your commits with all the recent updates to upstream/master and adds implementation + tests for NSHTTPCookie.requestHeadersForCookies().  Please take a look and incorporate the changes into this pull request :)

**Comment by ChrisChares** [comment]
@salgernon #34 and this take a different approach to storing cookie properties.  This uses a private cookie struct while #34 passes all requests to the properties dictionary.  Which is preferred?

**Comment by tptee** [comment]
My two cents is that we shouldn't be force casting anywhere. Best to remove all our optionals in the initializer, making the getters trivial to implement.

**Comment by tptee** [comment]
The type signatures of the getters constricts you to non-optional, non-throwing code, so I think the only way to avoid the force casts is check the validity of the entire cookie in the initializer, where you do have the freedom to check optionals, return nil for an invalid cookie, etc

**Comment by ChrisChares** [comment]
I'm for that as well.  It seems better to set properties with all their respective fallback rules at the same time as doing validation.  

The alternative means a simplified `init?()` method with property fallback and casting logic spread amongst all the getters.  Not only does that seem more complicated conceptually, it may also lead to code duplication as it seems you'll have to walk through the property fallbacks in `init?()` to ensure a valid cookie and again in the respective getter.

**Comment by parkera** [comment]
In order to try and get us all on the same page, I've merged #34 and this in.

**Pull request merged**
