### PR TITLE
NotificationCenter should us NSNotification.Name per docs

### PR DESCRIPTION
**Pull request by glenna**
Per [Apple docs](https://developer.apple.com/documentation/foundation/notificationcenter), `addObserver` and `post` use `NSNotification.Name`

### CODE REVIEW

**Comment by ianpartridge** [comment]
According to https://developer.apple.com/documentation/foundation/notificationcenter/1407263-removeobserver it should be `NSNotification.Name`?

**Comment by glenna** [comment]
As does addObserver(...), but in source it’s using `Notification.Name` (not that that makes this PR correct)

https://developer.apple.com/documentation/foundation/notificationcenter/1411723-addobserver

**Comment by ianpartridge** [comment]
It would be great to fix up these incompatibilities. Do you want to do that in this PR? Or should we close it?

**Comment by glenna** [comment]
Just to clarify, you mean to change them both back to `NSNotificaiton.Name` to match the docs?

**Comment by ianpartridge** [comment]
Yes. It looks like `post()` is wrong too.

**Comment by spevans** [comment]
@swift-ci please test

**Comment by glenna** [comment]
@ianpartridge got a bit busy, but it's done now. i'll edit the PR title/description so the merge commit will have a relevant message

**Comment by ianpartridge** [comment]
Thanks!

**Pull request merged**
