### PR TITLE
Unwrap potentially boxed attributes returned by NSAttributedString.attribute

### PR DESCRIPTION
**Pull request by ephemer**
When adding an attribute to a NSMutableAttributedString with `.addAttribute`, the Swift value provided is potentially boxed in a `_SwiftValue` via `_SwiftValue.store(value)`, as seen here: https://github.com/apple/swift-corelibs-foundation/blob/master/Foundation/NSAttributedString.swift#L345

The boxed value is never unboxed again though on retrieval. And given that `_SwiftValue` is a Foundation-internal type, it's impossible for an end-user to ever access the real raw value again (`.attribute(at: index)` always just returns the boxed version).

The current change aims to fix this (see Changed Files in this PR for details) by defensively unboxing any individual attributes returned. `_SwiftValue.fetch(value)` checks whether the value needs unboxing and is thus safe to use on any `AnyObject(?)`.

The only question is whether we should extend this change to multiple attributes (here, probably: https://github.com/apple/swift-corelibs-foundation/blob/master/Foundation/NSAttributedString.swift#L254), or whether there's a more foolproof way about this.

### CODE REVIEW

**Comment by parkera** [comment]
@swift-ci please test

**Comment by parkera** [comment]
You're right that we should not be exposing `_SwiftValue` to callers. We must have this box/unbox pattern elsewhere as well.

Adding your test case to our XCTests seems reasonable.

**Comment by ephemer** [comment]
@parkera thank you for your speedy review. Can you run the tests again? The test that failed last run made little sense to me as written: at the top of the very same test that failed we were trying to cast the attribute's value to `String`, and below we were trying to cast it to `NSString` (which now failed).

As far as I'm aware we're not able to cast String to NSString on Linux as we are on Darwin. So it seems to me the way the test was written was bound to fail, or was relying on broken behaviour. Or have I misunderstood something here? For now I've changed the expectation to be internally consistent (it now always checks for a `String`).

**Comment by spevans** [comment]
@swift-ci please test

**Comment by ephemer** [comment]
@spevans sorry, I got too hasty with that one. I have pushed an update but am not able to test the build locally until tomorrow. It should work so you could try again if you're feeling lucky, otherwise I'll write again tomorrow.

**Comment by spevans** [comment]
@swift-ci please test

**Comment by alblue** [comment]
@swift-ci please test

**Comment by ephemer** [comment]
@spevans I can't build the current master on my machine with Xcode 9.3 - I have a bunch of errors like `Data does not conform to protocol 'Collection'`.

There was a problem with the build yesterday because of a typo. It should work now but I unfortunately don't have time to fix the Foundation build errors to get it working here. Can you try again?

**Comment by spevans** [comment]
If you are building with Xcode, may sure to download the latest nightly snapshot of the toolchain, available at https://swift.org/download/#snapshots.

Also, remember to checkout swift-corelibs-xctest and open `Foundation.xcworkspace` so that it also builds XCTest at the same time.

**Comment by millenomi** [comment]
@swift-ci please test

**Comment by millenomi** [comment]
The fix is minimal, so I commandeered this.

**Comment by millenomi** [comment]
@swift-ci please test

**Comment by millenomi** [comment]
@swift-ci please test

**Comment by millenomi** [comment]
I've slept on this; since `NSString(…) as? String` now works on Linux, I'd rather have returning values be a constant time operation and the downstream casts perform the bridging like on Darwin. I'm closing it, but if this is in error, please ping me.

**Pull request closed without merging**
