### PR TITLE
[android] Replace URL tests that use hardcoded /tmp

### PR DESCRIPTION
**Pull request by buttaface**
In Android /tmp doesn't exist, and the temporary directory is normally
/data/local/tmp. It is not a symlink. The tests were mostly working, but
because `resolvingSymlinksInPath` returns a trailing slash if the
directory actually exists, in Android it was returning without the final
trailing slash in some of the cases.

The changes split the large test into smaller pieces that test one of
the behaviours of `resolvingSymlinksInPath`, and tries not to use the
temporarl directory by itself or suppose anything about it.

There are, however, a couple of tests that check behaviours that are
only applicable to Darwin, so those tests are only performed in Darwin
platforms.

This is simply a rebase of #2145, as [@drodriguez asked me to do](https://github.com/apple/swift-corelibs-foundation/pull/2145#issuecomment-577047292). This pull fixes the last remaining test that fails for me when building Foundation natively on Android.

@spevans, you already substantially reviewed this pull, let me know if there's anything else.

### CODE REVIEW

**Comment by spevans** [comment]
@swift-ci test

**Comment by buttaface** [comment]
Passed all tests, let me know if there's anything else.

**Comment by buttaface** [comment]
Ping, just following up.

**Comment by buttaface** [comment]
Done.

**Comment by spevans** [comment]
@swift-ci test linux

**Comment by spevans** [comment]
@swift-ci test linux

**Comment by spevans** [comment]
@swift-ci test and merge

**Comment by buttaface** [comment]
Maybe you have to approve it on github first?

**Comment by spevans** [comment]
@buttaface There is often issues between GitHub and the Swift CI servers whereby messages from one to the other seem to get lost. Since it passed ok on Linux I have merged it in manually.

**Comment by buttaface** [comment]
Alright, thanks.

**Pull request merged**
