### PR TITLE
Honor CMAKE_INSTALL_BINDIR

### PR DESCRIPTION
**Pull request by tristanlabelle**
CMake install places binary files under the `CMAKE_INSTALL_BINDIR` subdirectory, but some CMake files hardcode `bin` instead (the default value). This change un-hardcodes these. This has no effect by default, but it will allow redirecting the binaries to a different output directory, which will help with packaging installers for multiple architectures in the Windows build.

### CODE REVIEW

**Review by compnerd — APPROVED** [review]
https://github.com/apple/swift-corelibs-foundation/blob/main/CMakeLists.txt#L53 includes `GNUInstallDirs` so we should be fine.

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by tristanlabelle** [comment]
The Linux CI build is still hitting the seemingly unrelated:
```
/home/build-user/swift-tools-support-core/Sources/TSCBasic/ByteString.swift:11:8: error: no such module 'Foundation'
import Foundation
       ^

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by tristanlabelle** [comment]
Ah! It looks like in the linux build, `CMAKE_INSTALL_LIBDIR` expands to `lib/x86_64-linux-gnu`

**Comment by tristanlabelle** [comment]
The latest change scopes down to only replacing `bin` with `CMAKE_INSTALL_BINDIR` and leaving lib alone given the variation of the linux build and that for the Windows installer purposes, we only need to override the bin dir. @compnerd , could you re-kick the CI?

**Pull request merged**
