### PR TITLE
Lower camel case for swift enum cases

### PR DESCRIPTION
**Pull request by kouky**
Swift API design guidelines specify `lowerCamelCase` for everything except the names of types and protocols. The rationale is that cases are values and should follow the same convention as other values.

https://swift.org/documentation/api-design-guidelines/#general-conventions

The following files already have `lowerCamelCase` formatting for enumerations, this PR brings the rest into line
- `NSObjCRuntime.swift`
- `NSFileManager.swift`
- `NSTimeZone.swift`
- `NSURLReques.swift`
- `NSURLResponse.swift`

### CODE REVIEW

**Comment by NaughtyOttsel** [comment]
I have a local branch that does the lowerCamelCase for the NSXMLDocument enums. If this PR isn't merged in before I get home, I will branch from this PR and commit those changes as well. Saves having multiple PR's for accomplishing the same type of task.

**Comment by kouky** [comment]
@NaughtyOttsel sure thing, CI is in a bad state at the moment so it might be a little while until we can check this chnage-set is green.

**Comment by parkera** [comment]
Yah, I'm holding off test runs and merges until the rest gets sorted out.

**Comment by phausler** [comment]
There will be a few conflicts with some of the extra stuff I have been looking at; but I was easily able to reconcile those.

**Comment by kouky** [comment]
@phausler merged master and resolved a trivial conflict

**Comment by phausler** [comment]
@swift-ci Please test

**Comment by kouky** [comment]
@phausler I've fixed the error reported by CI with commit 6d909d7, latest master has also been merged. Can you please rerun swift CI again?

**Comment by kouky** [comment]
Closing this PR, the commit was manually merged into master d5ddaa728640329325220a15c3f2ce359065b6ef 🎉

**Pull request closed without merging**
