### PR TITLE
[Android][Linux] Fixed hang when using RunLoop.main.run with Date()

### PR DESCRIPTION
**Pull request by Molanda**
When using `RunLoop.main.run(mode: .default, before: Date())` on Android, the call would not return.

This function, along with `limitDate` (which also would hang), calls `CFRunLoopRunInMode`.  According to the [documentation](https://developer.apple.com/documentation/corefoundation/1541988-cfrunloopruninmode), this should return immediately if seconds is 0.

I traced the problem to `__CFRunLoopRun` where there are a few platform specific cases for draining the message queue.  In the `TARGET_OS_LINUX` case, the polling condition was not being considered.

This PR fixes the parameter to be `poll ? 0 : TIMEOUT_INFINITY` as is done for the other platforms, which  allows polling to work on Android.

### CODE REVIEW

**Comment by drodriguez** [comment]
@swift-ci please test

**Comment by bendjones** [comment]
Yup same here and agreed about the test...

**Comment by Molanda** [comment]
I'm building for Ubuntu now to test out the test I added.  The result will be pass/hang though.

I did notice that two of the other RunLoop tests are commented out, with a reference to SR-399.  This appears to be an issue on Darwin, so I don't see it as related to this fix.

**Comment by spevans** [comment]
@swift-ci test linux

**Comment by Molanda** [comment]
Is the test status stuck?

[Jenkins](https://ci.swift.org/view/Pull%20Request/job/swift-corelibs-foundation-PR-Linux/3810/) is claiming that it was a success.

**Comment by spevans** [comment]
@Molanda Sometimes the status message from Jenkins -> Github gets lost, i'll start the test again

**Comment by spevans** [comment]
@swift-ci test linux

**Comment by Molanda** [comment]
Thank you!

**Comment by spevans** [comment]
@swift-ci test linux

**Comment by Molanda** [comment]
Has the build job been changed?  

[Build 3810](https://ci.swift.org/job/swift-corelibs-foundation-PR-Linux/3810/consoleFull) completed successfully on 10/27 with all of my changes.  The last step was "Creating installable package".

```
18:41:50 Setting status of dd402ba04bd324c193a8cc607e03a21c964e9980 to SUCCESS with url https://ci.swift.org/job/swift-corelibs-foundation-PR-Linux/3810/ and message: 'Build finished. '
18:41:50 Using context: Swift Test Linux Platform
18:41:50 Setting status of dd402ba04bd324c193a8cc607e03a21c964e9980 to SUCCESS with url https://ci.swift.org/job/swift-corelibs-foundation-PR-Linux/3810/ and message: ' '
18:41:50 Using context: Swift Test Linux Platform
18:41:50 Finished: SUCCESS
```

This step has been replaced in [Build 3825](https://ci.swift.org/job/swift-corelibs-foundation-PR-Linux/3825/consoleFull) with the following...

- Building indexstoredb
- Running tests for indexstoredb
- Finished tests for indexstoredb
- Building sourcekitlsp
- Running tests for sourcekitlsp
- Finished tests for sourcekitlsp
- Installing sourcekitlsp
- Building benchmarks

And "Installing swiftpm" now fails with the following error:

```
21:45:03 IOError: [Errno 2] No such file or directory: '/home/buildnode/jenkins/workspace/swift-corelibs-foundation-PR-Linux/buildbot_linux/benchmarks-linux-x86_64/Benchmark_Onone/debug/SwiftBench'
```

**Comment by drodriguez** [comment]
The Swift Package Manager – Benchmarks build error was fixed this morning, after Simon launched the tests.

@swift-ci test linux

**Comment by Molanda** [comment]
Great, thank you!

**Comment by Molanda** [comment]
What is the next step for this one?

**Comment by drodriguez** [comment]
Sorry for the delays. I just merged. Congrats!

**Pull request merged**
