### PR TITLE
Foundation: support `_getFileSystemRepresentation` on Windows

### PR DESCRIPTION
**Pull request by compnerd**
Update the `_getFileSystemRepresentation` helper to return a UTF-16
Windows style path.  This enables us to properly model the file system
representation of the path and the URL representation of the path.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
Windows CI: https://dev.azure.com/compnerd/swift-build/_build/results?buildId=26158&view=results

**Comment by compnerd** [comment]
Seems that it is hanging on the Facebook donated host.  *sigh* time to make further tweaks

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by spevans** [comment]
@swift-ci test linux

**Comment by compnerd** [comment]
CI on the Facebook machine: https://dev.azure.com/compnerd/swift-build/_build/results?buildId=26171&view=logs&j=231dcdbf-b818-57d0-e791-37f9a41be191&t=c588f5d8-dba7-51ee-e9b7-dd6cf97d2428

**Comment by compnerd** [comment]
new failure count: 56, old failure count: 65

**Comment by compnerd** [comment]
I'm going to merge this for now, its improving the current state, though I will have more fixes to follow on this.

**Pull request merged**
