### PR TITLE
Re-enable ICU tests now that Linux always builds with a newer version

### PR DESCRIPTION
**Pull request by spevans**
Resolves SR-250, SR-7589

### CODE REVIEW

**Comment by spevans** [comment]
Will hold off merging until manual tests on Ubuntu14 have been run

**Comment by spevans** [comment]
@compnerd Is there a way of passing the `--verbose` option to `ctest` so that the full output from `TestFoundation` shows up in the logs?

**Comment by compnerd** [comment]
@spevans - Sorry, I never even thought about doing that since I would just run the target locally and look at the logs.  It would require tweaking build-script-impl to enable this (and you are right, we should).  Really all it boils down to is passing `CTEST_OUTPUT_ON_FAILURE=TRUE` to the test command (e.g. `ninja -C ... test CTEST_OUTPUT_ON_FAILURE=TRUE`).

**Comment by spevans** [comment]
@swift-ci test

**Comment by spevans** [comment]
@swift-ci test

**Comment by spevans** [comment]
Please test with the following request:
https://github.com/apple/swift/pull/20314

@swift-ci test

**Comment by spevans** [comment]
@swift-ci test

**Comment by spevans** [comment]
@swift-ci test

**Comment by spevans** [comment]
@swift-ci test

**Comment by spevans** [comment]
Manually tested ok on Ubuntu14.04

**Comment by millenomi** [comment]
@swift-ci please test

**Comment by spevans** [comment]
@swift-ci test linux

**Comment by spevans** [comment]
@swift-ci test osx

**Comment by spevans** [comment]
@swift-ci test osx

**Comment by spevans** [comment]
@swift-ci test osx

**Comment by spevans** [comment]
@swift-ci test

**Comment by spevans** [comment]
@swift-ci test and merge

**Pull request merged**
