### PR TITLE
Add `@_versioned` attribute to _MutableHandle._pointer

### PR DESCRIPTION
**Pull request by ikesyo**
Found related errors at https://ci.swift.org/view/Pull%20Request/job/swift-corelibs-xctest-PR-osx/154/consoleFull#-824480375ee1a197b-acac-4b17-83cf-a53b95139a76.

This is the same as #772.

/cc @slavapestov

### CODE REVIEW

**Comment by parkera** [comment]
Hm, am I wrong or did we remove the need for Boxing.swift completely from the overlay code?

**Comment by parkera** [comment]
Ok

**Comment by parkera** [comment]
@swift-ci please test and merge

**Comment by briancroom** [comment]
@swift-ci please test and merge

**Comment by briancroom** [comment]
@ikesyo it looks like this change isn't going to work as-is:

```
Foundation/Boxing.swift:17:5: error: '@_versioned' attribute can only be applied to internal declarations, but '_pointer' is fileprivate
    @_versioned fileprivate var _pointer : MutableType
    ^~~~~~~~~~~~
```

**Comment by ikesyo** [comment]
@briancroom Sorry for the trouble. I've just made it `internal`.

**Comment by briancroom** [comment]
@swift-ci please test

**Comment by ikesyo** [comment]
The test has passed https://ci.swift.org/job/swift-corelibs-foundation-PR-Linux/539/

**Comment by parkera** [comment]
@swift-ci please test and merge

**Pull request merged**
