### PR TITLE
Reduce NSError usages (to match the Darwin version)

### PR DESCRIPTION
**Pull request by ikesyo**
- NSKeyedUnarchiver.swift
- NSStream.swift
- NSURLAuthenticationChallenge.swift

### CODE REVIEW

**Comment by parkera** [comment]
@swift-ci please test and merge

**Comment by parkera** [comment]
Should we try this again?

**Comment by ikesyo** [comment]
@parkera Yes, please! 🙏 The failure is unrelated: https://github.com/apple/swift-corelibs-foundation/pull/823#issuecomment-274645107.

**Comment by parkera** [comment]
@swift-ci test and merge

**Pull request merged**
