### PR TITLE
[5.2] Make URLSession and URLSessionTask more source-compatible with Darwin

### PR DESCRIPTION
**Pull request by broadwaylamb**
This is a cherry-pick of #2587 for Swift 5.2.

cc @millenomi @parkera @phausler

### CODE REVIEW

**Comment by broadwaylamb** [comment]
Can anybody verify this patch?

**Comment by broadwaylamb** [comment]
@parkera is there a chance for it still make it into Swift 5.2?

**Comment by drexin** [comment]
@swift-ci test

**Comment by drexin** [comment]
@millenomi If you have a minute, would you mind taking a look at this?

**Comment by millenomi** [comment]
I’d rather not remove API surface in a minor — even incorrect API surface. Can we instead deprecate the setters and have them do nothing?

**Comment by millenomi** [comment]
(Next major we `@availability(unavailable)` them.)

**Comment by spevans** [comment]
This change is in the 5.3 release , so closing this PR.

**Pull request closed without merging**
