### PR TITLE
Implementation of NSURLCredential.copy(with:)

### PR DESCRIPTION
**Pull request by vipinmenon**
This PR has Implementation of NSURLCredential.copy(with:) along with the unit test case.

### CODE REVIEW

**Comment by parkera** [comment]
@swift-ci please test linux

**Comment by vipinmenon** [comment]
The build failure seems to be unrelated to this PR.

**Comment by vipinmenon** [comment]
@parkera : Can you please re-run the tests

**Comment by itaiferber** [comment]
@swift-ci Please test Linux

**Pull request merged**
