### PR TITLE
Uses var (otherwise not used) as parameter to open file in CFFileUtilities

### PR DESCRIPTION
**Pull request by valeriyvan**

### CODE REVIEW

**Comment by spevans** [comment]
@swift-ci please test

**Comment by spevans** [comment]
@swift-ci please test

**Comment by valeriyvan** [comment]
ping

**Comment by valeriyvan** [comment]
ping

**Comment by millenomi** [comment]
cc @niw This is the CF dual of your last patch — should it be 0666?

**Comment by niw** [comment]
Actually, probably get `mode` by `stat(2)` for existing path is unnecessary at least on POSIX system, because `mode` (`oflag`) is used only when it is creating a new file by `O_CREAT`.
Therefore, the original code works as expected (but has unused `mode`,) also this patch works as expected. 

I think it is preferred to not have unused `mode` for sure, so I think this change is reasonable.

**Pull request merged**
