### PR TITLE
Updated NumberFormatter to match expected behavior

### PR DESCRIPTION
**Pull request by ddunn2**
Made some updates to the NumberFormatter class, now the usesSignificantFigures property will only be set if you want to set either minimum or maximum significant figures and will prevent setting numberStyle to .decimal overwriting the values you set for minimum or maximum significant figures. 

I ran the tests and they all passed, I also added a few new tests and made the necessary changes to the old tests to account for this change.

### CODE REVIEW

**Comment by parkera** [comment]
@swift-ci please test and merge

**Comment by ianpartridge** [comment]
TestFoundation/TestNSByteCountFormatter.swift:368: error: TestNSByteCountFormatter.test_isAdaptiveFalseZeroPadsFractionDigitsTrue : XCTAssertEqual failed: ("123 MB") is not equal to ("123.5 MB") -

**Comment by ddunn2** [comment]
Thanks Ian, I imagine it's due to the ByteCountFormatter is currently configured to work with how the NumberFormatter use to be prior to this update, and just needs updating to work this updated version of the NumberFormatter but I'll look into it to confirm and update as needed.

**Comment by ddunn2** [comment]
I've confirmed it's due to how the new NumberFormatter update works, I will update the ByteCountFormatter and add changes to a new commit. I'll also tidy up the ByteCountFormatter as a few bits can be removed with this update to NumberFormatter as well.

**Comment by ddunn2** [comment]
@parkera @swift-ci  Changes have been added, I ran tests on mac and linux and both passed.

**Comment by parkera** [comment]
Cool, let me kick this off again.

**Comment by parkera** [comment]
@swift-ci please test and merge

**Pull request merged**
