### PR TITLE
[NSAffineTransform] NSCoding implementation

### PR DESCRIPTION
**Pull request by naithar**
Implemented `NSCoding` protocol and `isEqual` to match macOS Foundation.

### CODE REVIEW

**Comment by parkera** [comment]
Hm, the darwin one encodes this as a C array of 6 big-endian floats.

**Comment by naithar** [comment]
So should it encode a `UnsafePointer<Double>` or just and array like `[Double]`?

**Comment by parkera** [comment]
`UnsafePointer<Float>` I think.

**Comment by naithar** [comment]
@parkera please review. Not sure it's a right implementation, but i found no other way to encode `UnsafePointer<Float>`.

**Comment by parkera** [comment]
Sure, let's give this a shot.

**Comment by parkera** [comment]
@swift-ci please test and merge

**Comment by parkera** [comment]
```
TestFoundation/TestNSAffineTransform.swift:361: error: TestNSAffineTransform.test_NSCoding : XCTAssertEqual failed: ("<NSAffineTransform: 0x0000000001c704b0>") is not equal to ("<NSAffineTransform: 0x0000000001c7e9c0>") - Archived then unarchived `NSAffineTransform` must be equal.
Test Case 'TestNSAffineTransform.test_NSCoding' failed (0.004 seconds)
```

**Comment by naithar** [comment]
@parkera please review.

**Comment by parkera** [comment]
@swift-ci please test

**Comment by naithar** [comment]
@parkera if i understand correctly [this test job (617)](https://ci.swift.org/view/All/job/swift-corelibs-foundation-PR-Linux/617/) performed without errors.

**Comment by parkera** [comment]
Great!

**Comment by parkera** [comment]
@swift-ci test and merge

**Pull request merged**
