### PR TITLE
Adapt for the mangling prefix change ($S -> $s)

### PR DESCRIPTION
**Pull request by eeckstein**

### CODE REVIEW

**Comment by eeckstein** [comment]
Please test with following pull request:
https://github.com/apple/swift/pull/19388

@swift-ci smoke test Linux platform

**Comment by eeckstein** [comment]
Please test with following pull request:
https://github.com/apple/swift/pull/19388

@swift-ci test Linux platform

**Comment by parkera** [comment]
Can you test this manually on macOS to make sure we don't break our developers there? The CI doesn't do it.

**Comment by parkera** [comment]
Last time this mangling changed it really messed us up for a while since everyone had to have ToT tools installed.

**Comment by eeckstein** [comment]
@parkera What test should I run?

**Comment by parkera** [comment]
You can run all the unit tests (I hope) on macOS using the Xcode workspace.

**Comment by parkera** [comment]
I assume in order for this to work you need to install a toolchain based on your compiler PR?

**Comment by eeckstein** [comment]
yeah, this change has to be in sync with the compiler mangling change

**Comment by eeckstein** [comment]
OK, I did run the tests locally by setting SWIFT_EXEC and SWIFT_LIBRARY_PATH to my ToT compiler build.
I worked around one compiler error and got 12 failures in TestNSNumberBridging, which seem to be unrelated to the mangling change.

How can we proceed with that?

**Comment by parkera** [comment]
I know we need to do this, but is there any way we can detect which version of the compiler we're building with to continue to support shipped tools?

Not to overstate it, but it introduces a barrier to contributions which is difficult for some people to get past.

**Comment by eeckstein** [comment]
What you can do is to add a pre-build configuration step. For example:

echo '#define __CFConstantStringClassReference' `swift-demangle --remangle-new '$S15SwiftFoundation19_NSCFConstantStringCN'` > config.h

using the swift-demangle from the toolchain. And then include config.h in CFInternal.h

Or maybe you can just define a build setting outside the Xcode project and then conditionally compile the macro definition in CFInternal.h. A little bit more manual, but simpler.

**Comment by eeckstein** [comment]
@parkera I added a workaround which enables to compile with both compiler versions (old and new mangling prefix)

**Comment by eeckstein** [comment]
Please test with following pull request:
https://github.com/apple/swift/pull/19388

@swift-ci smoke test Linux platform

**Comment by eeckstein** [comment]
Please test with following pull request:
https://github.com/apple/swift/pull/19388

@swift-ci smoke test Linux platform

**Comment by eeckstein** [comment]
Please test with following pull request:
https://github.com/apple/swift/pull/19388

@swift-ci smoke test Linux platform

**Comment by eeckstein** [comment]
Please test with following pull request:
https://github.com/apple/swift/pull/19388

@swift-ci test Linux platform

**Comment by eeckstein** [comment]
Please test with following pull request:
https://github.com/apple/swift/pull/19388

@swift-ci test Linux platform

**Comment by eeckstein** [comment]
Please test with following pull request:
https://github.com/apple/swift/pull/19388

@swift-ci test Linux platform

**Comment by eeckstein** [comment]
Please test with following pull request:
https://github.com/apple/swift/pull/19388

@swift-ci clean test Linux platform

**Comment by eeckstein** [comment]
Please test with following pull request:
https://github.com/apple/swift/pull/19388

@swift-ci clean test Linux platform

**Comment by eeckstein** [comment]
Please test with following pull request:
https://github.com/apple/swift/pull/19388

@swift-ci clean test Linux platform

**Comment by eeckstein** [comment]
Please test with following pull request:
https://github.com/apple/swift/pull/19388

@swift-ci test Linux platform

**Comment by eeckstein** [comment]
Please test with following pull request:
https://github.com/apple/swift/pull/19388

@swift-ci test Linux platform

**Pull request merged**
