### PR TITLE
[gardening] Use optional binding

### PR DESCRIPTION
**Pull request by jarinosuke**

### CODE REVIEW

**Comment by jarinosuke** [comment]
@swift-ci Please test

**Comment by jarinosuke** [comment]
This is my first pull request to this repos, Do I need to implement overlay to https://github.com/apple/swift ?

like these
https://github.com/apple/swift-corelibs-foundation/pull/1358
https://github.com/apple/swift/pull/13314

**Comment by pushkarnk** [comment]
Hi @jarinosuke - You don't need to do that for this particular change. Thanks!

**Comment by pushkarnk** [comment]
@swift-ci please test and merge

**Pull request merged**
