### PR TITLE
Made some upgrades to NSOperatingSystemVersion

### PR DESCRIPTION
**Pull request by rsmoz**
Added tests, too.

### CODE REVIEW

**Comment by phausler** [comment]
This is an API change; any such change should be submitted as a API proposal and undergo review since it would have to be back-ported to the Darwin version of Foundation.

**Comment by rsmoz** [comment]
@phausler Would the proposal go through Swift-evolution, or is that just for the actual language/compiler itself?

**Comment by phausler** [comment]
Yes; swift-evolution is not just for compiler/language but also API changes and how they are exposed in swift. There is a bit more involved with that process since we have to take it to the component owners and have it be a maintained change in both the linux version as well as Mac OS X.

**Comment by parkera** [comment]
I think we should probably do this, but we need to track it as an ER in JIRA first. Closing for now.

**Pull request closed without merging**
