### PR TITLE
Fix Any? -> Any build warnings

### PR DESCRIPTION
**Pull request by e78l**
Addressing build-time warnings of possibly nil values being used as Any [SR-2737] (https://bugs.swift.org/browse/SR-2737)
Some whitespace fixes too

### CODE REVIEW

**Comment by e78l** [comment]
Realized I should include changes to NSHTTPCookie too; I had to change the time format to 'z' in my environment (Amazon Linux, ICU 57.1).
"O" doesn't work to parse "GMT" some reason...
The problem was caught by existing test. 'z' works OK and on my Mac too.
Heads up to @dbrajkovic and @pushkarnk in case something breaks but http://www.unicode.org/reports/tr35/tr35-dates.html#Date_Field_Symbol_Table says 'O' is a fallback for 'z', so I don't expect any problems.

**Comment by parkera** [comment]
We had at least one situation with Any/Any? where it would warn either on Darwin or on Linux. @phausler should double check that.

Also, I would prefer we split up the HTTPCookie format changes into a separate PR.

**Comment by e78l** [comment]
Updated - split off the HTTPCookie format change; HTTPCookie changes to silence warnings about optional values in [String:Any] remain

**Comment by e78l** [comment]
@phausler @parkera Chance for a review? I think this still applies though there've been more warnings introduced since (re: optional string interpolation).

**Comment by phausler** [comment]
@swift-ci Please test and merge

**Pull request merged**
