### PR TITLE
Parity: Bundle(for: AnyClass)

### PR DESCRIPTION
**Pull request by millenomi**
- Use dladdr() with a symbol guaranteed to be in the source image of the class.

 - We cannot replace the Bundle object init() returns, but we can implement equality correctly so that at least `==` can compare bundles correctly if they refer to the same CFBundle.

 - Add testExpectedToFailOnWindows() and associated infrastructure.

### CODE REVIEW

**Comment by millenomi** [comment]
@swift-ci please test

**Comment by millenomi** [comment]
Fixes https://bugs.swift.org/browse/SR-10361

**Comment by millenomi** [comment]
@swift-ci please test

**Comment by spevans** [comment]
@swift-ci please test

**Pull request merged**
