### PR TITLE
Rename *LiteralConvertible conformances to ExpressibleBy*Literal

### PR DESCRIPTION
**Pull request by CodaFi**
In accordance with SE-0115 and apple/swift#3474.

### CODE REVIEW

**Comment by parkera** [comment]
@swift-ci please test

**Comment by CodaFi** [comment]
That may not be a good idea without actually merging the stdlib changes first 😉

**Comment by parkera** [comment]
Ok, please let me know when this is actually ready to merge then.

**Comment by CodaFi** [comment]
Once more?

@swift-ci please test.

**Comment by CodaFi** [comment]
@swift-ci please test.

**Pull request merged**
