### PR TITLE
Implement removeItem on Windows

### PR DESCRIPTION
**Pull request by jmittert**
Use FindFirstFileW to "recursively" remove a directory tree in Windows.

It's probably simpler to implement this by creating a NSURLDirectoryEnumerator (https://github.com/apple/swift-corelibs-foundation/pull/1966) and DeleteFileW/RemoveDirectoryW'ing everything it returns. Would that be the preferred way to do it?

### CODE REVIEW

**Comment by millenomi** [comment]
Either's fine.

**Comment by millenomi** [comment]
@swift-ci please test

**Comment by jmittert** [comment]
Updated to use `.withCString(encodedAs:)` since String.utf16 isn't null terminated.

**Comment by compnerd** [comment]
I think that the DirectoryEnumerator is nicer since we can have the same codepath for all the targets that way.

**Comment by jmittert** [comment]
> 
> 
> I think that the DirectoryEnumerator is nicer since we can have the same codepath for all the targets that way.

See https://github.com/apple/swift-corelibs-foundation/pull/2002

**Comment by millenomi** [comment]
I'm closing this in favor of #2002.

**Pull request closed without merging**
