### PR TITLE
SR-5829: Fix NSString.commonPrefix(with:options:)

### PR DESCRIPTION
**Pull request by spevans**
- Also implement .caseInsensitive option.

Current implementation was buggy and would crash for some strings.
Tests now match Darwin

### CODE REVIEW

**Comment by spevans** [comment]
@swift-ci please test

**Comment by spevans** [comment]
@itaiferber Could you have a look at this string one as well please :)

**Comment by spevans** [comment]
According to https://developer.apple.com/documentation/foundation/nsstring/1408169-commonprefix only `NSCaseInsensitiveSearch` and `NSLiteralSearch` are supported for `commonPrefix(with:options:)` unless Im missing something?

I haven't done any benchmarking because the binary search method didn't actually work and I didn't fully understand how to fix it. I decided to work directly treating the string as a `Character` array and that does not have O(1) performance for random access so I used iterators instead.

**Comment by itaiferber** [comment]
@spevans Hmm, indeed — it looks like we don't support things like `.diacriticInsensitive` or `.widthInsensitive` there on Darwin. Scratch that, then. :)

**Comment by itaiferber** [comment]
Re: perf testing, understandable. The original code does look very much like the actual implementation in `NSString` on Darwin, so I wonder what the differential was there. I'll try to take a look when I have time to investigate.

**Comment by spevans** [comment]
@swift-ci test

**Comment by itaiferber** [comment]
@swift-ci Please test and merge

**Pull request merged**
