### PR TITLE
StringTransform is a top level type not nested in NSString.

### PR DESCRIPTION
**Pull request by spevans**

### CODE REVIEW

**Comment by spevans** [comment]
@swift-ci test

**Comment by compnerd** [comment]
Hmm, is that so?  I got this from the documentation, I wonder how I got that wrong.  Where is this canonically documented?

**Comment by compnerd** [comment]
CC: @millenomi

**Comment by spevans** [comment]
https://developer.apple.com/documentation/foundation/stringtransform

Also try this in Swift Playgrounds, it gives no error:

```
import Foundation
print(StringTransform.latinToArabic.rawValue)
```

**Pull request merged**
