### PR TITLE
Merge pull request #1630 from maksimorlovich/rfc6265-cookie-domain-ma…

### PR DESCRIPTION
**Pull request by maksimorlovich**
…tching

### CODE REVIEW

**Comment by maksimorlovich** [comment]
@ianpartridge Here's the cherry-picked merge from master to 4.2 :) Thanks!

**Comment by spevans** [comment]
@swift-ci please test

**Comment by maksimorlovich** [comment]
@ianpartridge @spevans Can this please be merged in to 4.2 branch? It would really great to have this with the official Swift 4.2 release. Thanks!

**Comment by ianpartridge** [comment]
@swift-ci please test and merge

**Pull request merged**
