### PR TITLE
[SR-11026] CFString allocates more than it needs to, due to Swift.String being smaller now

### PR DESCRIPTION
**Pull request by Catfish-Man**
Fixes https://bugs.swift.org/browse/SR-11026

### CODE REVIEW

**Comment by Catfish-Man** [comment]
@swift-ci please test

**Comment by phausler** [comment]
Seems reasonable to me

**Comment by Catfish-Man** [comment]
@swift-ci please test osx platform

**Comment by spevans** [comment]
Isnt Swift.String still 3 words on 32bit or is that not relevant here?

FYI the macOS testing is currently broken in scl-f (I think since it was upgraded to the Catalina bet).

**Comment by Catfish-Man** [comment]
Oh good point, thank you

**Comment by shahmishal** [comment]
The Swift project moved the default branch to `main` and deleted `master` branch, so GitHub automatically closed the PR. Please re-create pull request with main branch.

More detail about the branch update - https://forums.swift.org/t/updating-branch-names/40412

**Pull request closed without merging**
