### PR TITLE
A temporary work-around for the memory leak in SR-3536 

### PR DESCRIPTION
**Pull request by nethraravindran**

### CODE REVIEW

**Comment by nethraravindran** [comment]
__NSRegularExpressionCache.object(forKey: key._nsObject) in NSString checks for key in Dictionary which holds the 'key reference pointer' as key and the 'NSCacheEntry' as value. Key reference pointer is the reference to NSString Object which can be different for each instance. This is because NSCache on Linux only works with static keys. And Hence we end up having duplicate entries for the same NSString, NSRegularExpression pair causing the memory to leak. So I have disabled the NSCache until a fix for [https://bugs.swift.org/browse/SR-3904] (NSCache working for dynamic keys) is provided.

**Comment by alblue** [comment]
@swift-ci please test

**Comment by alblue** [comment]
I agree; I think this change is necessary until the NSCache implementation can be fixed.

**Comment by ianpartridge** [comment]
Let's get #877 reviewed before merging this? Would be great to just fix the cache.

**Comment by pushkarnk** [comment]
I think this can be closed now.

**Pull request closed without merging**
