### PR TITLE
Changes done to NSJSONSerialization to align with darwin code

### PR DESCRIPTION
**Pull request by saiHemak**

### CODE REVIEW

**Comment by parkera** [comment]
@swift-ci please test

**Comment by ianpartridge** [comment]
Looks like this will need an update to swiftpm too as it depends on the old naming:

```
/home/buildnode/jenkins/workspace/swift-corelibs-foundation-PR-Linux/swiftpm/Sources/ManifestSerializer/JSONSerialization.swift:24:46: error: type 'NSJSONWritingOptions' has no member 'PrettyPrinted'
        let options: NSJSONWritingOptions = .PrettyPrinted
                                             ^~~~~~~~~~~~~
```

**Comment by parkera** [comment]
Do we have a corresponding PR for them?

**Comment by ianpartridge** [comment]
I raised https://github.com/apple/swift-package-manager/pull/357 - can you merge both @parkera ?

**Comment by parkera** [comment]
Ok, let's give this a shot.

**Comment by parkera** [comment]
Mysterious CI failure; I'll revert this while we investigate.

[https://ci.swift.org/job/oss-swift-incremental-RA-linux-ubuntu-14_04/4811/](url)

**Pull request merged**
