### PR TITLE
UserDefaults: Implement volatile domains, argument domain

### PR DESCRIPTION
**Pull request by millenomi**
This implements:
 - The `.volatileDomain(forName:)` API and related calls.
 - The volatile argument domain, `UserDefaults.argumentDomain`.

A note: since there is no language-supported bridging in Swift Foundation, we opt to accept and return value types (Array<_>, Dictionary<_,_>, Date, URL…) rather than reference types (NSArray, NSDictionary, NSDate, NSURL…). We internally convert to reference types them to a. check that you are only saving plist types and b. to support existing persistent domain API (since these objects go to CF and need to be reference types).

### CODE REVIEW

**Comment by millenomi** [comment]
@swift-ci Please test.

**Comment by millenomi** [comment]
:\ I may have to cut some tests, if I can't have TestFoudation do a `@testable import`.

**Comment by millenomi** [comment]
@swift-ci Please test.

**Comment by millenomi** [comment]
@swift-ci Please test.

**Comment by alblue** [comment]
Please rebase on master and resubmit

**Comment by millenomi** [comment]
This has been superseded by: https://github.com/apple/swift-corelibs-foundation/pull/1408

**Pull request closed without merging**
