### PR TITLE
Import stdlib overlay tests

### PR DESCRIPTION
**Pull request by phausler**

### CODE REVIEW

**Comment by phausler** [comment]
@swift-ci Please test

**Comment by phausler** [comment]
There are a few places that still need cleanup for the crash expectations etc; which lit supports but XCTest does not

**Comment by phausler** [comment]
@swift-ci Please test

**Comment by parkera** [comment]
Great work. Let's hold off on merging this until after we've finished with the `swift-3.0-branch` merge.

**Comment by phausler** [comment]
@swift-ci Please test

**Comment by phausler** [comment]
@swift-ci Please test

**Comment by phausler** [comment]
@swift-ci Please test

**Comment by phausler** [comment]
@swift-ci Please test

**Comment by phausler** [comment]
@parkera when we get these passing do we want to go ahead and merge them? There are some extra fixes in here that probably have some reasonably decent impact

**Comment by parkera** [comment]
@phausler Yes, I think so

**Comment by phausler** [comment]
For some reason this is still failing in the linking steps. However no change was made to the ld search paths.

**Comment by phausler** [comment]
@swift-ci Please test

**Comment by phausler** [comment]
@swift-ci Please test

**Comment by phausler** [comment]
@swift-ci Please test

**Comment by phausler** [comment]
@swift-ci Please test

**Comment by phausler** [comment]
@swift-ci Please test

**Comment by phausler** [comment]
@swift-ci Please test

**Comment by phausler** [comment]
@swift-ci Please test

**Comment by alblue** [comment]
This has gone stale - @phausler please re-open if necessary

**Pull request closed without merging**
