### PR TITLE
feat: improve uploadTask fromFile

### PR DESCRIPTION
**Pull request by zymxxxs**
Support asynchronous large file upload

### CODE REVIEW

**Comment by zymxxxs** [comment]
@swift-ci please test

**Comment by spevans** [comment]
@swift-ci please test

**Comment by zymxxxs** [comment]
Looks like a compilation error

**Comment by zymxxxs** [comment]
Hello, I have n’t followed up for a few days. I want to know the specific reason?

the swift-corelibs-foundation is very good, I have been doing similar things recently, I have consulted a lot, and found some network layer bugs, I do n’t know if I should continue to submit PR

**Comment by spevans** [comment]
The macOS test failure can be ignored for now, its known to be faulty.

**Pull request merged**
