### PR TITLE
Update CMakeLists.txt

### PR DESCRIPTION
**Pull request by compnerd**
Bump discovery timeout to see if it helps.

### CODE REVIEW

**Comment by stevapple** [comment]
This problem should go with #3146.

@compnerd Could you take some time to review that now?

**Comment by compnerd** [comment]
Eh?  Why would that impact this?

**Comment by stevapple** [comment]
With #3146 , `TestFoundation` no longer requires anything to be in the path.

DLL paths will be injected by CMake.

**Comment by compnerd** [comment]
Right, I understand that.  I am not seeing the issue locally, only on the swift.org builder.

**Comment by compnerd** [comment]
@swift-ci please test

**Pull request merged**
