### PR TITLE
Fixes and improvements for NSURL

### PR DESCRIPTION
**Pull request by HeMet**
Implement `NSURL.fileSystemRepresentation` and `init(fileURLWithFileSystemRepresentation: isDirectory: relativeToURL)`.
Fix `init(fileURLWithFileSystemRepresentation: isDirectory: relativeToURL)`
Reenable tests for `NSURL`.

### CODE REVIEW

**Comment by phausler** [comment]
on linux I get these failures:
```
Test Case 'TestNSURL.test_URLStrings' started.
Test Case 'TestNSURL.test_URLStrings' passed (1.05 seconds).
Test Case 'TestNSURL.test_fileURLWithPath_relativeToURL' started.
TestFoundation/TestNSURL.swift:86: error: TestNSURL.test_fileURLWithPath_relativeToURL : <CFURL 0x2423ef0 [0x7f48693ed768]>{string = Documents/, encoding = 0
	base = <CFURL 0x2053890 [0x7f48693ed768]>{string = file:///home/phausler/, encoding = 0, base = (null)}} was not equal to <CFURL 0x2424110 [0x7f48693ed768]>{string = Documents, encoding = 0
	base = <CFURL 0x2053890 [0x7f48693ed768]>{string = file:///home/phausler/, encoding = 0, base = (null)}}
TestFoundation/TestNSURL.swift:90: error: TestNSURL.test_fileURLWithPath_relativeToURL : <CFURL 0x2423ef0 [0x7f48693ed768]>{string = Documents/, encoding = 0
	base = <CFURL 0x2053890 [0x7f48693ed768]>{string = file:///home/phausler/, encoding = 0, base = (null)}} was not equal to <CFURL 0x2424220 [0x7f48693ed768]>{string = Documents, encoding = 0
	base = <CFURL 0x2053890 [0x7f48693ed768]>{string = file:///home/phausler/, encoding = 0, base = (null)}}
Test Case 'TestNSURL.test_fileURLWithPath_relativeToURL' failed (0.001 seconds).
Test Case 'TestNSURL.test_fileURLWithPath' started.
TestFoundation/TestNSURL.swift:267: error: TestNSURL.test_fileURLWithPath : Failed to set up test paths
TestFoundation/TestNSURL.swift:301: error: TestNSURL.test_fileURLWithPath : fileSystemRepresentation was too short
TestFoundation/TestNSURL.swift:305: error: TestNSURL.test_fileURLWithPath : fileSystemRepresentation of file path is wrong
Test Case 'TestNSURL.test_fileURLWithPath' failed (0.001 seconds).
Test Case 'TestNSURL.test_fileURLWithPath_isDirectory' started.
TestFoundation/TestNSURL.swift:309: error: TestNSURL.test_fileURLWithPath_isDirectory : Failed to set up test paths
TestFoundation/TestNSURL.swift:353: error: TestNSURL.test_fileURLWithPath_isDirectory : fileSystemRepresentation was too short
TestFoundation/TestNSURL.swift:357: error: TestNSURL.test_fileURLWithPath_isDirectory : fileSystemRepresentation of file path is wrong
Test Case 'TestNSURL.test_fileURLWithPath_isDirectory' failed (0.001 seconds).
Test Case 'TestNSURL.test_URLByResolvingSymlinksInPath' started.
Test Case 'TestNSURL.test_URLByResolvingSymlinksInPath' passed (0.002 seconds).
Executed 5 tests, with 8 failures (0 unexpected) in 0.211 (1.054) seconds
```

**Comment by HeMet** [comment]
Regarding the first two it seems there is no Documents directory in home directory. Also it seems test could not setup files for testing and it produces other failures. I tested it on Ubuntu in VM and it worked.

**Comment by phausler** [comment]
The Documents directory is present for GUI installs; if you have a CLI only install that directory may not exist (e.g. on headless builders like what I was using)

**Comment by phausler** [comment]
the path `/usr/include` might be safer on ubuntu since there is a pre-req to have '-dev' installs of libraries on the machine for things like libxml etc.

**Comment by phausler** [comment]
looks like that cleared up TestNSURL.test_fileURLWithPath_relativeToURL

**Pull request merged**
