### PR TITLE
Moving TransferState out of http folder

### PR DESCRIPTION
**Pull request by saiHemak**
TransferState has 1-on-1 relationship with EasyHandle and is independent of protocol.Hence it has been moved out of the http folder.In the next PR, this code will be aligned under NativeProtocol instead of HTTPURLprotocol which can be used across different protocols.

@alblue , I understand that this PR alone will not make much sense as the code is still an extension of HTTPURLProtocol.To address #1355 ,I have  raised PR for the movement of the file.The code under this PR will be renamed to ```_NativeProtocol``` in the next PR.

### CODE REVIEW

**Comment by pushkarnk** [comment]
This is just a file movement intended for work coming up in a future PR. 

@swift-ci please test and merge

**Comment by alblue** [comment]
@swift-ci please test and merge

**Comment by pushkarnk** [comment]
@swift-ci please test and merge

**Comment by pushkarnk** [comment]
@shahmishal We've been seeing this since yesterday. Could you help please? Thanks. 
```
ERROR: Step ‘Github Pull Request Merger’ aborted due to exception: 
java.io.IOException: Server returned HTTP response code: 405 for URL: https://api.github.com/repos/apple/swift-corelibs-foundation/pulls/1369/merge
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at org.kohsuke.github.Requester.parse(Requester.java:602)
Caused: java.io.IOException: Server returned HTTP response code: 405 for URL: https://api.github.com/repos/apple/swift-corelibs-foundation/pulls/1369/merge
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1926)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1921)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1920)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1490)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.kohsuke.github.Requester.parse(Requester.java:612)
```

**Comment by shahmishal** [comment]
@pushkarnk Looking into it.

**Comment by shahmishal** [comment]
@swift-ci please test and merge

**Comment by shahmishal** [comment]
@pushkarnk It should be fixed now

**Comment by pushkarnk** [comment]
Thanks @shahmishal ! I appreciate the prompt response :)

**Comment by saiHemak** [comment]
Thank you @shahmishal

**Pull request merged**
