### PR TITLE
[SR-2503] Implement subtraction for CharacterSet

### PR DESCRIPTION
**Pull request by xwu**
This is a PR that parallels apple/swift#5201.

Execution is interrupted when `CharacterSet.subtracting(_:)` is invoked. The underlying reason is that `subtracting(_:)` is a default implementation that calls `symmetricDifference(_:)`, but `CharacterSet.symmetricDifference(_:)` invokes `subtracting(_:)`. This PR implements `CharacterSet.subtracting(_:)` and `CharacterSet.subtract(_:)`.

A new test has been added for this code; however, as reported in [SR-2509](https://bugs.swift.org/browse/SR-2509), `CharacterSet.union(_:)` is not currently working in corelibs-foundation, so the test must be disabled in this repo until that entirely separate issue is resolved.

Resolves [SR-2503](https://bugs.swift.org/browse/SR-2503).

### CODE REVIEW

**Comment by parkera** [comment]
I didn't mention it in the other review, but thanks for finding/fixing this @xwu.

**Comment by parkera** [comment]
Seems like we should get to the bottom of SR-2509 before merging this, so we can have the test enabled.

**Comment by xwu** [comment]
@parkera I agree that'd be preferable.

SR-2509 is tricky, though, because it's probably related to another bug (SR-2510) about `NSMutableCharacterSet` in corelibs-foundation. It seems that it's generally borked: try to invert an instance of `NSMutableCharacterSet` and execution is interrupted; ask if "abc" is a superset of "cde" and you get `true`. I'm not getting anywhere fixing that one.

**Comment by parkera** [comment]
Well at least that one is easy to repro. Looks like we are failing to initialize the right callback into Swift. I'll take a closer look.

**Comment by parkera** [comment]
I talked about this with @phausler and he has a fix for 2510 planned soon.

**Comment by xwu** [comment]
@parkera With the new year and SR-2509/10 being still unresolved, any thoughts on maybe merging this first? While it's true the tests would stay disabled, arguably there's value in aligning with changes already merged in the apple/swift repo?

**Comment by parkera** [comment]
Sure.

**Comment by parkera** [comment]
@swift-ci test and merge

**Comment by parkera** [comment]
I have some changes for CFCharacterSet pending which will help with some extant struct CharacterSet bugs as well.

**Pull request merged**
