### PR TITLE
[NSError] Use Error for user info providers to match the Darwin version

### PR DESCRIPTION
**Pull request by ikesyo**

### CODE REVIEW

**Comment by parkera** [comment]
@swift-ci please test and merge

**Comment by ikesyo** [comment]
> Base branch was modified. Review and try the merge again.

Just a merge error.

**Comment by parkera** [comment]
Hm, something mysterious happened to the build after I merged this, #828, and #827. I'm going to revert while we investigate.

**Comment by ikesyo** [comment]
@parkera I'm not sure what was the reason for the failure, but can those reverted PRs be re-reverted now?

**Comment by parkera** [comment]
Sure - can you put up another PR so we can kick off a test-and-merge?

**Pull request merged**
