### PR TITLE
SR-10921: Fix bugs related to XML Namespace.

### PR DESCRIPTION
**Pull request by YOCKOW**
`struct _xmlNode` has two members related to namespace: `ns` and `nsDef`. CoreFoundation uses `ns` instead of `nsDef` in some situations and that causes some bugs such as [SR-10921](https://bugs.swift.org/browse/SR-10921). This PR fixes the issue.

Resolves [SR-10921](https://bugs.swift.org/browse/SR-10921).
(Partially resolves [SR-10764](https://bugs.swift.org/browse/SR-10764).)

### CODE REVIEW

**Comment by pushkarnk** [comment]
@swift-ci please test

**Comment by YOCKOW** [comment]
The failure on macOS seems to be caused by XCTest.

**Comment by pushkarnk** [comment]
@swift-ci please test macOS

**Comment by YOCKOW** [comment]
Due to XCTest failure, again...

**Comment by millenomi** [comment]
@swift-ci please test

**Comment by YOCKOW** [comment]
Seems to be the same failure on macOS.
I believe it is unrelated to this PR...

**Pull request merged**
