### PR TITLE
[Test][NSURLSession] Chunked response

### PR DESCRIPTION
**Pull request by naithar**
As discussed in #911, I've commented out the actual test (It's fail otherwise), but all needed functionality is included.

### CODE REVIEW

**Comment by pushkarnk** [comment]
Thanks @naithar 

@parkera This PR adds a test for #911 along with the necessary changes to `HTTPServer.swift`. Can you please review? Once this one is merged, we can take #911 forward. Thank you.

**Comment by alblue** [comment]
@swift-ci please test

**Comment by parkera** [comment]
Sure, looks good to me. Merge when you're ready.

**Comment by pushkarnk** [comment]
@swift-ci please test and merge

**Pull request merged**
