### PR TITLE
Rename NSRegularExpression options

### PR DESCRIPTION
**Pull request by spevans**
- NSMatchingOptions -> NSRegularExpression.MatchingOptions

- NSMatchingFlags -> NSRegularExpression.MatchingFlags

### CODE REVIEW

**Comment by spevans** [comment]
@ianpartridge See if this looks ok

**Comment by ianpartridge** [comment]
@swift-ci please test

**Comment by ianpartridge** [comment]
Timed out - is this a known issue @shahmishal?

**Comment by spevans** [comment]
is the timeout  total time or time since something was last written to the terminal? I wonder if we can make the tests more chatty rather than just doing the 10..20..30 etc

**Comment by alblue** [comment]
@swift-ci please test

**Comment by ianpartridge** [comment]
@swift-ci please test

**Pull request merged**
