### PR TITLE
[4.2] SR-8689: Fix crash with NSMutableString.replaceOccurrences(of:with:options:)

### PR DESCRIPTION
**Pull request by spevans**
- "\r\n" is treated as a single character, but so are "\r" and "\n"
  so use rangeOfComposedCharacterSequence(at:) to find the range of the
  decomposed character.

- master PR: #1687

### CODE REVIEW

**Comment by spevans** [comment]
cc @weissi @kevints

**Comment by spevans** [comment]
@swift-ci test

**Comment by spevans** [comment]
hmm.. the macOS failure seems to be completely unrelated (same with #1884)

**Comment by kevints** [comment]
Hi @spevans thanks for the PR. This patch definitely appears in scope for backporting. One quick request - it looks like you this is a cherry-pick of 6f194f8828fabc7a379bbd3c54bfb351cc25e566. Can you update this branch with `git cherry-pick -x 6f194f8828fabc7a379bbd3c54bfb351cc25e566` instead? The `-x` flag will include the original commit sha in the cherry-picked commit message, which will make tracking down the history of these backported changes easier.

From the Git docs:
```
       -x
           When recording the commit, append a line that says "(cherry picked from commit ...)" to the original commit message in order to indicate which commit
           this change was cherry-picked from. This is done only for cherry picks without conflicts. Do not use this option if you are cherry-picking from your
           private branch because the information is useless to the recipient. If on the other hand you are cherry-picking between two publicly visible branches
           (e.g. backporting a fix to a maintenance branch for an older release from a development branch), adding this information can be useful.
```

Thanks!

**Comment by spevans** [comment]
@swift-ci test

**Comment by spevans** [comment]
@kevints Ive updated both PRs, and they also tested OK in Xcode. Not sure why the macOS CI is failing.

**Comment by spevans** [comment]
Agreed, I had to use Xcode 10.1, the 10.2 beta caused problems.

**Comment by shahmishal** [comment]
I will update PR testing to support 4.2 beach on macOS.

**Comment by shahmishal** [comment]
@swift-ci test 4.2

**Comment by spevans** [comment]
@kevints I think this PR is good to go now

**Comment by kevints** [comment]
@swift-ci test and merge

**Comment by spevans** [comment]
@swift-ci test and merge

**Pull request merged**
