### PR TITLE
TestFileHandle: Fix NS_FOUNDATION_ALLOWS_TESTABLE_IMPORT

### PR DESCRIPTION
**Pull request by spevans**

### CODE REVIEW

**Comment by spevans** [comment]
@swift-ci test

**Comment by millenomi** [comment]
@swift-ci please test and merge

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by spevans** [comment]
@swift-ci please test and merge

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by spevans** [comment]
@swift-ci please test and merge

**Pull request merged**
