### PR TITLE
Implement attributes enumerating in NSAttributedString

### PR DESCRIPTION
**Pull request by eyeplum**
This pull request implements the following `NSAttributedString` methods:
- `enumerateAttribute(_:in:options:using:)`
- `enumerateAttributes(in:options:using:)`

### CODE REVIEW

**Comment by parkera** [comment]
Cool, thanks.

**Comment by parkera** [comment]
@swift-ci please test and merge

**Comment by eyeplum** [comment]
Hi @parkera, there was a issue in the test case.
It has been fixed. Can we try again?
Thanks.

**Comment by parkera** [comment]
@swift-ci please test and merge

**Pull request merged**
