### PR TITLE
Foundation/Unit: add {m,u,p,n}second units to UnitDuration

### PR DESCRIPTION
**Pull request by AndrewSB**
not 100% sure this wasn't implemented elsewhere, but i didn't see these units

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@parkera this seems like a straightforward change, matches the current documentation at https://developer.apple.com/documentation/foundation/unitduration.  I can't seem to find when the API was introduced, but existed prior to Xcode 14.  Any objections to merging this?

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
> <EXPR>:0: error: SwiftDriverTests.testToolSearching : threw error "failed to retrieve frontend target info"

Seems like a spurious failure.

**Review by parkera — APPROVED** [review]

**Comment by AndrewSB** [comment]
as always, super appreciative of your cross platform work @compnerd. thanks for pushing to get this in

**Pull request merged**
