### PR TITLE
Import CoreFoundation changes from Sierra

### PR DESCRIPTION
**Pull request by phausler**

### CODE REVIEW

**Comment by phausler** [comment]
@swift-ci Please test

**Comment by phausler** [comment]
@swift-ci Please test

**Comment by phausler** [comment]
@swift-ci Please test

**Comment by phausler** [comment]
@swift-ci Please test

**Comment by parkera** [comment]
@swift-ci please test

**Comment by phausler** [comment]
@swift-ci please test

**Comment by phausler** [comment]
@parkera can you get the CI to test this?

**Comment by parkera** [comment]
@swift-ci please test and merge

**Comment by parkera** [comment]
@emish @erg we're having problems kicking off the CI again from this repo.

**Comment by parkera** [comment]
I think the status never appeared, but it looks like it did actually run.

**Pull request merged**
