### PR TITLE
Import the latest version of struct Data

### PR DESCRIPTION
**Pull request by phausler**

### CODE REVIEW

**Comment by phausler** [comment]
@swift-ci please test and merge

**Comment by phausler** [comment]
@swift-ci please test and merge

**Comment by phausler** [comment]
@swift-ci please test and merge

**Comment by phausler** [comment]
@swift-ci please test

**Comment by parkera** [comment]
@swift-ci please test and merge

**Comment by phausler** [comment]
Umm what is going on here?

```
Building remotely on macOS-16 (trigger-bot) in workspace /Users/buildnode/jenkins/workspace/swift-corelibs-foundation-PR-merge
```

This should be testing on linux not macOS

**Comment by phausler** [comment]
@swift-ci please test and merge

**Comment by phausler** [comment]
@parkera please test and merge

**Comment by phausler** [comment]
@swift-ci Please test and merge

**Comment by parkera** [comment]
@swift-ci please test and merge

**Comment by parkera** [comment]
@shahmishal @erg Why does it appear that this PR testing is being run on a macOS builder? swift-corelibs-foundation is for Linux only.

**Comment by erg** [comment]
I'm not sure why.

Filed as rdar://problem/29687947

**Comment by shahmishal** [comment]
> @shahmishal @erg Why does it appear that this PR testing is being run on a macOS builder? swift-corelibs-foundation is for Linux only.

The request "Please test and merge" triggers a bot https://ci.swift.org/job/swift-corelibs-foundation-PR-merge/89/ which triggers another bot https://ci.swift.org/job/swift-corelibs-foundation-PR-Linux/476/. The trigger bot is ran on macOS, however Linux testing happened on [Linux bot](https://ci.swift.org/job/swift-corelibs-foundation-PR-Linux/476/).

**Comment by phausler** [comment]
@swift-ci please test and merge

**Comment by phausler** [comment]
@swift-ci please test and merge

**Comment by parkera** [comment]
@swift-ci please test and merge

**Pull request merged**
