### PR TITLE
Restore previous value of `Decimal.leastFiniteMagnitude` for compatibility and deprecate

### PR DESCRIPTION
**Pull request by xwu**
See discussion in #3067.

### CODE REVIEW

**Comment by xwu** [comment]
@swift-ci test

**Review by spevans — CHANGES_REQUESTED** [review]
I agree with reverting to the previous value but the deprecation would require more discussion so that should be removed for now (although the clarifying message is actually really useful).

**Comment by stephentyrone** [comment]
@spevans Let's start that discussion then, since the property is both useless and misleading and should definitely be deprecated.

**Comment by spevans** [comment]
Sorry, I meant it would be up to the Foundation team to decide on the API change, so just removing the deprecation change would allow the PR to go through whilst they come to a decision. Personally I think its a reasonable change.

cc @millenomi

**Comment by millenomi** [comment]
I'm okay with the deprecation. @phausler, any objections?

**Comment by phausler** [comment]
nah, this is fine to deprecate

**Review by spevans — APPROVED** [review]

**Pull request merged**
