### PR TITLE
Remove some TODOs

### PR DESCRIPTION
**Pull request by talzag**
Some of the TODOs in NSIndexSet regarding bounds checking were already implemented.

### CODE REVIEW

**Comment by talzag** [comment]
Reverted. That's what happens when I assume lol

**Comment by parkera** [comment]
Would you mind cleaning this up into a single commit (especially avoiding the merge commit and the revert)?

**Comment by talzag** [comment]
There we go, sorry about that!

**Comment by talzag** [comment]
There we go, one commit!

**Pull request merged**
