### PR TITLE
Fix Data(count:) to correctly zero the data

### PR DESCRIPTION
**Pull request by spevans**
- Use calloc() instead of malloc()

### CODE REVIEW

**Comment by phausler** [comment]
@swift-ci Please test Linux

**Comment by phausler** [comment]
The build failure is not associated with this commit, will check back later when the build bot is healthy

**Comment by parkera** [comment]
Looks reasonable to me. Kicking off another test.

**Comment by parkera** [comment]
@swift-ci please test linux

**Comment by parkera** [comment]
Ugh, the build status disappeared.

**Comment by parkera** [comment]
@swift-ci please test linux

**Comment by parkera** [comment]
@swift-ci please test linux

**Comment by parkera** [comment]
Tested manually

**Pull request merged**
