### PR TITLE
Fix power prefix in Unit.swift

### PR DESCRIPTION
**Pull request by tgu**
fix prefix for UnitPower

### CODE REVIEW

**Comment by spevans** [comment]
@swift-ci please test

**Comment by parkera** [comment]
The implementation looks right in the Darwin Foundation, so it looks like a doc bug. I'll take care of it separately.

**Comment by ianpartridge** [comment]
@swift-ci please test and merge

**Comment by ianpartridge** [comment]
@swift-ci please test and merge

**Pull request merged**
