### PR TITLE
Add TARGET_{CPU_WASM32,OS_WASI} to TargetConditionals.h

### PR DESCRIPTION
**Pull request by MaxDesiatov**
These are required for WebAssembly and WASI support in CoreFoundation.

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
@swift-ci please test

**Comment by millenomi** [comment]
cc @parkera re: the use of TARGET_OS_WASI as discussed.

**Comment by millenomi** [comment]
@swift-ci please test and merge

**Comment by MaxDesiatov** [comment]
The failed unit test on macOS is `ClangImporter/./SwiftClangImporterTests/ClangImporterTest.missingSubmodule`, I don't think that's related.

**Comment by MaxDesiatov** [comment]
It's also the same failure that that the `master` toolchain macOS builds fail with.

**Comment by MaxDesiatov** [comment]
@swift-ci please smoke test OS X Platform

**Comment by MaxDesiatov** [comment]
@swift-ci please test OS X Platform

**Comment by MaxDesiatov** [comment]
@swift-ci please test macOS platform

**Comment by MaxDesiatov** [comment]
@swift-ci please test and merge

**Comment by MaxDesiatov** [comment]
@swift-ci please test and merge

**Pull request merged**
