### PR TITLE
NSHTTPCookie v1 tests and refactoring

### PR DESCRIPTION
**Pull request by tptee**
Added tests for initializing a v1 cookie. Also, broke a lot of the initializer logic into separate private functions for clarity.

### CODE REVIEW

**Comment by phausler** [comment]
@salgernon this seems to build just fine on both mac and linux; do we have any issues here?

**Comment by dbrajkovic** [comment]
@salgernon & @phausler Please see https://github.com/apple/swift-corelibs-foundation/pull/182 before accepting.

**Comment by salgernon** [comment]
Finally looking at this, and with it #182; I think we need a synthesis of the two patches for the NSHTTPCookie changes.  Let me think about how we can best proceed for the NSHTTPCookie implementation itself with that change.  (I think everyone is basically on the same page.)

**Comment by parkera** [comment]
Ok, I think we've subsumed this into #182.

**Pull request closed without merging**
