### PR TITLE
SR-11699: Process: Closing standardInput before calling run() aborts with EBADF

### PR DESCRIPTION
**Pull request by spevans**
- Check the file descriptor passed to _CFPosixSpawnFileActionsAddClose()
  is valid.

### CODE REVIEW

**Comment by spevans** [comment]
@swift-ci test

**Comment by Kaiede** [comment]
Aha, when I looked at this earlier when I hit it, I didn’t have quite enough time to ingest what was going on. This makes a lot of sense now that I’ve had time to read it: not checking to see if the FD is already closed before telling the child process to close it (to avoid the child process to have say, write access to the standard input pipe). 

Thanks for the quick turnaround on this one.

**Comment by spevans** [comment]
@swift-ci test linux

**Comment by spevans** [comment]
@swift-ci test linux

**Comment by spevans** [comment]
@swift-ci test linux

**Comment by spevans** [comment]
@swift-ci test linux

**Comment by spevans** [comment]
@swift-ci test and merge

**Pull request merged**
