### PR TITLE
Adopt new XCTAssertEqualWithAccuracy spelling in the tests.

### PR DESCRIPTION
**Pull request by briancroom**
Once https://github.com/apple/swift-corelibs-xctest/pull/193 lands, this can go in to clean up the deprecation warnings.

### CODE REVIEW

**Comment by parkera** [comment]
Looks ok to me

**Comment by alblue** [comment]
@swift-ci please test

**Comment by alblue** [comment]
Looks like it's failed with the missing 'accuracy:' arguments

```
TestFoundation/TestNSURLSession.swift -o ../Ninja-ReleaseAssert/foundation-linux-x86_64/TestFoundation/TestFoundation
TestFoundation/TestNSTimer.swift:62:13: error: argument labels '(_:, _:, accuracy:)' do not match any available overloads
            XCTAssertEqual(currentInterval, previousInterval + interval, accuracy: 0.01)
            ^
```

**Comment by alblue** [comment]
Ah, apple/swift-corelibs-xctest#193 hasn't been merged yet :)

**Comment by briancroom** [comment]
@swift-ci please test

**Pull request merged**
