### PR TITLE
build: repair the build

### PR DESCRIPTION
**Pull request by compnerd**

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @spevans

**Comment by compnerd** [comment]
@swift-ci please smoke test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by drodriguez** [comment]
It might also not be a bad time to look at #2246, since it cleans up `libdispatch_ldflags` from the RPATH flags.

**Comment by drodriguez** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Pull request merged**
