### PR TITLE
Foundation API Conformance Update: URLs

### PR DESCRIPTION
**Pull request by itaiferber**
#### `NSURL`
* Add resource values API
* `public` → `open`
* `fileURLWithPathComponents(_ components: [String])` → `fileURL(withPathComponents components: [String])`
* `AnyObject` → `Any`
* Add missing URL resource keys

#### `NSURLQueryItem`
* `public` → `open`

#### `NSString`
* `stringByAddingPercentEncodingWithAllowedCharacters(_ allowedCharacters: CharacterSet)` → `addingPercentEncoding(withAllowedCharacters allowedCharacters: CharacterSet)`
* `stringByRemovingPercentEncoding: String?` → `removingPercentEncoding: String?`

#### `URL`
* Integrate work from overlay (with nullability/throws changes)
* Update tests to remove now missing elements (e.g. `resourceSpecifier`)
* Update auxiliary usages to match new nullability/throws

#### `URLComponents`/`URLQueryItems`/`URLRequest`
* Integrate work from overlay

#### `NSURLRequest`
* Update types in `NetworkServiceType`

### CODE REVIEW

**Comment by itaiferber** [comment]
@swift-ci Please test

**Comment by itaiferber** [comment]
Tested manually as well but want to make sure that it builds correctly in a clean environment

**Comment by itaiferber** [comment]
Build failed due to changes in NSTask & associated tests. Working to resolve conflicts with https://github.com/apple/swift-corelibs-foundation/pull/555

**Comment by phausler** [comment]
Tested manually after fixing merge damage

**Pull request merged**
