### PR TITLE
Moves inside loop left operand of comma operator in do-while loop condition

### PR DESCRIPTION
**Pull request by valeriyvan**
Fix resolves warning of possible misuse of comma operator.
Fix preserves original logic.
But it seems like what was moved inside loop could be removed completely.
Or it might be that condition in do-while before fix was wrong and there should be && instead of comma operator.

### CODE REVIEW

**Comment by compnerd** [comment]
Pretty sure that this was an existing bug, but your change simply drops the check which doesn't make sense to move into the loop.  I think it is better to fix this and that the intent was that both of them should be true and need to be concatenated with `&&`.

**Comment by valeriyvan** [comment]
Done

**Comment by valeriyvan** [comment]
Ping

**Comment by valeriyvan** [comment]
ping

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by compnerd** [comment]
CC: @millenomi

**Comment by millenomi** [comment]
I'm purposefully not taking patches that change the layout of CF code right now because I'm working on finishing this year's merge.

**Comment by millenomi** [comment]
I finished this year's merge!

**Pull request closed without merging**
