### PR TITLE
[NSCalendar] Drop needless word to match Darwin.

### PR DESCRIPTION
**Pull request by damuellen**
@modocache replacement for #371 please test and merge

### CODE REVIEW

**Comment by modocache** [comment]
Thanks, @damuellen! Sorry for the inconvenience. Part of the trouble is that, last I checked, Foundation's repository doesn't have "please test and merge" enabled. I wonder if that's changed...

@swift-ci please test and merge

**Comment by modocache** [comment]
Yup, sure enough, it looks like that didn't work.

@swift-ci please test

**Comment by modocache** [comment]
Or maybe I just don't have permissions to trigger CI on this repository at all...? @parkera, could you kick this off?

**Comment by parkera** [comment]
@swift-ci please test

**Comment by parkera** [comment]
I haven't been able to get the test-and-merge thing to work either.

**Comment by modocache** [comment]
"test and merge" is enabled on a per-repo basis -- I think only apple/swift supports it. It's not enabled for swift-corelibs-xctest, for example. The situation might be remedied with some sort of offering/bribe to @shahmishal... 😆

**Comment by parkera** [comment]
I pinged the proper authorities, hopefully we'll get it turned on soon.

**Comment by damuellen** [comment]
I looked at the Foundation shipped in Xcode 8 and realised that there is another change in the api,
this is now a class var, I also overlooked a test that was added in the meantime.
I found similar changes in NSLocation for which I will create another PR.

**Comment by damuellen** [comment]
@parkera  I'm sorry, but somehow I managed to mix my two requests, practice makes perfect.
But I found similar changes in Thread, Host and FileManager. I could make one new PR for all,or spilt them up. What do you prefer ?

**Comment by parkera** [comment]
Splitting them up sounds good, thanks.

**Pull request closed without merging**
