### PR TITLE
String: fix potential unaligned access

### PR DESCRIPTION
**Pull request by compnerd**
A potential unaligned access was identified by UBSAN.  It is unclear if this is
a correctness issue, but may be a source for some inefficient code.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

CC: @parkera @phausler

**Comment by phausler** [comment]
The only calling points are from __CFStringCreateImmutableFunnel3, which would mean that a caller of CFStringCreateWithCString would have to pass an un-aligned buffer somehow

**Comment by compnerd** [comment]
@phausler this is motivated by the desire to avoid UBSAN warnings, and why I call out in the commit message that this isn't really a correctness issue.

**Comment by compnerd** [comment]
@parkera @phausler ping?  This can also be a slight optimization since we will pre-process to get into a wider stride.

**Comment by alblue** [comment]
This pull request has gone stale, closing. If required, please re-base onto master and reopen.

**Pull request closed without merging**
