### PR TITLE
[5.2] improve URLError returned upon task cancellation

### PR DESCRIPTION
**Pull request by glessard**
previously merged to master in https://github.com/apple/swift-corelibs-foundation/pull/2825

### CODE REVIEW

**Comment by spevans** [comment]
Has this been backported to the 5.3 branch yet? If not it will need to be so it doesnt get reverted by 5.3

**Comment by spevans** [comment]
cc @drexin

**Comment by spevans** [comment]
@swift-ci test

**Comment by glessard** [comment]
@spevans Makes sense. I will do that too.

**Comment by glessard** [comment]
note: merged to the 5.3 branch in https://github.com/apple/swift-corelibs-foundation/pull/2844

**Comment by drexin** [comment]
@swift-ci test 5.2 macos

**Comment by drexin** [comment]
@swift-ci test 5.2 macos

**Pull request merged**
