### PR TITLE
Start the NSMassFormatter implementation

### PR DESCRIPTION
**Pull request by mauriciomeirelles**
Start the implementation of NSMassFormatter and create its tests. I’ve started with English, with and without metric system. To finish all other languages I’ll need the translations for “kg”, “g”, “lb”, “oz”,
“kilograms”, “grams”, “pounds”, “ounces”.

### CODE REVIEW

**Comment by mauriciomeirelles** [comment]
Can this be accepted as the initial implementation of the NSMassFormatter?
Do you have any tips?

**Comment by scanf** [comment]
I would squash the merge commit.

**Comment by mauriciomeirelles** [comment]
Done

**Comment by phausler** [comment]
the darwin version uses ICU to handle the unit values (since getting into the game of translations and unit localizations is perhaps a bit of a huge task). The Objective-C versions of these funnel to uplrules_select and friends to fetch the conversions and localized versions of the names/suffixes.

**Comment by parkera** [comment]
As this PR seems to be inactive, I'm going to close it. Please feel free to re-open with a rebased patch.

**Pull request closed without merging**
