### PR TITLE
NSNotification.Name is sendable

### PR DESCRIPTION
**Pull request by jumhyn-browser**

### CODE REVIEW

**Review by compnerd — APPROVED** [review]
CC: @parkera

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by jumhyn-browser** [comment]
Windows run [succeeded ](https://ci-external.swift.org/job/swift-corelibs-foundation-PR-windows/181/) but didn't get linked back here for some reason.

@parkera any idea on the macOS failure here? I thought @kateinoigakukun's #4873 should have addressed this but I rebased onto that change this morn

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by parkera** [comment]
I think #4873 addressed something completely different for the macOS builds. I'm not sure why we are even attempting to run argument parser's tests in the SCL-F PRs.

**Review by parkera — APPROVED** [review]

**Pull request merged**
