### PR TITLE
[CF] Unify implementations of _CFProcessPath.

### PR DESCRIPTION
**Pull request by 3405691582**
Firstly, `_CFProcessPath` has no implementation for TARGET_OS_BSD. Indeed,
there is no portable implementation of this action across multiple
platforms. As an initial implementation for TARGET_OS_BSD, use the
environment to help us. Some shells set the environment variable "_" to
the path used to invoke the binary. This mirrors the implementation for
TARGET_OS_OSX, so add the same conditionals on `__CFProcessIsRestricted`.

Relying on the shell has drawbacks, including that the shell doesn't set
the full path to the current executable if it isn't part of the PATH
(or, of course, specified explicitly). Perhaps on some other platforms
there is some miscellaneous kernel trickery that could be done, but
let's defer that to the future and keep getenv("_") as a last resort.

Second, given that, we should bring the implementations together (like
we've done elsewhere), not to mention that `_CFProcessPath` is fundamental
to other parts of CF. This highlights the repetition in each
implementation, so here we also factor off some of it and share it
across the implementations to facilitate code reuse.

### CODE REVIEW

**Comment by 3405691582** [comment]
@compnerd This is mainly a mechanical change, but could you double check this on the win32 buildbot please?

**Comment by compnerd** [comment]
https://dev.azure.com/compnerd/swift-build/_build/results?buildId=26671&view=results

**Comment by millenomi** [comment]
@swift-ci please test

**Comment by 3405691582** [comment]
macOS test failure looks unrelated, since it seems to be in xctest and that it has been failing in the same fashion since at least [build 2072 on March 30](https://ci.swift.org/job/swift-corelibs-foundation-PR-macOS/2072/).

**Comment by compnerd** [comment]
@3405691582 this needs to be rebased as there is now a conflict.

**Comment by 3405691582** [comment]
Rebase completed.

**Comment by spevans** [comment]
@swift-ci please test

**Comment by spevans** [comment]
@swift-ci please test

**Pull request merged**
