### PR TITLE
Match types when calculating remaining in FileHandle's _readDataOfLength

### PR DESCRIPTION
**Pull request by gonzalolarralde**
This was causing an error when trying to get the remaining amount of data.

### CODE REVIEW

**Comment by mattrajca** [comment]
Can you add a test for this?

**Comment by pushkarnk** [comment]
Per [this](https://linux.die.net/man/2/stat) the `st_size` member is also of type `off_t`. Am I missing something here?

**Comment by gonzalolarralde** [comment]
@mattrajca @pushkarnk sorry for the lack of context in the original message.

@pushkarnk it is true for linux, it is not for 32-bits arm or at least in [bionic](https://github.com/android/platform_bionic/blob/master/libc/include/sys/stat.h#L107). This is causing a compilation error when trying to combine a `long long` with an `off_t` without casting.

@mattrajca this wasn't causing a runtime error but a compilation error under some particular circumstances (`-target armv7-linux-androideabi` in my case)

**Comment by parkera** [comment]
@swift-ci please test

**Comment by parkera** [comment]
Let's see if this causes a compilation error on other platforms...

**Comment by pushkarnk** [comment]
I think we can merge this. It seems to be blocking compilation of Foundation on the said platform. On platforms where `st_size` is of type `off_t` (where a cast isn't necessary), I don't think this explicit cast should cause a problem.

**Comment by pushkarnk** [comment]
@swift-ci please test and merge

**Pull request merged**
