### PR TITLE
[CF] Expose mach_absolute_time for BSD.

### PR DESCRIPTION
**Pull request by 3405691582**
This is exposed for Linux, but also is needed for linking on BSD.

(Let me know if you think there should be one definition of mach_absolute_time in Prefix and the body ifdef'd between Windows and Linux/BSD. I thought to include that in this PR, but I'm not sure I like the look of it, so I omitted it. If you think it'd be worthwhile though, I'm happy to roll it in this PR.)

### CODE REVIEW

**Comment by spevans** [comment]
@swift-ci test linux

**Comment by compnerd** [comment]
@3405691582 I think that it would be nice to have the shared location for the shims.

**Comment by 3405691582** [comment]
Added an extra commit to the branch.

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by spevans** [comment]
Probably worth squashing this down into one commit

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by 3405691582** [comment]
Re suggestion by @spevans, squashed down to two commits: one for the mach_absolute_time refactor, and another for the ifdef tidying. (I think squashing down to one is perhaps a little too aggressive.)

**Comment by spevans** [comment]
@swift-ci test

**Comment by spevans** [comment]
@swift-ci test

**Comment by compnerd** [comment]
*sigh* seems that this broke the Windows build.

**Comment by 3405691582** [comment]
Argh; sorry about that. :(

**Pull request merged**
