### PR TITLE
[SR-3032] Fix comment in Locale

### PR DESCRIPTION
**Pull request by pedrovereza**
Reported in [SR-3032](https://bugs.swift.org/browse/SR-3032)

### CODE REVIEW

**Comment by pushkarnk** [comment]
It could have also been:
```/// For example, in the "en" locale, the result for `"es"` is `"Spanish"`.``` 😀

**Comment by pushkarnk** [comment]
This is a simple comment change and it looks correct to me. I'll go ahead and merge.
@swift-ci please test and merge

**Comment by pushkarnk** [comment]
@swift-ci please test and merge

**Comment by pushkarnk** [comment]
@swift-ci please test and merge

**Comment by parkera** [comment]
Actually, can we match the content of this commit from the overlay?

https://github.com/apple/swift/commit/1a08dc87a385bc15336dd8753386296bc1f80e52

**Comment by pedrovereza** [comment]
@parkera done! :wink:

**Comment by parkera** [comment]
Thanks!

**Pull request merged**
