### PR TITLE
Swift 3 API for NSURLSession's uploadTask 'from' parameter

### PR DESCRIPTION
**Pull request by 0xpablo**
See https://developer.apple.com/reference/foundation/nsurlsession/1409763-uploadtask

### CODE REVIEW

**Comment by 0xpablo** [comment]
@swift-ci please test

**Comment by 0xpablo** [comment]
@swift-ci Please test

**Comment by phausler** [comment]
@swift-ci Please test

**Comment by parkera** [comment]
@swift-ci please test and merge

**Pull request merged**
