### PR TITLE
Implement ._hidden on Windows

### PR DESCRIPTION
**Pull request by gmittert**
Windows has a specific attribute to mark a file as hidden as opposed to
prefixing ".". This allows setting and getting the attribute. On POSIX,
it will return based on the "." prefix and setting it does nothing.

### CODE REVIEW

**Comment by gmittert** [comment]
@millenomi Are you okay with adding in attributes, especially ones that are more Windows specific? If not, what would be the better way to add this support?

cc @compnerd

**Comment by millenomi** [comment]
(There is already a private ._hidden attribute, IIRC?)

**Comment by millenomi** [comment]
I can consider a Windows-only attribute that is prefixed if there is a compellingly strong use case other than completeness; but the right way to do this is to ask for a new API via Radar. However, in this case, we already have API that corresponds to this in a more modern API (it's `URLResourceKey.isHiddenKey`), and we tend to not duplicate, so I would advise making sure that that one works correctly instead.

**Comment by gmittert** [comment]
I see, I misunderstood how the private attributes worked. I've changed it to use _hidden via URLResource now.

@swift-ci please test linux

**Comment by gmittert** [comment]
@swift-ci please test linux

**Comment by millenomi** [comment]
@swift-ci please test linux

**Comment by gmittert** [comment]
@swift-ci please test linux

**Comment by gmittert** [comment]
@swift-ci please test linux

**Comment by gmittert** [comment]
@swift-ci please test linux

**Comment by gmittert** [comment]
@swift-ci please test linux

**Comment by gmittert** [comment]
@swift-ci please test

**Comment by gmittert** [comment]
@swift-ci please test

**Pull request merged**
