### PR TITLE
change ProcessInfo.processinfo() class func to processinfo static let

### PR DESCRIPTION
**Pull request by jpsim**
to align with recent changes on Darwin (Xcode 8)

### CODE REVIEW

**Comment by parkera** [comment]
@swift-ci please test

**Comment by jpsim** [comment]
FYI I'm sure there are many more of these than the 3 PRs I just filed. A good starter task could be to audit all of the changes in Foundation from Xcode 8 betas and align Swift Foundation with them.

**Comment by jpsim** [comment]
The CI failure seems due to `swift-corelibs-xctest` relying on `processInfo` being a function. Looks like these two changes would have to be made simultaneously. How would you suggest we do this @parkera?

**Comment by parkera** [comment]
Can you put up a PR for XCTest? I'll merge them together.

**Comment by jpsim** [comment]
Sure thing! apple/swift-corelibs-xctest#144

**Comment by parkera** [comment]
Hm, is it possible to temporarily stage this by having both names in Foundation?

**Comment by jpsim** [comment]
> Hm, is it possible to temporarily stage this by having both names in Foundation?

I don't think so, since referring to `ProcessInfo.processInfo` would then be ambiguous because that's also a valid way to refer to the `processInfo()` function.

**Comment by parkera** [comment]
Ok - let's hold off on this particular change for a few days. The rest of Swift is scrambling to land source breaking changes, but per my email to swift-corelibs-dev earlier today, we have a few more weeks. That will keep us out of the line of fire while everything else finishes up.

**Comment by parkera** [comment]
Then we can do a simultaneous merge of both PRs.

**Comment by jpsim** [comment]
happy to wait if it helps

**Comment by jpsim** [comment]
rebased

**Comment by parkera** [comment]
Hopefully we can un-stick the Linux builder today and land this. Thanks for your patience.

**Comment by parkera** [comment]
Going to go ahead and merge these.

**Pull request merged**
