### PR TITLE
Avoid unnecessarily allocating an array when initializing `String` from a sequence of bytes

### PR DESCRIPTION
**Pull request by fumoboy007**

### CODE REVIEW

**Comment by fumoboy007** [comment]
Will these changes automatically make it into the Darwin implementation once merged or do we need to create an Apple feedback report for that?

**Comment by parkera** [comment]
The Darwin implementation (and future everywhere implementation) is over here: https://github.com/apple/swift-foundation/blob/main/Sources/FoundationEssentials/String/String%2BEssentials.swift#L86

**Comment by fumoboy007** [comment]
Oh nice, it already has this optimization!

**Comment by fumoboy007** [comment]
@parkera Should we merge this?

**Comment by parkera** [comment]
@swift-ci test

**Comment by fumoboy007** [comment]
The macOS issue seems to be
```
CMake Error at CMakeLists.txt:11 (project):
  The CMAKE_C_COMPILER:

    /Users/ec2-user/jenkins/workspace/swift-corelibs-foundation-PR-macOS/branch-main/build/Ninja-ReleaseAssert/toolchain-macosx-x86_64/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.
```

**Comment by MaxDesiatov** [comment]
@swift-ci test macos

**Comment by fumoboy007** [comment]
All checks passed!

**Comment by fumoboy007** [comment]
Happy New Year! Please review. 🙏

**Review by parkera — APPROVED** [review]

**Pull request merged**
