### PR TITLE
build: migrate to the new ELF registration scheme

### PR DESCRIPTION
**Pull request by compnerd**
The new ELF registration scheme uses linker tables and only requires a
single object to be added to the link.

### CODE REVIEW

**Comment by alblue** [comment]
Does this require synchronous testing across all repositories with this change? Do you know when it's planned to land?

**Comment by compnerd** [comment]
@alblue yeah, it requires synchronous testing :-(.  I was looking into a final failure with the ELF migration.  There is a single failure in a single test case now (associated type reflection for a remote image which is not loaded but rather mapped into memory).  It is part of the same ELF metadata loading change for now at least.

**Comment by compnerd** [comment]
This was tested as part of apple/swift#12758

**Comment by aschwaighofer** [comment]
Hi @compnerd this got auto merged to swift-4.1-branch of corelibs. And is breaking there (https://ci.swift.org/job/oss-swift-4.1-incremental-RA-linux-ubuntu-16_04-long-test/258/)

I have reverted it on that branch: https://github.com/apple/swift-corelibs-foundation/commits/swift-4.1-branch

Because I believe if we want it there we also need to port apple/swift#12758 to swift's swift-4.1-branch.

**Pull request merged**
