### PR TITLE
Add tests for NSClassFromString and NSStringFromClass

### PR DESCRIPTION
**Pull request by JGiola**
I've add simple test coverage for NSStringFromClass and NSClassFromString

### CODE REVIEW

**Comment by parkera** [comment]
@swift-ci please test and merge

**Comment by JGiola** [comment]
It seems to fail tests on Linux, but I can't find what is failing, where I have to look?

**Comment by JGiola** [comment]
Found it! It was the tests with the class from XCTest that was failing because on Linux the module is named SwiftXCTest and not only XCTest.

**Comment by parkera** [comment]
@swift-ci please test and merge

**Pull request merged**
