### PR TITLE
[test] Drop stdlib-redundant tests

### PR DESCRIPTION
**Pull request by milseman**
hasPrefix/hasSuffix is now available universally from the standard
library (it used to be Darwin only). As such, these tests are
redundant with the tests in the standard library (indeed they are
literally copy-pasted from the stdlib). As test methodology changes,
maintaining these across projects and platforms is troublesome.

### CODE REVIEW

**Comment by milseman** [comment]
@airspeedswift I believe you made the changes to make this test redundant.

**Comment by milseman** [comment]
@swift-ci please test

**Comment by milseman** [comment]
Argh, I couldn't build this because of another issue locally. I will download a toolchain and try again on Mac.

**Comment by milseman** [comment]
@swift-ci please test

**Comment by milseman** [comment]
@swift-ci please test

**Comment by milseman** [comment]
Small string merged. This will be needed for CI. 

@parkera @phausler @Catfish-Man does this look ok? Can I merge after the builder?

**Comment by milseman** [comment]
@shahmishal @aschwaighofer this might be needed to unbreak CI Linux. Hoping to get a LGTM from @parker, but worse case we merge to unbreak CI, he can revert, and I’ll have to bring 🍻🍺 to apologize

**Comment by shahmishal** [comment]
Merged to unblock CI.

**Comment by phausler** [comment]
Btw this test was leftover from before the id to any transition where it was previously testing NSString and not String. Since we fixed the return types of the APIs to favor structures in Foundation this test is vestigial.

**Pull request merged**
