### PR TITLE
Added libcurl abstractions to libcurl directory

### PR DESCRIPTION
**Pull request by saiHemak**
I am creating this PR based on the comments received for #1216.

@alblue @xwu @pushkarnk  This PR has the changes  which needed just a movement from one folder to the other.
I will be raising other PR for which basically carves out the common code to Nativeprotocol.
Please review ..

### CODE REVIEW

**Comment by alblue** [comment]
This looks good, but please squash all of these down to a single commit, since the changes for the intermediate changes won't be buildable (as they'll be missing from the Xcode project file). If you can do that, I can kick off a test-and-merge step. Thanks!

**Comment by saiHemak** [comment]
@alblue , Sure ..

**Comment by saiHemak** [comment]
@alblue  Done ..Please review

**Comment by alblue** [comment]
@swift-ci please test and merge

**Comment by alblue** [comment]
@swift-ci please test and merge

**Pull request merged**
