### PR TITLE
SR-10689: Fix bugs of DataProtocol's firstRange(of:in:)/lastRange(of:in:).

### PR DESCRIPTION
**Pull request by YOCKOW**
`DataProtocol`'s `firstRange(of:in:)` and `lastRange(of:in:)` return a wrong value or crash under some conditions because they handle indices incorrectly.
This PR fixes the issue.

Resolves [SR-10689](https://bugs.swift.org/browse/SR-10689).

-----

Note:
SR-10689 also says "`lastRange(of:)` returns `firstRange(of:in:)`", however, it has been already fixed by #2310.

### CODE REVIEW

**Comment by spevans** [comment]
@swift-ci test

**Comment by YOCKOW** [comment]
Rebased to resolve conflicts.

**Comment by spevans** [comment]
@swift-ci test

**Comment by YOCKOW** [comment]
The failures seem to be unrelated to this PR, don't they...?

**Comment by CodaFi** [comment]
@swift-ci test

**Comment by CodaFi** [comment]
@swift-ci test

**Comment by YOCKOW** [comment]
@CodaFi 

Thank you for running tests.

[The error on macOS](https://ci.swift.org/job/swift-corelibs-foundation-PR-macOS/2088/consoleFull#-182906423122a513-f36a-4c87-8ed7-cbc36a1ec144) seems to be unrelated.

**Comment by CodaFi** [comment]
@swift-ci test macOS

**Comment by CodaFi** [comment]
@swift-ci test

**Comment by YOCKOW** [comment]
The failure on Linux seems to be caused by LLDB...

**Comment by YOCKOW** [comment]
I believe this is not stale... so rebased.
(Or we should wait for [generalized "Collection Matchers"](https://bugs.swift.org/browse/SR-10662) suggested by @milseman?)

**Comment by spevans** [comment]
@swift-ci test

**Comment by YOCKOW** [comment]
@spevans Thank you for rerunning tests.

-----

The error seems to be unrelated.

<details>
<blockquote>
/home/buildnode/jenkins/workspace/swift-corelibs-foundation-PR-Linux/swift/validation-test/StdlibUnittest/RaceTest.swift:116:11: error: CHECK: expected string not found in input<br />
16:55:33 // CHECK: [ OK ] Race.closure  <br />
16:55:33           ^  <br />
16:55:33 <stdin>:17:1: note: scanning from here   <br />
16:55:33 stderr>>> CRASHED: SIGSEGV  <br />
16:55:33 ^  <br />
16:55:33 <stdin>:19:3: note: possible intended match here  <br />
16:55:33 [ FAIL ] Race.closure  <br />
16:55:33   ^  <br />
16:55:33   <br />
16:55:33 --  <br />
</blockquote>
</details>

**Comment by spevans** [comment]
@swift-ci test linux

**Comment by YOCKOW** [comment]
@spevans Thank you again. At last tests have passed.

**Comment by YOCKOW** [comment]
Finally [PR for SDK Overlay (swift#28639)](https://github.com/apple/swift/pull/28639) has been merged.
I expect this PR is also ready to be merged.

**Comment by juozasvalancius** [comment]
I've just discovered that the previous implementation also had bugs in the returned *length* of the range.
So it's probably a good idea to add tests for that too.

Here is a case that returns shorter range than the given input in Xcode 11.6 (11E708):

    import Foundation
    let data = Data([1, 2, 3, 4, 5, 6])
    let search = Data([2, 3, 9])
    data.firstRange(of: search, in: 0 ..< 5) // returns 1..<2, should be nil

**Comment by YOCKOW** [comment]
@juozasvalancius 
Thank you for the review.
The length is checked here https://github.com/apple/swift-corelibs-foundation/pull/2499/files#diff-593783312ec62e6e9299004a53468f83R865 and your case could be covered by https://github.com/apple/swift-corelibs-foundation/pull/2499/files#diff-593783312ec62e6e9299004a53468f83R892

**Comment by YOCKOW** [comment]
No conflicts even after the base branch was changed from `master` to `main`.

**Comment by YOCKOW** [comment]
Should this PR be alive? https://github.com/apple/swift-corelibs-foundation/pull/2915 was merged, though.

**Comment by YOCKOW** [comment]
Confirmation

* [PR for SDK Overlay (swift#28639)](https://github.com/apple/swift/pull/28639) was merged in Aug 2020. And now, [the commit exists in this scf repository](https://github.com/apple/swift-corelibs-foundation/commit/1cf2e3b51dd4979f2b385f0d9f51c68eee2f7220) as a result of [#2915](https://github.com/apple/swift-corelibs-foundation/pull/2915). It is the same implementation with this PR.
* [SR-10689](https://bugs.swift.org/browse/SR-10689) is not yet resolved on non-Darwin and will be resolved by this PR.
* All checks have passed, and this PR has no conflicts with `main` branch even now.
* ([#2993](https://github.com/apple/swift-corelibs-foundation/pull/2993) would resolve the same issue in the different way.)

-----
@millenomi Could you review this PR (and/or #2993) at your convenience?

**Comment by CodaFi** [comment]
@swift-ci test

**Comment by YOCKOW** [comment]
@CodaFi 
Thnak you for rerunning tests.
All tests have passed again.

**Comment by CodaFi** [comment]
I would like sign offs from some core maintainers here. 

@millenomi @spevans

**Comment by millenomi** [comment]
Done.

**Comment by YOCKOW** [comment]
@millenomi Thank you for your approval.

**Pull request merged**
