### PR TITLE
Add one more XCTAssert for isLeapMonth in TestDate.swift

### PR DESCRIPTION
**Pull request by lamtrinhdev**
`isLeapMonth` is a component in `Date`. Add one more XCTAssert for `isLeapMonth` in `test_recreateDateComponentsFromDate`.

### CODE REVIEW

**Comment by parkera** [comment]
We haven't traditionally always set this value (sometimes it is nil, depending on calendar). Is there something in particular we are trying to validate here?

**Comment by parkera** [comment]
@swift-ci test

**Comment by lamtrinhdev** [comment]
> We haven't traditionally always set this value (sometimes it is nil, depending on calendar). Is there something in particular we are trying to validate here?

Thank you for your review, @parkera . No particular, just see the test case that cover almost paramaters without it, and I would like to add it into test case.

**Comment by lamtrinhdev** [comment]
Dear @parkera ,

It seems `Swift Test macOS Platform` has the problem. I have observed some previous merged PRs that have also failed with the `Swift Test macOS Platform`.

Thanks,
Lam

**Pull request merged**
