### PR TITLE
Fix `String.getLineStart(_:end:contentsEnd:for:)` returns wrong start

### PR DESCRIPTION
**Pull request by norio-nomura**
https://bugs.swift.org/browse/SR-3366

### CODE REVIEW

**Comment by norio-nomura** [comment]
@phausler Could you please review this?

**Comment by norio-nomura** [comment]
Rebased

**Comment by phausler** [comment]
@swift-ci please test and merge

**Comment by norio-nomura** [comment]
Thanks! 🙏

**Pull request merged**
