### PR TITLE
FileManager.attributesOfItem(atPath:) - use statx() on Linux if available.

### PR DESCRIPTION
**Pull request by spevans**
- Linux kernel >= 4.11.0 has a statx() call for extended file stat
   information and this can be used to set .creationDate

### CODE REVIEW

**Comment by spevans** [comment]
@swift-ci test

**Comment by spevans** [comment]
@swift-ci test

**Comment by spevans** [comment]
@swift-ci test

**Comment by spevans** [comment]
@swift-ci test

**Comment by spevans** [comment]
@swift-ci test

**Comment by spevans** [comment]
@swift-ci test

**Comment by ianpartridge** [comment]
Looks good. Worth noting that this requires filesystem support too so kernel 4.11.0 probably isn't enough. I think ext4 got support pretty soon afterwards though.

**Comment by spevans** [comment]
Yeah, after reading your comment about ext4fs I realised I need to add a check of the `stx_mask` to make sure that `STATX_BTIME ` bit is set to make sure it is set in the result else ignore that field. All the other fields should be ok though.

**Comment by spevans** [comment]
@swift-ci test

**Comment by spevans** [comment]
@swift-ci test

**Comment by millenomi** [comment]
@spevans Willing to merge when not conflicted with master.

**Comment by spevans** [comment]
@swift-ci test

**Comment by spevans** [comment]
@swift-ci test

**Comment by spevans** [comment]
@swift-ci test

**Comment by spevans** [comment]
@millenomi Is this ok to go in now?

**Comment by millenomi** [comment]
@swift-ci please test

**Pull request merged**
