### PR TITLE
Parity: NSURL resource values.

### PR DESCRIPTION
**Pull request by millenomi**
Implement resource values at the Swift layer, leveraging the FileManager implementations and partially moving them closer to completion.

### CODE REVIEW

**Comment by millenomi** [comment]
@swift-ci please test

**Comment by millenomi** [comment]
@swift-ci please test

**Comment by millenomi** [comment]
Fixes https://bugs.swift.org/browse/SR-10365.

**Comment by spevans** [comment]
@swift-ci please test

**Comment by spevans** [comment]
@swift-ci test linux

**Comment by millenomi** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
This broke the Windows build!  `timeval` is not defined: https://dev.azure.com/compnerd/windows-swift/_build/results?buildId=1914

**Pull request merged**
