### PR TITLE
Parity: NSAttributedString

### PR DESCRIPTION
**Pull request by millenomi**
This implements:
 - encoding and decoding.
 - the partial ability to bridge NSAttributedString.Key to NSString as Darwin allows.

It also adds a new fixture generator and fixtures produced on macOS 10.14. The generator only works on Darwin for now.

Fixes https://bugs.swift.org/browse/SR-10387

### CODE REVIEW

**Comment by millenomi** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
Is there a SR for the linux/windows side?

**Comment by millenomi** [comment]
Of the fixture generator? No, but I need to write one.

**Comment by millenomi** [comment]
https://bugs.swift.org/browse/SR-10454

**Comment by millenomi** [comment]
cc @compnerd I added the change to SwiftSupport.cmake we discussed.

**Comment by millenomi** [comment]
@swift-ci please test

**Comment by millenomi** [comment]
@swift-ci please test

**Comment by millenomi** [comment]
@swift-ci please test

**Comment by millenomi** [comment]
@swift-ci please test

**Comment by millenomi** [comment]
@swift-ci please test

**Pull request merged**
