### PR TITLE
[Error] Implement `localizedDescription` using `_swift_Foundation_getErrorDefaultUserInfo`

### PR DESCRIPTION
**Pull request by ikesyo**
This should return an appropriate value instead of the fixed "The operation could not be completed".

### CODE REVIEW

**Comment by parkera** [comment]
@swift-ci please test and merge

**Comment by ikesyo** [comment]
@swift-ci please test

**Comment by parkera** [comment]
@ikesyo feel free to merge if you're ready

**Comment by ikesyo** [comment]
Thanks @parkera 

@swift-ci test and merge

**Pull request merged**
