### PR TITLE
Use macOS instead of OSX

### PR DESCRIPTION
**Pull request by AtariDreams**

### CODE REVIEW

**Comment by AtariDreams** [comment]
@Kyle-Ye This PR is for you!

**Review by parkera — APPROVED** [review]

**Comment by parkera** [comment]
@swift-ci test

**Comment by parkera** [comment]
We should be able to merge this.

**Comment by parkera** [comment]
@swift-ci test

**Comment by Kyle-Ye** [comment]
@swift-ci please test macOS

**Comment by AtariDreams** [comment]
Can we try this again?

**Comment by AtariDreams** [comment]
@parkera

**Comment by Kyle-Ye** [comment]
@swift-ci please test

**Comment by AtariDreams** [comment]
Oh wow this passed.

**Comment by AtariDreams** [comment]
@parkera thoughts?

**Comment by parkera** [comment]
Seems fine to me.

**Comment by parkera** [comment]
Looks like the Windows build is in progress now.

**Comment by ktoso** [comment]
All green - ready to merge @parkera ?

**Comment by parkera** [comment]
Thank you @AtariDreams !

**Pull request merged**
