### PR TITLE
Enable WMO for release builds

### PR DESCRIPTION
**Pull request by jmschonfeld**
This enables whole module optimization for Foundation, FoundationNetworking, and FoundationXML for release builds. We've found that this added optimization results in a significant performance improvements for FoundationEssentials (https://github.com/apple/swift-foundation/pull/832) and will be applying the same optimization to the SCL-F suite of libraries

### CODE REVIEW

**Comment by jmschonfeld** [comment]
https://github.com/apple/swift-foundation/pull/832

@swift-ci please test

**Review by glessard — APPROVED** [review]
🏎️

**Comment by jmschonfeld** [comment]
https://github.com/apple/swift-foundation/pull/832

@swift-ci please test

**Review by glessard — APPROVED** [review]

**Comment by jmschonfeld** [comment]
https://github.com/apple/swift-foundation/pull/832

@swift-ci please test

**Comment by jmschonfeld** [comment]
https://github.com/apple/swift-foundation/pull/832

@swift-ci please test Windows platform

**Comment by jmschonfeld** [comment]
https://github.com/apple/swift-foundation/pull/832

@swift-ci please test

**Comment by jmschonfeld** [comment]
https://github.com/apple/swift-foundation/pull/832

@swift-ci please test Windows platform

**Comment by jmschonfeld** [comment]
https://github.com/apple/swift-foundation/pull/832

@swift-ci please test Windows platform

**Pull request merged**
