### PR TITLE
SR-14108: Implement `copy()` in `DateFormatter`.

### PR DESCRIPTION
**Pull request by YOCKOW**
`DateFormatter.copy()` returns the same instance not a copied one so far.
This PR adds an implementation of `copy()` in `DateFormatter` to behave expectedly(i.e. The same behavior with DarwinFoundation).

Resolves [SR-14108](https://bugs.swift.org/browse/SR-14108).

### CODE REVIEW

**Comment by spevans** [comment]
@swift-ci test

**Comment by spevans** [comment]
@swift-ci test

**Comment by YOCKOW** [comment]
@spevans
Thank you for running tests.
The failure on macOS seems to be unrelated.

**Review by spevans — APPROVED** [review]
I ran the test under `DarwinCompatibiityTests` and it works fine on BigSur 1.4.4

**Comment by spevans** [comment]
@YOCKOW Its probably worth doing a back port of this 5.5 and 5.4 since its a bug fix.

**Comment by YOCKOW** [comment]
@spevans 
Thank you for approving.
I've opened PRs for 5.4/5.5:
- #3010
- #3011

**Pull request merged**
