### PR TITLE
Fix bug [SR-4391]: index check should be `||` instead of `&&`

### PR DESCRIPTION
**Pull request by rxwei**
Bug in NSOrderedSet index check

### CODE REVIEW

**Comment by alblue** [comment]
@swift-ci please test

**Comment by pushkarnk** [comment]
@swift-ci please test

**Comment by rxwei** [comment]
@parkera The case was already covered by `test_ObjectsAtIndexes`. I fixed another bug and added a test

**Comment by parkera** [comment]
@swift-ci please test and merge

**Pull request merged**
