### PR TITLE
build: remove the custom build system

### PR DESCRIPTION
**Pull request by compnerd**
Encouragement for people to move to CMake as the one build system for
Swift!

### CODE REVIEW

**Comment by gottesmm** [comment]
So beautiful...

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please clean test macOS platform

**Comment by compnerd** [comment]
CC: @millenomi

**Comment by millenomi** [comment]
As part of removing this, we *must* document how to build Core Foundation standalone, since the previous instructions I had relied on the old build system.

Do you have any indications on how to invoke CMake correctly to build CF with `CF_DEPLOYMENT_SWIFT` off?

**Comment by compnerd** [comment]
@millenomi - if you have the exact configuration you would like to build, I should be able to tweak the build to get that build working.

**Comment by spevans** [comment]
I think `Docs/GettingStarted.md` needs an update as to how to invoke the tests now that `ninja test` doesn't work since `build.ninja` is in the build directory.

**Comment by spevans** [comment]
@compnerd Now that there is a separate PR for updating the docs (#2657) do you want to resurrect this one and finally remove the old build system?

**Comment by compnerd** [comment]
Yeah, I can do that soonish.  Im neck deep in Foundation debugging right now, and don't want to page that out

**Comment by shahmishal** [comment]
The Swift project moved the default branch to `main` and deleted `master` branch, so GitHub automatically closed the PR. Please re-create pull request with main branch.

More detail about the branch update - https://forums.swift.org/t/updating-branch-names/40412

**Pull request closed without merging**
