### PR TITLE
SR-3052. Incorrect string result for String methods with non latin symbols

### PR DESCRIPTION
**Pull request by naithar**
Fixes Issue: https://bugs.swift.org/browse/SR-3052
Added tests that cover this issue. 
Implemented possible fix by providing correct UTF8-length for `_CFStringCreateByAddingPercentEncodingWithAllowedCharacters` and `_CFStringCreateByRemovingPercentEncoding`

Also switched to `CFStringGetLengthUTF8` method for string length where UTF-8 encoding is used.

### CODE REVIEW

**Comment by parkera** [comment]
Can we fix this issue without introducing a new length function for CFString? There is no "CFStringGetLengthUTF8" function on Darwin and I don't think we should introduce one. CFString has the `CFStringGetMaximumSizeForEncoding` function for dealing with differently-sized buffers when the string is encoded into something besides its native representation.

**Comment by naithar** [comment]
I'll look into this more. Thanks for the tip on `CFStringGetMaximumSizeForEncoding`.

**Comment by naithar** [comment]
@parkera updated fix. Tests is passing.

**Comment by parkera** [comment]
Thanks!

**Comment by parkera** [comment]
@swift-ci please test

**Comment by parkera** [comment]
Ok, don't know why the tests are stuck. Trying again.

**Comment by parkera** [comment]
@swift-ci please test

**Comment by naithar** [comment]
Looks like everything is ok now

**Pull request merged**
