### PR TITLE
Foundation: DCE `sliceRange` (NFC)

### PR DESCRIPTION
**Pull request by compnerd**
Remove unnecessary construction of `NSRange` and assignment to a
variable where the value was unused.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
CC: @phausler @millenomi @parkera

**Comment by phausler** [comment]
This will be subsumed by the import of Data I have from the overlay

**Comment by compnerd** [comment]
Seems like @phausler is already going to take care of this, I'm going to close it so I don't accidentally submit it.

**Pull request closed without merging**
