### PR TITLE
NSURL: Dont leak the result of dataRepresentation

### PR DESCRIPTION
**Pull request by spevans**
Validated with valgrind.

### CODE REVIEW

**Comment by ianpartridge** [comment]
Hmm there were a bunch of these `deallocator: .none` initializations added in https://github.com/apple/swift-corelibs-foundation/commit/188a4e17036f9b7c8f1012a175a0f85f648cd31c

Worth auditing them all?

**Comment by ianpartridge** [comment]
@swift-ci please test

**Comment by spevans** [comment]
I audited all of the `malloc()` and `bytesNoCopy:` calls, I will look at that commit and check the ` deallocator: .none`s

**Comment by spevans** [comment]
There was only one other use, in `XMLParser.swift`, and that has a `defer { free() }` after the `malloc` so I think it is all ok.

**Pull request merged**
