### PR TITLE
[Measurement] Group operators into just two extensions

### PR DESCRIPTION
**Pull request by ikesyo**
A follow up for #1349.

Once this is merged, I will sync the file with the overlay.

### CODE REVIEW

**Comment by ikesyo** [comment]
@swift-ci Please test

**Comment by alblue** [comment]
@swift-ci please test

**Comment by alblue** [comment]
Looks like the swift build is hosed at the moment:

```
/home/buildnode/jenkins/workspace/swift-corelibs-foundation-PR-Linux/swift/include/swift/Runtime/Config.h:109:39: note: expanded from macro 'SWIFT_CC_swift'
#define SWIFT_CC_swift __attribute__((swiftcall))
                                      ^
/home/buildnode/jenkins/workspace/swift-corelibs-foundation-PR-Linux/swift/unittests/runtime/Stdlib.cpp:89:1: warning: unknown attribute 'swiftcall' ignored [-Wunknown-attributes]
SWIFT_CC(swift) SWIFT_RUNTIME_STDLIB_INTERNAL
^
```

**Comment by ianpartridge** [comment]
@swift-ci please test

**Pull request merged**
