### PR TITLE
[NSKeyedArchiver] Implement init() and encodedData

### PR DESCRIPTION
**Pull request by broadwaylamb**

### CODE REVIEW

**Comment by parkera** [comment]
Looks good! Can we get a simple test case too?

**Comment by broadwaylamb** [comment]
@parkera please can you take a look?

**Comment by parkera** [comment]
@swift-ci please test and merge

**Comment by parkera** [comment]
Great, thanks!

**Comment by broadwaylamb** [comment]
@parkera seems like something's wrong with the build.

**Comment by parkera** [comment]
Hm let's try again...

**Comment by parkera** [comment]
@swift-ci please test and merge

**Comment by shahmishal** [comment]
@swift-ci please test and merge

**Pull request merged**
