### PR TITLE
[cmake] Fix capitalization in find_path argument.

### PR DESCRIPTION
**Pull request by drodriguez**
/cc @compnerd

### CODE REVIEW

**Comment by drodriguez** [comment]
Since I removed the duplicated script in #1746, I suppose this is the only change needed. But if you want the duplicated script, I can duplicate this change easily.

**Comment by compnerd** [comment]
@swift-ci please test and merge

**Comment by drodriguez** [comment]
The failure seems unrelated to this changes. I think I have seen the same test failing in another completely unrelated PR. Can we restart the tests? Thanks.

**Comment by milseman** [comment]
@swift-ci please test and merge

**Pull request merged**
