### PR TITLE
Update from deprecated .withUnsafeBytes

### PR DESCRIPTION
**Pull request by spevans**
- use `withUnsafeBytes<R>(_: (UnsafeRawBufferPointer) throws -> R) rethrows -> R` instead

### CODE REVIEW

**Comment by spevans** [comment]
@swift-ci test

**Comment by millenomi** [comment]
Is this correct? I'm pretty sure you shouldn't bind memory you are not the owner of. @phausler?

**Comment by spevans** [comment]
@swift-ci test

**Comment by spevans** [comment]
@swift-ci test linux

**Comment by spevans** [comment]
@swift-ci test linux

**Pull request merged**
