### PR TITLE
Use bundled UUID

### PR DESCRIPTION
**Pull request by compnerd**
Setup the build to build the bundled UUID and port to windows in preparation for supporting Windows as a build target.

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
CC: @millenomi @parkera

**Comment by jakepetroules** [comment]
Why not just use [CoCreateGuid](https://docs.microsoft.com/en-us/windows/desktop/api/combaseapi/nf-combaseapi-cocreateguid) instead of adding the libuuid dependency?

**Comment by compnerd** [comment]
@jakepetroules - because there are auxiliary functions here that need to be re-implemented then.  The conversion to from string can be done using Win32 APIs, but, it seems that if we do this, we can avoid the dependency on e2fsprogs on Linux as well.  Its a pretty tiny code base, already here, and means that all the ports have the same code base.

**Pull request merged**
