### PR TITLE
Reimplement OperationQueue similar to Objective-C Foundation

### PR DESCRIPTION
**Pull request by andriydruk**
# Motivation
The current implementation of OperationQueue work in a different way to Objective-C Foundation.
There are some deadlocks and unexpected behavior but the biggest problem is stopping on semaphore during waiting for other operations in a queue.

https://github.com/apple/swift-corelibs-foundation/blob/master/Foundation/Operation.swift#L441

In application with high loads on OperationQueue it leads to spending time on semaphors and blocking all libdispatch.

Example:
> Let's create OperationQueue1 with maxConcurrentOperationCount == 2 and put 1000 operations to this queue. 
> ER: OperationQueue1 will get 2 threads from pool and use them to do 1000 operations one by one. Any other OperationQueue or DispatchQueue works properly
> AR: OperationQueue1 will post 1000 DispatchWorkItem and start waiting on sempahors at 998 threads *(probably it will be 64 or other limitation from libdspatch)* that block any other OperationQueue2 or DispatchQueue

# Changes
**First Commit:** add tests that fail on old implementation and pass on Objective-C Foundation 
*(I don't know how to run tests from this repo on Objective-C Foundation, that's why I locally created a separated project for that purpose)*

**Second Commit:** rewrite OperationQueue from scratch and try to copy Objective-C Foundation behavior as much as possible.

### CODE REVIEW

**Comment by ianpartridge** [comment]
cc: @phausler

**Comment by zayass** [comment]
> Third: little known fact - operations can have dependencies across queues.

This case should be covered https://github.com/apple/swift-corelibs-foundation/pull/1858/files#diff-0a359ab91a67f2ac00f668f57be56f3cR259

**Comment by zayass** [comment]
Hi @phausler can you look into this? 
Looks like all mentioned "specs" already implemented.

**Comment by Frizlab** [comment]
Any news on this? I’m heavily using `Operation`s on a server and current queue implementation is very broken in Swift 5.1.*…

**Comment by shahmishal** [comment]
The Swift project moved the default branch to `main` and deleted `master` branch, so GitHub automatically closed the PR. Please re-create pull request with main branch.

More detail about the branch update - https://forums.swift.org/t/updating-branch-names/40412

**Pull request closed without merging**
