### PR TITLE
[SR-6785] Fix `Decimal` conformance to `Strideable`

### PR DESCRIPTION
**Pull request by xwu**
Consider the following discrepancy:

```swift
import Foundation

let x: Int = 42
x.distance(to: 43) // 1
let y: Decimal = 42
y.distance(to: 43) // -1 (oops!)
```

The implementation of `distance(to:)` is incorrect for `Decimal`. This PR corrects the implementation (for both the overlay and swift-corelibs) and adds corresponding tests.

Resolves [SR-6785](https://bugs.swift.org/browse/SR-6785).

### CODE REVIEW

**Comment by xwu** [comment]
@swift-ci test

**Comment by xwu** [comment]
@swift-ci test

**Comment by xwu** [comment]
@swift-ci test Linux

**Comment by xwu** [comment]
@swift-ci test Linux

**Comment by xwu** [comment]
Ugh

@swift-ci please clean test Linux

**Comment by xwu** [comment]
@swift-ci please clean test Linux

**Comment by xwu** [comment]
@swift-ci please test Linux

**Comment by xwu** [comment]
@swift-ci test

**Review by spevans — APPROVED** [review]

**Pull request merged**
