### PR TITLE
Fix memory leak in CFBundle_Executable.c

### PR DESCRIPTION
**Pull request by valeriyvan**

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
Please add a better commit message than 'Fix memory leak'.  How was this detected?  What scenarios did it occur under?  Seems like this is the non-Windows Swift path, which means that Darwin would not be impacted?

**Review by compnerd — CHANGES_REQUESTED** [review]
The commit message should be reworked.

**Comment by valeriyvan** [comment]
> Please add a better commit message than 'Fix memory leak'. How was this detected? What scenarios did it occur under? Seems like this is the non-Windows Swift path, which means that Darwin would not be impacted?

Found with Xcode static analyser.
On line 85 call `CFURLCreateWithFileSystemPathRelativeToBase` returns object with +1 retain count according to [Create rule](https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFMemoryMgmt/Concepts/Ownership.html#//apple_ref/doc/uid/20001148-103029).

**Comment by MaxDesiatov** [comment]
> Found with Xcode static analyser.
> On line 85 call `CFURLCreateWithFileSystemPathRelativeToBase` returns object with +1 retain count according to [Create rule](https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFMemoryMgmt/Concepts/Ownership.html#//apple_ref/doc/uid/20001148-103029).

This should be added to the commit message, not a PR comment which will be lost after merge.

Personally, I would prefer it as a comment at the appropriate location in the code.

**Comment by compnerd** [comment]
@valeriyvan yes, I was able to infer that from reading the code (the path that leaked the CFURL) - but that information belongs in the commit message so that someone going through the history doesn't need to reconstruct every bit of detail from the diff.

**Comment by valeriyvan** [comment]
> Personally, I would prefer it as a comment at the appropriate location in the code.

File `CFBundle_Executable.c` has 46 calls of `CFRelease`. No-one is commented. Why exactly this one should be commented? This is trivial bug. Someone just forgotten that retained object should be released. I don't see any reason why this call of CFRelease deserves to be commented.

**Comment by valeriyvan** [comment]
> The commit message should be reworked.

Updated commit message

**Review by compnerd — APPROVED** [review]
Might be nice to actually follow git suggestions for formatting commit messages.

**Comment by valeriyvan** [comment]
> Might be nice to actually follow git suggestions for formatting commit messages.

Fixed commit message.

**Comment by MaxDesiatov** [comment]
@swift-ci please test

**Pull request merged**
