### PR TITLE
Tests: convert some assertions into XCTest forms

### PR DESCRIPTION
**Pull request by compnerd**
Use the `XCTAssert*` helpers to validate the state to get proper diagnostics emitted for test failures.  This should help debugging failures.

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @parkera

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by parkera** [comment]
Thanks, LGTM.

**Pull request merged**
