### PR TITLE
Cherry pick: Make Date, DateComponents and DateInterval Sendable

### PR DESCRIPTION
**Pull request by FranzBusch**

### CODE REVIEW

**Comment by FranzBusch** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by FranzBusch** [comment]
@compnerd @shahmishal I think the macOS CI is broken. It was already broken for the 5.9 release itself and we merged over it in my previous PR as well: https://github.com/apple/swift-corelibs-foundation/pull/4789

**Review by ktoso — APPROVED** [review]

**Comment by ktoso** [comment]
Approved but can you give the PR a better title? :)

**Comment by compnerd** [comment]
Seeing something similar on other branches, I think that it might be wisest to go ahead and merge this for 5.9.1 (macOS builds of swift-corelibs-foundation are not for release purposes).

**Review by compnerd — APPROVED** [review]

**Pull request merged**
