### PR TITLE
FileManager: Add missing replaceItemAt(_:withItemAt:backupItemName:options:)

### PR DESCRIPTION
**Pull request by spevans**
- This just wraps replaceItem(at:withItemAt:backupItemName:options:)

### CODE REVIEW

**Comment by spevans** [comment]
@swift-ci test linux

**Comment by spevans** [comment]
I was looking at https://developer.apple.com/documentation/foundation/filemanager/2293212-replaceitemat

It also autocompletes in Xcode playgrounds unless Im missing something obvious?

**Comment by millenomi** [comment]
My bad, you're correct. Thanks for picking this up.

**Comment by millenomi** [comment]
@swift-ci please test

**Pull request merged**
