### PR TITLE
[5.4] Process: Adapt #2928 for Android

### PR DESCRIPTION
**Pull request by buttaface**
This is a cherry-pick of be83f8d from the main branch. It is completely safe as it only reorganizes the code for Android and changes nothing on non-Android.

### CODE REVIEW

**Comment by tomerd** [comment]
@swift-ci test

**Comment by spevans** [comment]
FYI this PR is against the 5.4 branch, not 5.3

**Comment by spevans** [comment]
@swift-ci test

**Comment by buttaface** [comment]
Can run the CI again and merge?

**Comment by spevans** [comment]
@swift-ci test

**Comment by buttaface** [comment]
Thanks, one less patch for me to maintain separately otherwise.

**Pull request merged**
