### PR TITLE
Fixbug, BlockOperation addExecutionBlock

### PR DESCRIPTION
**Pull request by dannliu**
Steps:
1.Create BlockOperation with an init block.
2.Add another one with addExecutionBlock.
3.Access the executionBlocks property, it contains 3 blocks.

### CODE REVIEW

**Comment by spevans** [comment]
@swift-ci test

**Comment by lxbndr** [comment]
Looks useful. Provided test case still fails without a fix. And fixed code behaves as expected. @spevans Is there a chance to merge this?

**Comment by MaxDesiatov** [comment]
This should target the `main` branch and needs conflicts to be resolved.

**Comment by lxbndr** [comment]
@dannliu Are you still interested working on this?

**Comment by millenomi** [comment]
@phausler for review?

**Comment by shahmishal** [comment]
The Swift project moved the default branch to `main` and deleted `master` branch, so GitHub automatically closed the PR. Please re-create pull request with main branch.

More detail about the branch update - https://forums.swift.org/t/updating-branch-names/40412

**Pull request closed without merging**
