### PR TITLE
Move the size check to be the first thing checked in CFAllocator functions

### PR DESCRIPTION
**Pull request by AtariDreams**
This saves us a lot of work is size is 0

### CODE REVIEW

**Review by parkera — APPROVED** [review]

**Comment by AtariDreams** [comment]
It saves some work @parkera

**Comment by AtariDreams** [comment]
Any update on this @parkera

**Review by parkera — APPROVED** [review]

**Comment by AtariDreams** [comment]
@parkera Can we try this one more time?

**Comment by parkera** [comment]
@swift-ci test

**Comment by AtariDreams** [comment]
@parkera I apologize. I did not account for the malloc_zone tests. That has been fixed. Can we try one more time?

**Comment by AtariDreams** [comment]
@parkera this passed!

**Pull request merged**
