### PR TITLE
CFString alternatives for tests

### PR DESCRIPTION
**Pull request by compnerd**

### CODE REVIEW

**Comment by spevans** [comment]
What is the rationale for removing some of the `CFString...` calls?

**Comment by compnerd** [comment]
`CF*` APIs are not supposed to be exposed, but, were accidentally exposed on Linux.  This clean up is required for Windows which properly completely obscures all CoreFoundation access.  The result is that the CoreFoundation APIs are unavailable for the tests unless they are in the header.  Alternatively, I suppose, the tests could link their own copy of CoreFoundation, but, it seemed that @millenomi was in favour of migrating to the use of the Foundation APIs for testing as long as the test still made sense.

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by millenomi** [comment]
@swift-ci please test and merge

**Pull request merged**
