### PR TITLE
Move the SWIFT_INDEX_STORE_ENABLE down to the project level instead of target level

### PR DESCRIPTION
**Pull request by phausler**

### CODE REVIEW

**Comment by phausler** [comment]
@swift-ci please test

**Comment by alblue** [comment]
@phausler this looks like a good change but needs rebasing - can you resubmit?

**Comment by alblue** [comment]
@phausler Can you rebase and resubmit this if needed?

**Comment by alblue** [comment]
@phausler I'm assuming this is either no longer required or will be rebased/resubmitted later, and since we have conflicts that prevent the pull request moving forwards at this stage I'm going to close it down. We can always re-open it and update the changes when needed in future.

**Pull request closed without merging**
