### PR TITLE
CMake based build

### PR DESCRIPTION
**Pull request by compnerd**
These set of changes are needed to build with the CMake system.

### CODE REVIEW

**Comment by compnerd** [comment]
@millenomi - the underlying CF changes that can be done are in a separate PR (that should go in first).  The Foundation side of the changes I expect will require the CF to be built as a framework (which is part of what I did in the CMake based build).  Once the base CF changes are in, I will rebase this.

The hack for plutil I haven't figured out why the type of doesn't work.  After that, I am going to try to switch over the Foundation build to CMake :-)

**Comment by spevans** [comment]
With the CMake build, will `libFoundation.a` still be built? I notice that after `swift-corelibs-xctest` and `swift-corelibs-libdispatch` were switched over to CMake, the respective  static libraries stopped being built and I was hoping that wouldn't be the case for Foundation (and eventually the other two can be fixed as well).

**Comment by compnerd** [comment]
@spevans, sure, passing `-DBUILD_SHARED_LIBS=NO` will generate a static library.  Updating build-script to do two builds will allow the distributions to have the static builds.

**Comment by compnerd** [comment]
Please test with following PRs:
apple/swift#20032
apple/swift-llbuild#388
apple/swift-package-manager#1833
apple/swift-llvm#121
apple/swift-corelibs-xctest#230

@swift-ci please test Linux platform

**Comment by compnerd** [comment]
Please test with following PRs:
apple/swift#20032
apple/swift-llbuild#388
apple/swift-package-manager#1833
apple/swift-corelibs-xctest#230

@swift-ci please test Linux platform

**Pull request merged**
