### PR TITLE
Process: Match Darwin more closely for handling of .currentDirectoryPath and .currentDirectoryURL

### PR DESCRIPTION
**Pull request by spevans**
- Fix compile error on Windows when using .currentDirectoryURL

#2525 Broke compiling on windows, this should fix it.

### CODE REVIEW

**Comment by spevans** [comment]
@swift-ci test

**Comment by spevans** [comment]
@compnerd please test windows 😀

**Comment by spevans** [comment]
@swift-ci test linux

**Comment by compnerd** [comment]
@spevans haha

**Comment by compnerd** [comment]
https://dev.azure.com/compnerd/windows-swift/_build/results?buildId=12560&view=results

**Comment by compnerd** [comment]
Okay, this definitely fixes the Windows build as per the CI run above.

**Pull request merged**
