### PR TITLE
[5.2] SR-13015: Decimal calculation incorrect on Linux

### PR DESCRIPTION
**Pull request by buttaface**
From #2827, see explanation there.

### CODE REVIEW

**Comment by spevans** [comment]
@swift-ci test

**Comment by buttaface** [comment]
The tests didn't run?

**Comment by spevans** [comment]
cc @millenomi

**Comment by buttaface** [comment]
macOS failure is unrelated, linux passes.

**Comment by ktoso** [comment]
AFAIK we're waiting on the macOS Swift CI to be updated with the latest toolchain, I believe this is going to be solved soon but don't have an estimate for it.

**Comment by spevans** [comment]
@swift-ci test macos

**Comment by buttaface** [comment]
Is someone working on getting the macOS CI going with this branch again? If not, maybe the macOS CI can be ignored, if 5.2.5 will be another linux-only release like 5.2.3.

**Comment by drexin** [comment]
@swift-ci test 5.2 macos

**Comment by buttaface** [comment]
macOS CI didn't get command?

**Comment by drexin** [comment]
@swift-ci test 5.2 macos

**Pull request merged**
