### PR TITLE
Fix typo in DateFormatter method dateFormat:fromTemplate

### PR DESCRIPTION
**Pull request by njuri**

### CODE REVIEW

**Comment by ianpartridge** [comment]
Surprisingly this is actually wrong on Darwin too: https://developer.apple.com/documentation/foundation/dateformatter/1408112-dateformat

As we try to match Darwin as closely as possible I don't think we should change this.

**Comment by spevans** [comment]
Might require @parkera to do another documentation fix first.

**Comment by parkera** [comment]
This is the internal name so it should be fine to change it. I'll just fix it up in the Foundation header for a future release.

**Comment by parkera** [comment]
Ah, now I remember why it is spelled this way. I believe it was an Objective-C++ compatibility hack, as `template` is a reserved keyword.

**Comment by alblue** [comment]
@parkera so do we want to close this, or would changing to a different name (e.g. `tmplt`) make sense?

**Comment by parkera** [comment]
Let's just leave this as-is.

**Pull request closed without merging**
