### PR TITLE
Revert "[Attempt 2] Implement FileManager.url{s,}(for:…) and NSSearchPathForDirectoriesInDomains."

### PR DESCRIPTION
**Pull request by rudkx**
Reverts apple/swift-corelibs-foundation#1597

The CI builders are broken and this blocks PR testing.

### CODE REVIEW

**Comment by rudkx** [comment]
@swift-ci Please test

**Comment by shahmishal** [comment]
Merged to unblock CI

**Comment by rudkx** [comment]
@shahmishal Thanks Mishal!

**Comment by millenomi** [comment]
Please cc me on reverts in the future.

**Comment by millenomi** [comment]
@shahmishal @rudkx Do we have examples of breakage so I can fix this? This patch is highly desired.

**Comment by millenomi** [comment]
I have found it at https://ci.swift.org/job/oss-swift-package-linux-ubuntu-16_04/1774/consoleFull#10090894603122a513-f36a-4c87-8ed7-cbc36a1ec144

**Comment by rudkx** [comment]
@millenomi Thanks for the reminder on cc'ing. I was assuming a notification would be sent due to the reference to the other PR.

**Pull request merged**
