### PR TITLE
Revert "Implements URLSessionWebSocketTask"

### PR DESCRIPTION
**Pull request by compnerd**
Reverts apple/swift-corelibs-foundation#4643

This breaks the Windows build: https://ci-external.swift.org/job/swift-PR-build-toolchain-windows/272/

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
CC: @pseligman

**Comment by pseligman** [comment]
Thanks for the heads up.  Based on the error, I suspect this will be a quick patch.  Any instructions how to kick off a Windows build to test any changes?

**Comment by pseligman** [comment]
I'd like to propose we roll forward with a fix, rather than roll-back and re-attempt.  The patch is straightforward, I'm just unclear how best to validate it resolves the windows build:

`diff --git a/Sources/FoundationNetworking/URLSession/URLSessionTask.swift b/Sources/FoundationNetworking/URLSession/URLSessionTask.swift
index b3a731b7..1d42f234 100644
--- a/Sources/FoundationNetworking/URLSession/URLSessionTask.swift
+++ b/Sources/FoundationNetworking/URLSession/URLSessionTask.swift
@@ -754,7 +754,9 @@ open class URLSessionWebSocketTask : URLSessionTask {
                             pongReceiveHandler(error)
                         }
                     } else {
-                        pongReceiveHandler(POSIXError(.ENOTCONN))
+                        let disconnectedError = URLError(_nsError: NSError(domain: NSURLErrorDomain,
+                                                                           code: NSURLErrorNetworkConnectionLost))
+                        pongReceiveHandler(disconnectedError)
                     }
                 }
             }
@@ -782,7 +784,8 @@ open class URLSessionWebSocketTask : URLSessionTask {
             
             self.closeCode = code
             self.closeReason = reason
-            self.taskError = POSIXError(.ENOTCONN)
+            self.taskError = URLError(_nsError: NSError(domain: NSURLErrorDomain,
+                                                        code: NSURLErrorNetworkConnectionLost))
             self.closeMessage = (code, reason ?? Data())
             self.doPendingWork()
         }
`

**Comment by pseligman** [comment]
Hopefully we can leave the WebSocketTask support in place, and instead fix the Windows build.  See PR #4661 .  Apologies for not previously testing a Windows build, I was unaware swift-ci could do so.  #4661 should include the magic incantation to kick one off.

**Comment by compnerd** [comment]
This repository doesn't support that and needs to be kicked off from the swift repo.  However, @CodaFi happened to do that in apple/swift#62145 which verified that it does fix it.  Closing in favour of #4661.

**Pull request closed without merging**
