### PR TITLE
Modify NSCharacterSet api defined in NSURL file to align with that of Darwin version.

### PR DESCRIPTION
**Pull request by mamabusi**

### CODE REVIEW

**Comment by mamabusi** [comment]
After rebasing the changes to the latest master, I see that most of the changes were already put in. Only a few comment lines and the TestFoundation's test names are seen to have the older api names.This PR currently modifies those names.

**Comment by parkera** [comment]
Cool, let's give this a spin.

**Comment by parkera** [comment]
@swift-ci please test

**Comment by mamabusi** [comment]
@parkera The Build failure looks unrelated to the changes here. Could you please shed more light on this.

**Pull request merged**
