### PR TITLE
[SE-0121] remove use of optional comparison operators

### PR DESCRIPTION
**Pull request by jtbandes**
Found another. These things are out to get me.  for https://github.com/apple/swift/pull/3637

### CODE REVIEW

**Comment by jtbandes** [comment]
@parkera Can I bother you for another CI run?

**Comment by parkera** [comment]
@swift-ci please test

**Comment by jtbandes** [comment]
@ddunbar Any idea what this failure means? I think it's coming from the package manager:

https://ci.swift.org/job/swift-corelibs-foundation-PR-Linux/142/console
>
Test Case 'GitRepositoryTests.testProvider' started at 21:21:54.891
Cloning /tmp/spm-tests-testProvider().IEkqjp/test-repo
fatal: Needed a single revision
error:  Git 2.0 or higher is required. Please update git and retry

**Comment by ddunbar** [comment]
No, it is a real failure which has been reverted.

**Comment by moiseev** [comment]
@swift-ci please test

**Comment by moiseev** [comment]
Build failure looks unrelated.
@parkera can we proceed and merge? As this one is blocking https://github.com/apple/swift/pull/3637

**Comment by moiseev** [comment]
Master builds are failing with the same error.

**Comment by moiseev** [comment]
@swift-ci Please test and merge

**Comment by jtbandes** [comment]
@moiseev still seems like a probably unrelated failure?

**Pull request merged**
