### PR TITLE
build: correct the `DT_SONAME`

### PR DESCRIPTION
**Pull request by compnerd**
When ninja is invoked from a subdirectory it will convert the path to a
relative path, and that resulted in incorrect test results.  This
ensures that we get the correct soname.

### CODE REVIEW

**Comment by millenomi** [comment]
@swift-ci please test Linux

**Comment by aciidb0mb3r** [comment]
I've tested that this patch fixes the issue.

**Comment by millenomi** [comment]
The failure appears unrelated.

**Comment by millenomi** [comment]
@swift-ci please test Linux

**Comment by millenomi** [comment]
If we have another unrelated error, I'll ask @shahmishal to force-merge.

**Pull request merged**
