### PR TITLE
[SR-7715] [Foundation] FileManager.DirectoryEnumeration converted to generic class to iterate Path(String) and URL types.

### PR DESCRIPTION
**Pull request by karthikkeyan**
Bug Link:
https://bugs.swift.org/browse/SR-7715

Discussion link: 
https://forums.swift.org/t/sr-7715-filemanager-directoryenumerator-from-enumerator-atoptions-enumerates-any-instead-of-url/20051

- `FileManager.DirectoryEnumeration` confirmed with `Sequence` protocol.
- `FileManager.DirectoryEnumeration` is no longer the subclass of `NSEnumerator`, which gives the class the flexibility to be a generic type class.
- `FileManager.DirectoryEnumeration` contains a `nextObject()` method with a generic return type, which should be overridden by all sub-classes.
- `NSPathDirectoryEnumerator` internal class is a subclass of `DirectoryEnumeration<String>` with generic type `String` as it returns a path
- `NSURLDirectoryEnumerator` internal class is a subclass of `DirectoryEnumeration<URL>` with generic type URL since it returns a file url.

url

path

### CODE REVIEW

**Comment by karthikkeyan** [comment]
@spevans @parkera   Please give me your feedback when you guys get a chance. 

I guess I tagged you guys correctly, as I have seen you two are actively involved in PR reviews. If not my apologies, hope I didn't spam you guys.

**Comment by millenomi** [comment]
We can't change this. One of the primary goals of s-c-f is full source compatibility with Darwin, and Darwin's type is a `NSEnumerator`, which enumerates over `Any`.

The feedback is appreciated, though.

**Comment by karthikkeyan** [comment]
@millenomi Thanks for looking in my PR. 

Sorry Im new to this process, Where do we go from here, do I have to close this PR? or wait till we reach the point to update `NSEnumerator`'s interface?

**Comment by parkera** [comment]
We'll take this feedback into consideration for future Foundation API. I agree that the enumerator methods are not ideal in Swift vs their utility in ObjC.

**Comment by parkera** [comment]
The challenge with taking this change as-is would be that our existing clients using this API would suddenly fail to compile, which is an experience we're trying really hard to avoid. That's frustrating to have happen to you.

**Comment by parkera** [comment]
Thank you for the work here!

**Comment by karthikkeyan** [comment]
@parkera  Thanks Tony, for looking into my PR.

**Pull request closed without merging**
