### PR TITLE
Foundation: clear up some unused return value warnings

### PR DESCRIPTION
**Pull request by compnerd**
This just cleans up a set of unused-return-value warnings in the Foundation
implementation.  NFC.

### CODE REVIEW

**Comment by modocache** [comment]
@swift-ci please test

**Comment by parkera** [comment]
@swift-ci please test

**Comment by phausler** [comment]
Some of these are actually hiding potential errors or error handling. I am actually very surprised that the glibc functions are being imported with a warning (since they are not annotated with `__attribute__((warn_unsed_result))`. I was under the assumption that swift functions were now by default with this warning, but un-annotated methods imported from external languages (objc/c) were suppressed.

**Comment by compnerd** [comment]
I agree that error checking would be good (e.g. on stat).  However, this is maintaining the status quo.  I think that we should figure out which of these are interesting cases to error check and then do that in a follow up change.

**Pull request merged**
