### PR TITLE
[4.2] JSONEncoder overlay changes (#1561)

### PR DESCRIPTION
**Pull request by ianpartridge**
Cherry-pick of 24e43de9ed5006c5939108db1249584f484b61eb to `swift-4.2-branch`.

### CODE REVIEW

**Comment by ianpartridge** [comment]
@swift-ci please test

**Comment by ianpartridge** [comment]
@parkera if you're happy with this please merge.

**Comment by ianpartridge** [comment]
@parkera any thoughts?

**Comment by parkera** [comment]
Sorry about that, got lost while I was out on vacation.

**Comment by ianpartridge** [comment]
No problem, thanks.

**Pull request merged**
