### PR TITLE
[4.2] [test] Drop stdlib-redundant tests

### PR DESCRIPTION
**Pull request by milseman**
4.2 cherrypick of https://github.com/apple/swift-corelibs-foundation/pull/1492

### CODE REVIEW

**Comment by milseman** [comment]
@swift-ci please test

**Comment by milseman** [comment]
@parkera @phausler same for this cherry pick

**Comment by milseman** [comment]
@shahmishal @aschwaighofer this might be needed to unbreak CI Linux. Hoping to get a LGTM from @parker, but worse case we merge to unbreak CI, he can revert, and I’ll have to bring 🍻🍺 to apologize

**Comment by shahmishal** [comment]
Merged to unblock CI

**Pull request merged**
