### PR TITLE
basic implementation for NSURLResponse init and tests

### PR DESCRIPTION
**Pull request by cullenbmacdonald**

### CODE REVIEW

**Comment by cullenbmacdonald** [comment]
Does this look ok or should we swap the interface to use `public let`?

**Comment by phausler** [comment]
looks good to me; after seeing the style of public private(set), I think perhaps it might be something we should adopt in places that don't have side effects or locks instead of using ivars

**Comment by cullenbmacdonald** [comment]
Cool. So are you saying that this is the right implementation here?

**Comment by phausler** [comment]
yea - it seems like a pretty reasonable pattern in many cases (not just this one)

**Pull request merged**
