### PR TITLE
Swift 3 API Parity:  Data & NSData

### PR DESCRIPTION
**Pull request by michael-lehew**
Brings the Data and NSData API in s-cl-f to match the public version of Swift3 on Darwin. Reorganizes the implementation of Data/NSData to be a bit saner (versus somewhat vestigially matching the Objective-C categories on Darwin).  Also brings a whole host of tests over from our overlay (some disabled for now, since the real focus of this PR is the API parity, which we should have now).

### CODE REVIEW

**Comment by michael-lehew** [comment]
@swift-ci please test and merge

**Comment by michael-lehew** [comment]
@swift-ci please test

**Comment by michael-lehew** [comment]
@swift-ci please test

**Comment by michael-lehew** [comment]
@swift-ci please test and merge

**Comment by michael-lehew** [comment]
@swift-ci Please test and merge.

**Comment by michael-lehew** [comment]
I suppose I needed to say it with feeling. :)

**Comment by itaiferber** [comment]
@michael-lehew On stuff like https://github.com/apple/swift-corelibs-foundation/pull/567, I feel like saying "@swift-ci Okay, once more with vigor" :)

**Comment by michael-lehew** [comment]
@swift-ci Please test and merge

**Comment by michael-lehew** [comment]
Unclear what the failure reason was -- remediation is to have it actually run

**Pull request merged**
