### PR TITLE
Changes type avoiding undefined behaviour shifting left negative value in CFTimeZone

### PR DESCRIPTION
**Pull request by valeriyvan**

### CODE REVIEW

**Comment by spevans** [comment]
@swift-ci test

**Comment by valeriyvan** [comment]
> Does this need a `return (uint32_t)result` to cast the result to the correct return type ?

No. Implicit cast from unsigned to signed of same size in not undefined behaviour. It is implementation-defined. Which means different compilers might legitimately do this differently.

We could add explicit cast to make intention clear. But anyway, it stays implementation-defined.

**Comment by spevans** [comment]
@swift-ci test

**Comment by spevans** [comment]
@swift-ci test

**Comment by spevans** [comment]
@swift-ci test macos

**Comment by spevans** [comment]
@swift-ci test and merge

**Pull request merged**
