### PR TITLE
SR-10717: `var kind: XMLNode.Kind { get }` should return a correct value on Linux.

### PR DESCRIPTION
**Pull request by YOCKOW**
As shown below, some kinds of nodes return incorrect values as `var kind: XMLNode.Kind`. This PR fixes the issue.

```Swift
print((XMLNode.processingInstruction(withName: "name", stringValue: "value") as? XMLNode)?.kind == .processingInstruction)
// -> Prints "true" on macOS.
// -> Prints "false" on Linux.

print((XMLNode.comment(withStringValue: "comment") as? XMLNode)?.kind == .comment)
// -> Prints "true" on macOS.
// -> Prints "false" on Linux.

print((XMLNode.text(withStringValue: "text") as? XMLNode)?.kind == .text)
// -> Prints "true" on macOS.
// -> Prints "false" on Linux.

print(XMLDTDNode(xmlString: #"<!NOTATION f SYSTEM "F">"#)?.kind == .notationDeclaration)
// -> Prints "true" on macOS.
// -> Prints "false" on Linux.
```

Resolves [SR-10717](https://bugs.swift.org/browse/SR-10717).

### CODE REVIEW

**Comment by millenomi** [comment]
@swift-ci please test

**Comment by YOCKOW** [comment]
Is [the failure on Linux](https://ci.swift.org/job/swift-corelibs-foundation-PR-Linux/3073/consoleFull#19329390313122a513-f36a-4c87-8ed7-cbc36a1ec144) caused by this fix...?

**Comment by spevans** [comment]
The build failure is unrelated to this fix.

**Comment by spevans** [comment]
@swift-ci test

**Comment by YOCKOW** [comment]
[Another error](https://ci.swift.org/job/swift-corelibs-foundation-PR-Linux/3085/consoleFull#-3958888243122a513-f36a-4c87-8ed7-cbc36a1ec144) again.
By the way, can't anyone trigger "@swift-ci test"?

**Comment by spevans** [comment]
@swift-ci test linux

**Comment by spevans** [comment]
@YOCKOW See https://github.com/apple/swift/blob/master/docs/ContinuousIntegration.md#swift-ci about having access to trigger CI requests.

**Comment by YOCKOW** [comment]
@spevans 
Thank you for the answer, and please forgive me for having overlooked the document.

**Comment by spevans** [comment]
@swift-ci test linux

**Comment by YOCKOW** [comment]
It seems ready to be merged, or requires another review?

**Comment by YOCKOW** [comment]
Thank you for taking your valuable time.
It seems ready to be merged, or requires another review?

**Pull request merged**
