### PR TITLE
[NSThread] Updated to match Darwin version

### PR DESCRIPTION
**Pull request by damuellen**

### CODE REVIEW

**Comment by parkera** [comment]
@swift-ci please test

**Comment by parkera** [comment]
Looks good - let's make sure we don't break XCTest or swiftpm with a name change.

**Comment by parkera** [comment]
Looks like we need to update NSXMLParser as well:

```
Foundation/NSXMLParser.swift:463:40: error: cannot call value of non-function type 'Thread'
        if let current = Thread.current().threadDictionary["__CurrentNSXMLParser"] {
                         ~~~~~~~~~~~~~~^~
                                       
Foundation/NSXMLParser.swift:472:27: error: cannot call value of non-function type 'Thread'
            Thread.current().threadDictionary["__CurrentNSXMLParser"] = p
            ~~~~~~~~~~~~~~^~
                          
Foundation/NSXMLParser.swift:474:27: error: cannot call value of non-function type 'Thread'
            Thread.current().threadDictionary.removeValue(forKey: "__CurrentNSXMLParser")
            ~~~~~~~~~~~~~~^~
```

**Comment by damuellen** [comment]
@parkera please test again.

**Comment by damuellen** [comment]
I checked both xctest and swiftpm, but there is no occurrence of this.

**Comment by parkera** [comment]
@swift-ci please test

**Comment by phausler** [comment]
Looks good to me

**Pull request merged**
