### PR TITLE
[SR-6396] URLSessionConfiguration, renamed discretionary to isDiscretionary

### PR DESCRIPTION
**Pull request by iothmane**
Have the property name match Darwin

### CODE REVIEW

**Comment by spevans** [comment]
@swift-ci please test

**Comment by millenomi** [comment]
This is interesting in that it may cause source breakage, but since we do not implement any of the actual Darwin background request infrastructure, and that code using it is incorrect (as it wouldn't compile on Darwin), I feel inclined to just merge this.

**Comment by millenomi** [comment]
@swift-ci please test and merge

**Comment by spevans** [comment]
@swift-ci please test and merge

**Pull request merged**
