### PR TITLE
Remove two-digit year cookie format support & unit test (fails on Ubu…

### PR DESCRIPTION
**Pull request by maksimorlovich**
…ntu 14.04)

### CODE REVIEW

**Comment by jrose-apple** [comment]
@swift-ci Please test

**Comment by jrose-apple** [comment]
Unfortunately I don't think we have any way to test 14.04 from CI right now. @shahmishal?

**Comment by shahmishal** [comment]
Correct, we don't currently support PR testing on 14.04.

**Comment by jrose-apple** [comment]
I'm going to merge this ahead of Foundation reviewers to get the bots back, but there's probably a way to write this test so that it can dynamically check for a new enough ICU. That's outside my area, though, so for now let's take this.

**Pull request merged**
