### PR TITLE
[Cherry-Picked] [NSCache] [SR-3904] Fix for object storage.

### PR DESCRIPTION
**Pull request by naithar**

### CODE REVIEW

**Comment by naithar** [comment]
This one should probably wait for #900 to be merged.

**Comment by alblue** [comment]
@swift-ci please test

**Comment by naithar** [comment]
Added limit fix. Please review.

**Comment by alblue** [comment]
@swift-ci please test

**Comment by naithar** [comment]
The [build job](https://ci.swift.org/job/swift-corelibs-foundation-PR-Linux/680/) seems to be finished successfuly.

**Comment by alblue** [comment]
LGTM. @parkera what do you think? #900 has been merged into master, and this is cherry-picked onto the swift-3.1 branch

**Comment by parkera** [comment]
Let's make sure this gets in.

**Pull request merged**
