### PR TITLE
Add ICU module map

### PR DESCRIPTION
**Pull request by dabrahams**
This should allow prototypes in the Swift project to import and use ICU facilities

### CODE REVIEW

**Comment by parkera** [comment]
Why would swift-corelibs-foundation define a module map for ICU?

**Comment by parkera** [comment]
n.b. that ICU is not public API on Darwin, so defining a module map only for the Linux version of Swift seems odd.

**Comment by dabrahams** [comment]
It's for stdlib implementation, but I found a workaround, so if adding the module map seems like a bad idea to you, we can close this

**Comment by parkera** [comment]
Ok.

**Pull request closed without merging**
