### PR TITLE
Fix IndexSet.contains(integersIn indexSet:)

### PR DESCRIPTION
**Pull request by zayass**
Current version not even use an input parameter
Just comparing self with itself

### CODE REVIEW

**Comment by spevans** [comment]
@swift-ci please test

**Comment by zayass** [comment]
Whoops wrong test
Fixed
@spevans @parkera could you retest?

**Comment by spevans** [comment]
@swift-ci please test

**Comment by alblue** [comment]
@swift-ci please test

**Comment by zayass** [comment]
@parkera Is it ok to merge?

**Comment by parkera** [comment]
Yup

**Pull request merged**
