### PR TITLE
TestXMLDocument: Un-XFAIL DTD tests.

### PR DESCRIPTION
**Pull request by spevans**
- Serve the DTD from the built in HTTPServer so the tests
  will work without internet access.

- Resolves rdar://31567922.

### CODE REVIEW

**Comment by spevans** [comment]
@swift-ci please test

**Comment by alblue** [comment]
This LGTM. What do you think, @pushkarnk ?

**Comment by millenomi** [comment]
More tests are nice, and this was open long enough that we can open a separate PR for feedback if needed.

**Comment by millenomi** [comment]
@swift-ci please test and merge

**Pull request merged**
