### PR TITLE
Remove an invalid file reference

### PR DESCRIPTION
**Pull request by woxtu**
This PR removes an invalid file reference in the project.
The 'TestNSProgressFraction.swift' file seems to no longer exist.

### CODE REVIEW

**Review by compnerd — CHANGES_REQUESTED** [review]
https://github.com/apple/swift-corelibs-foundation/blob/main/Tests/Foundation/Tests/TestProgressFraction.swift ... might just need a path update.

**Comment by woxtu** [comment]
It looks like 'TestProgressFraction.swift' has already been added.

```console
$ cat Foundation.xcodeproj/project.pbxproj | grep TestProgressFraction.swift
		B940492D223B146800FB4384 /* TestProgressFraction.swift in Sources */ = {isa = PBXBuildFile; fileRef = B940492C223B146800FB4384 /* TestProgressFraction.swift */; };
		B940492C223B146800FB4384 /* TestProgressFraction.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = TestProgressFraction.swift; sourceTree = "<group>"; };
				B940492C223B146800FB4384 /* TestProgressFraction.swift */,
				B940492D223B146800FB4384 /* TestProgressFraction.swift in Sources */,
```

**Comment by compnerd** [comment]
@swift-ci please test

**Review by compnerd — APPROVED** [review]

**Comment by woxtu** [comment]
Thanks!

**Pull request merged**
