### PR TITLE
[5.0.3] Backport 5.1 changes to HTTPCookie parsing.

### PR DESCRIPTION
**Pull request by millenomi**
Fixes https://bugs.swift.org/browse/SR-11294

cc @weissi @spevans

### CODE REVIEW

**Comment by millenomi** [comment]
@swift-ci please test

**Comment by millenomi** [comment]
The macOS build issue seems unrelated; I can confirm it builds locally.

**Comment by millenomi** [comment]
@swift-ci please test 5.0

**Comment by millenomi** [comment]
@swift-ci please test swift 5.0

**Comment by shahmishal** [comment]
@swift-ci please test 5.0

**Comment by millenomi** [comment]
@swift-ci please test 5.0

**Comment by millenomi** [comment]
@swift-ci please test 5.0

**Comment by millenomi** [comment]
@swift-ci please test 5.0

**Comment by shahmishal** [comment]
@swift-ci please test 5.0 macOS

**Comment by weissi** [comment]
```
/home/buildnode/jenkins/workspace/swift-corelibs-foundation-PR-Linux/swift-corelibs-foundation/TestFoundation/HTTPServer.swift:15:8: error: missing required module '_SwiftDispatchOverlayShims'
```

@shahmishal / @millenomi any ideas?

**Comment by spevans** [comment]
@weissi This is a common transient issue unrelated to Foundation. I think its due to the caching behind the build.

**Comment by spevans** [comment]
@swift-ci please test 5.0

**Comment by millenomi** [comment]
@swift-ci please test 5.0

**Comment by millenomi** [comment]
@swift-ci please test 5.0 mac platform

**Comment by millenomi** [comment]
@swift-ci please test 5.0

**Comment by millenomi** [comment]
@swift-ci please test 5.0

**Comment by weissi** [comment]
@millenomi / @spevans it it normal that it fails that many times?

**Comment by millenomi** [comment]
No, it really is not. @shahmishal why is there so much traffic on the 5.0 branch?

**Comment by shahmishal** [comment]
@millenomi Can you please provide little more information about traffic you're seeing? Also, we only have one node for macOS which supports Swift 5.0 branch.

**Comment by shahmishal** [comment]
@swift-ci test 5.0 macOS

**Comment by millenomi** [comment]
@swift-ci please test 5.0 linux

**Pull request merged**
