### PR TITLE
Fix TestFoundation build on macOS local development

### PR DESCRIPTION
**Pull request by ikesyo**
On Xcode 14 or later, `CODE_SIGN_IDENTITY` should be set to "Sign to Run Locally".

image

### CODE REVIEW

**Comment by ikesyo** [comment]
@swift-ci please test

**Comment by ikesyo** [comment]
@swift-ci test Windows

**Review by kateinoigakukun — APPROVED** [review]
Locally confirmed TestFoundation build works well

**Comment by ikesyo** [comment]
@swift-ci test Windows

**Pull request merged**
