### PR TITLE
Foundation: avoid temporary file leaks on Windows

### PR DESCRIPTION
**Pull request by compnerd**
Correct the implementation of `_NSCleanupTemporaryFile` to use `MoveFileExW` with `MOVEFILE_COPY_ALLOWED` to prefer to use file renames rather than copy and delete.  This should improve performance in the general single volume case and still allow the correct behaviour in the multi-volume scenarios using `CopyFile` and `DeleteFile`.

Thanks to @darinf for identifying the test case with 65535 temporary files!

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by shahmishal** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by shahmishal** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test Windows platform

**Comment by grynspan** [comment]
woo!

**Pull request merged**
