### PR TITLE
JSONEncoder: Rename data coding enum values to align with SE-0167

### PR DESCRIPTION
**Pull request by spevans**
- DataEncodingStrategy.base64Encode -> .base64
- DataDecodingStrategy.base64Decode -> .base64

### CODE REVIEW

**Comment by spevans** [comment]
@swift-ci please test

**Comment by spevans** [comment]
@swift-ci please test

**Comment by ianpartridge** [comment]
Looks good, but there are other cases in [`DataEncodingStrategy`](https://github.com/apple/swift/blob/ef9dffac5ac5e8893fdfb2131220da27cc7804ae/stdlib/public/SDK/Foundation/JSONEncoder.swift#L64) and [`DataDecodingStrategy`](https://github.com/apple/swift/blob/ef9dffac5ac5e8893fdfb2131220da27cc7804ae/stdlib/public/SDK/Foundation/JSONEncoder.swift#L799) which aren't correct.

**Comment by spevans** [comment]
@ianpartridge Which other cases aren't correct? TBH, I was only doing enough to get the tests to compile against macOS Foundation

**Comment by ianpartridge** [comment]
We're missing `case deferredToData` in both. In general, `JSONEncoder.swift` needs bringing back in sync with the overlay as @itaiferber has made commits over there without updating this repo.

**Comment by ianpartridge** [comment]
I'm going to merge this as-is and look to fix the remaining API issues in `JSONEncoder.swift` in a followup PR.

**Pull request merged**
