### PR TITLE
Added test for NSArray

### PR DESCRIPTION
**Pull request by joshuatbrown**
Just added a test for the `objectAtIndex` method.

### CODE REVIEW

**Comment by phausler** [comment]
looks reasonable to me

**Comment by joshuatbrown** [comment]
That makes sense - I'll make the change and update the PR. Thanks for the feedback!

**Comment by joshuatbrown** [comment]
OK, this is ready for another review. I bridged the Strings to NSStrings - I hope that's what you meant, @phausler.

**Comment by joshuatbrown** [comment]
Is there anything else I can do to move this along? I'm happy to make further changes if needed.

**Pull request merged**
