### PR TITLE
NSRegularExpression: Make options: default to empty to match Darwin

### PR DESCRIPTION
**Pull request by spevans**
Brings it into line with the signatures @ https://developer.apple.com/documentation/foundation/nsregularexpression

### CODE REVIEW

**Comment by ianpartridge** [comment]
This looks good to me.

`NSMatchingOptions` and `NSMatchingFlags` need lifting inside `NSRegularExpression` too (and to lose their `NS` prefix). Would you be willing to open another PR to fix those?

https://developer.apple.com/documentation/foundation/nsregularexpression.matchingoptions
https://developer.apple.com/documentation/foundation/nsregularexpression.matchingflags

**Comment by ianpartridge** [comment]
@swift-ci please test

**Comment by spevans** [comment]
Do you mean renaming `struct NSMatchingOptions` to `struct MatchingOptions` and moving it inside an `extension NSRegularExpression`? And the same for `NSMatchingFlags`? I can do a PR for that

Do we also completely drop the `NSMatchingOptions` and `NSMatchingFlags`?

**Comment by ianpartridge** [comment]
Yes that's right. The various APIs that use them will need updating too (including the ones you added default parameters too in this PR).

**Comment by ianpartridge** [comment]
@swift-ci please test

**Comment by ianpartridge** [comment]
@swift-ci please test

**Comment by ianpartridge** [comment]
@swift-ci please test

**Comment by ianpartridge** [comment]
Looks like CI bot isn't working - I'll try again in the morning.

**Comment by alblue** [comment]
@swift-ci please test

**Comment by spevans** [comment]
It looks like the Jenkins CI jobs for Foundation arent listed on the ci.swift.org servers anymore (In the pull request tab)

**Comment by ianpartridge** [comment]
@shahmishal the CI bot for Foundation doesn't seem to be working - can you advise?

**Comment by alblue** [comment]
There was a mail sent to https://lists.swift.org/pipermail/swift-users/Week-of-Mon-20170731/006034.html (and others):

> — ci.swift.org is back online, but we’re still working on restoring pull request testing. We expect full functionality by tomorrow.

I suspect the Foundation jobs are part of this restoration process.

**Comment by shahmishal** [comment]
@swift-ci please test

**Comment by ianpartridge** [comment]
@swift-ci please test and merge

**Comment by spevans** [comment]
Looks like the builds that ended up testing on 8 threads all took too along and were aborted by timeout

**Comment by ianpartridge** [comment]
@swift-ci please test and merge

**Pull request merged**
