### PR TITLE
Disable file/dispatch-related code in Foundation for WASI

### PR DESCRIPTION
**Pull request by MaxDesiatov**
Functionality related to Dispatch, run loops, and full filesystem access (other than stdio/stderr file handles) is not available on WASI/Wasm. As a follow-up to previous Core Foundation PRs, this one updates parts of Foundation to add support for that platform.

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
@swift-ci please test

**Comment by MaxDesiatov** [comment]
@swift-ci please test

**Comment by millenomi** [comment]
Same comments here re: NSCoding.

**Comment by MaxDesiatov** [comment]
@swift-ci please test

**Comment by MaxDesiatov** [comment]
@millenomi I've re-enabled `NSCoding`-related code here, it's ready for review

**Comment by MaxDesiatov** [comment]
@swift-ci please test

**Comment by MaxDesiatov** [comment]
@swift-ci please test macOS platform

**Comment by millenomi** [comment]
@MaxDesiatov I'm looking tomorrow.

**Comment by AtariDreams** [comment]
@millenomi any updates?

**Comment by millenomi** [comment]
Things slipped a little but I'm finally looking right now >.<'

**Comment by millenomi** [comment]
I'm going to take it for right now, but I hope we can have follow-ups to re-expose `write(to…)` methods etc. to throw at runtime rather than be a hard compile error on use and force `#if os(WASI)` on clients. cc @MaxDesiatov

**Comment by MaxDesiatov** [comment]
That makes sense, thanks!

**Pull request merged**
