### PR TITLE
[4.1] Fix IndexSet/NSIndexSet range merging

### PR DESCRIPTION
**Pull request by zayass**
Same as #1434

### CODE REVIEW

**Comment by spevans** [comment]
@swift-ci please test

**Comment by zayass** [comment]
@spevans Looks like build back to normal
Can you retrigger build?

**Comment by alblue** [comment]
@swift-ci please test

**Comment by parkera** [comment]
Yeesh

**Comment by parkera** [comment]
@swift-ci please test

**Comment by alblue** [comment]
@swift-ci please test

**Comment by zayass** [comment]
still have unrelated test failures
@parkera @alblue could you retrigger tests?

**Comment by alblue** [comment]
@swift-ci please test

**Pull request merged**
