### PR TITLE
[LengthFormatter] Implementation of LengthFormatter and tests

### PR DESCRIPTION
**Pull request by kweinmeister**
- Implementation of all unimplemented functions in `NSLengthFormatter.swift`
- Test cases covering all functions, including paths for US, metric system, and `isForPersonHeightUse`
- Includes workaround for [issue](https://bugs.swift.org/browse/SR-3202) in which Locale attributes are not populated

### CODE REVIEW

**Comment by parkera** [comment]
Cool!

**Comment by parkera** [comment]
cc @lifeissweetgood

**Comment by parkera** [comment]
@swift-ci please test

**Comment by lifeissweetgood** [comment]
This is a good start!  Eventually it would be great to add support for different formats (rather than hardcoding `"\(formattedValue)\(separator)\(unitString(fromValue: value, unit: unit))"`).  Til then though, lgtm!

**Comment by parkera** [comment]
@kweinmeister would you mind resolving the merge conflicts so we can get this in?

**Comment by kweinmeister** [comment]
@lifeissweetgood @parkera Done!

**Comment by parkera** [comment]
@swift-ci test and merge

**Pull request merged**
