### PR TITLE
[gardening] Remove duplicate code in NSCalendar

### PR DESCRIPTION
**Pull request by otaviolima**
Removed code seems to be a wrong copy-paste inside each function.

### CODE REVIEW

**Comment by spevans** [comment]
Could the remaining code be simplified down to:
```
yearValuePointer?.pointee = comps.year ?? NSDateComponentUndefined
etc...
```

to cut down on the large `if/else` trees?

**Comment by otaviolima** [comment]
I will do it, once I fix this: 

```
<unknown>:0: error: Swift does not support the SDK 'MacOSX10.13.sdk'
Command /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2018-07-11-a.xctoolchain/usr/bin/swiftc failed with exit code 1
```

Google is not helping much to fix that. :/

**Comment by spevans** [comment]
@otaviolima Are you using the Xcode10 beta? Because that is required for current snapshots.

**Comment by otaviolima** [comment]
I was, but it started giving me another error then I switch back to Xcode 9 then then above error was shown.

I'm installing Xcode 10 beta 3 now.

**Comment by otaviolima** [comment]
Done.

**Comment by spevans** [comment]
@swift-ci please test

**Comment by otaviolima** [comment]
It passed: https://ci.swift.org/view/Pull%20Request/job/swift-corelibs-foundation-PR-Linux/1160/console

Is the reporting/github hook broken?

**Comment by spevans** [comment]
@otaviolima Its quite common that the CI->GitHub update hook doesn't always work, I'll kick off another test just to see if it updates

**Comment by spevans** [comment]
@swift-ci please test

**Comment by millenomi** [comment]
@swift-ci please test and merge

**Pull request merged**
