### PR TITLE
Parity: NSCoding: NSTextCheckingResult

### PR DESCRIPTION
**Pull request by millenomi**
- NSRegularExpression now supports NSSecureCoding, and serializes in a way that’s compatible with Darwin.

 - NSTextCheckingResult now matches the class structure it has on Darwin, and can encode and decode those classes.

 - Missing NSTextCheckingResult API are now present and marked with descriptive diagnostics.

### CODE REVIEW

**Comment by millenomi** [comment]
@swift-ci please test and merge

**Comment by spevans** [comment]
@swift-ci please test and merge

**Comment by millenomi** [comment]
@swift-ci please test and merge

**Comment by millenomi** [comment]
Fixed https://bugs.swift.org/browse/SR-10388

**Pull request merged**
