### PR TITLE
build: parallelise build

### PR DESCRIPTION
**Pull request by compnerd**
Enable parallel compilation when building Foundation.  We were
previously building Foundation in single threaded mode.  This should
significantly improve builds.

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @gmittert @millenomi

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by millenomi** [comment]
@swift-ci please test

**Comment by millenomi** [comment]
🤦🏻‍♀️

**Comment by millenomi** [comment]
@swift-ci please test linux

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Pull request merged**
