### PR TITLE
Implement filter with predicate methods on foundation collections

### PR DESCRIPTION
**Pull request by klundberg**
I didn't complete these in my initial PR for NSPredicate (only did NSArray), so I thought I'd finish the job for the other collection types.

### CODE REVIEW

**Comment by parkera** [comment]
@swift-ci please test

**Comment by klundberg** [comment]
Looks like this failed for the same reason as the prior PR test build, and my changes have nothing to do with the area that failed 😕

**Comment by scanf** [comment]
Your branch is 7 commits behind master. Rebasing your commit should make the tests pass.

**Comment by parkera** [comment]
Looks great. However there is a mysterious compiler crash on Linux that I'll try to figure out how to work around.

**Comment by parkera** [comment]
In order to move forward on this I commented out two tests and hacked a bit on a 3rd to get it past the compiler on Linux.

**Comment by klundberg** [comment]
Thanks for that! Sorry for not testing on linux myself, my vm has had issues that I've not been able to resolve as of yet.

**Pull request merged**
