### PR TITLE
[SE-0046] Implemented consistent function labels

### PR DESCRIPTION
**Pull request by harlanhaskins**
Implemented changes specified in [SE-0046 Establish consistent label behavior across all parameters including first labels](https://github.com/apple/swift-evolution/blob/master/proposals/0046-first-label.md)

Please look over this and make sure I didn't inadvertently change API. Thanks!

### CODE REVIEW

**Comment by parkera** [comment]
@swift-ci please test

**Comment by parkera** [comment]
Can't really review this effectively; there are too many diffs. We may have to just merge it and hope for the best.

**Comment by harlanhaskins** [comment]
Also the CI is going to fail because the compiler work hasn't been merged in 😞

**Comment by harlanhaskins** [comment]
@parkera We're going to merge this as soon as the compiler work is merged, to avoid spurious build failures. Is this alright?

**Comment by harlanhaskins** [comment]
@parkera Can I get a merge?

**Comment by harlanhaskins** [comment]
Or @phausler?

**Pull request merged**
