### PR TITLE
Fix typos in comments and strings

### PR DESCRIPTION
**Pull request by rex4539**

### CODE REVIEW

**Comment by rex4539** [comment]
@compnerd Could you take a look?

**Review by MaxDesiatov — APPROVED** [review]
Thanks!

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Review by compnerd — APPROVED** [review]
Sure, this is fine, but please don't do this in the future. It is okay to correct typos in surrounding code when making material changes, but just correcting typos in bulk just creates more work.

**Pull request closed without merging**
