### PR TITLE
TestFoundation: port HTTPServer to Windows

### PR DESCRIPTION
**Pull request by compnerd**
Make the test HTTPServer build on Windows.  This is needed for the
Windows test suite.

### CODE REVIEW

**Comment by compnerd** [comment]
CC: @millenomi @spevans

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by pushkarnk** [comment]
@swift-ci please test

**Comment by pushkarnk** [comment]
@compnerd Looks like a compilation failure
```
/home/buildnode/jenkins/workspace/swift-corelibs-foundation-PR-Linux/swift-corelibs-foundation/TestFoundation/HTTPServer.swift:198:77: error: cannot pass immutable value as inout argument: 'bytes' is a 'let' constant
```

**Comment by pushkarnk** [comment]
@compnerd Pardon my ignorance, I've been away from the SCLF project for a long time. Do we have Windows builds in the CI?

**Comment by spevans** [comment]
@pushkarnk Windows is not in the main CI , I believe @compnerd has CI for Windows  running on Azure

**Comment by pushkarnk** [comment]
Thanks @spevans !

**Comment by compnerd** [comment]
@pushkarnk - the CI is on Azure at https://dev.azure.com/compnerd/windows-swift.  We do have builds now (see the post on the forums).  There still are outstanding patches for Windows on GH.  I'm hoping to get back to the Foundation test suite now that the swift test suite patches have been merged.

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Pull request merged**
