### PR TITLE
Made NSLock use direct pthread strucutres instead of raw pointers

### PR DESCRIPTION
**Pull request by richardjrossiii**
This should reduce memory usage, increase performance, and makes code
signifcantly easier to read.

### CODE REVIEW

**Comment by parkera** [comment]
@swift-ci please test

**Comment by richardjrossiii** [comment]
Whoops. Left out a cast. Will fix.

**Comment by richardjrossiii** [comment]
PR Updated

**Comment by richardjrossiii** [comment]
@swift-ci Please test

**Comment by phausler** [comment]
unfortunately taking the address of these structures is not thread safe in swift the last time I checked, so the only way to make a safe reference to a pthread_mutex is to allocate the mutex

**Comment by richardjrossiii** [comment]
@phausler Ah, so the compiler makes an actual temporary copy of the variable in order to pass it as a pointer when passed via inout? 

That seems like it could be improved at the compiler level, then.

Very good knowledge to have then, that '&' is not truly addressOf in swift when interfacing with C (which of course begs the question - what makes `unsafeAddressOf` special?).

**Comment by gribozavr** [comment]
@phausler is right.  The compiler can insert a copy at any point.  This won't change, this is the Swift model for structs.  `withUnsafePointer` does not guarantee you anything.  `unsafeAddressOf` only works with class instances.

**Pull request closed without merging**
