### PR TITLE
Fix Data.count’s setter

### PR DESCRIPTION
**Pull request by lorentey**
(This was ported from the overlay fix in https://github.com/apple/swift/pull/28919)

Data provides a settable `count` property. Its expected behavior is undocumented, but based on the implementation, it is intended to zero-extend (or truncate) the collection to the specified length.

This does not work correctly if we start with an empty Data and we try to increase the count by a small integer:

```
import Foundation

var d = Data()
d.count = 2
print(d.count) // ⟹ 0 ⁉️

d.count = 100
print(d.count) // ⟹ 100 ✓
```

It looks like this bug was introduced with the Data overhaul that shipped in Swift 5.

(This issue was uncovered by https://github.com/apple/swift/pull/28918.)

rdar://58134026

### CODE REVIEW

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
D'oh.

```
/home/buildnode/jenkins/workspace/swift-corelibs-foundation-PR-Linux/swift-corelibs-foundation/TestFoundation/TestNSData.swift:4550:18: error: use of unresolved identifier 'expectEqualSequence'
21:43:01                  expectEqualSequence(
21:43:01                  ^~~~~~~~~~~~~~~~~~~
21:43:01 /home/buildnode/jenkins/workspace/swift-corelibs-foundation-PR-Linux/swift-corelibs-foundation/TestFoundation/TestNSData.swift:4574:18: error: use of unresolved identifier 'expectEqualSequence'
21:43:01                  expectEqualSequence(
21:43:01                  ^~~~~~~~~~~~~~~~~~~
```

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
@swift-ci please test linux platform

**Comment by lorentey** [comment]
```
15:35:26 Failing Tests (1):
15:35:26     Swift(linux-x86_64) :: stdlib/Arrays.swift.gyb
```

This looks unrelated.

**Comment by spevans** [comment]
@swift-ci test linux

**Comment by lorentey** [comment]
@swift-ci test

**Comment by spevans** [comment]
@swift-ci test linux

**Comment by lorentey** [comment]
@swift-ci test

**Comment by lorentey** [comment]
@swift-ci test macOS platform

**Comment by spevans** [comment]
@lorentey the macOS testing doesn't currently work correctly on this repo so the failure here can be ignored.

**Pull request merged**
