### PR TITLE
Update Status.md

### PR DESCRIPTION
**Pull request by amorde**
While looking for places to contribute to I noticed the status doc was out of date. I updated only the entries that were clearly incorrect, so there are bound to be more that need updating

### CODE REVIEW

**Comment by pushkarnk** [comment]
@swift-ci please test and merge

**Comment by pushkarnk** [comment]
Looks like we hit some CI issue while merging. The swift build has gone through.

**Comment by alblue** [comment]
@swift-ci please test and merge

**Comment by parkera** [comment]
I'll just force merge this. No need for the test on a markdown change.

**Comment by amorde** [comment]
👍 thank you!

**Pull request merged**
