### PR TITLE
NSDictionary: Add customMirror and missing init() method.

### PR DESCRIPTION
**Pull request by spevans**
- Add init(dictionary:copyItems:).

- Add .customMirror

- ExpressibleByDictionaryLiteral: init(dictionaryLiteral: (Any, Any)...)
  already existed, just add the conformance to the class declaration.

- Group the init() methods together.

Fixes https://bugs.swift.org/browse/SR-10449

### CODE REVIEW

**Comment by spevans** [comment]
@swift-ci test

**Comment by spevans** [comment]
@swift-ci test linux

**Comment by spevans** [comment]
@swift-ci test linux

**Comment by spevans** [comment]
@swift-ci test linux

**Comment by millenomi** [comment]
@swift-ci please test

**Comment by spevans** [comment]
@swift-ci please test

**Pull request merged**
