### PR TITLE
Implemented some CGRect's missing APIs

### PR DESCRIPTION
**Pull request by bubski**
### Calculated Geometric Properties
- [x] `CGRect.height: CGFloat { get }`
- [x] `CGRect.width: CGFloat { get }`
- [x] `CGRect.minX: CGFloat { get }`
- [x] `CGRect.midX: CGFloat { get }`
- [x] `CGRect.maxX: CGFloat { get }`
- [x] `CGRect.minY: CGFloat { get }`
- [x] `CGRect.midY: CGFloat { get }`
- [x] `CGRect.maxY: CGFloat { get }`

### Creating Derived Rectangles
- [x] `CGRect.standardized: CGRect { get }`
- [x] `CGRect.integral: CGRect { get }`
- [x] `CGRect.insetBy(dx: CGFloat, dy: CGFloat) -> CGRect`
- [x] `CGRect.offsetBy(dx: CGFloat, dy: CGFloat) -> CGRect`
- [x] `CGRect.union(_ r2: CGRect) -> CGRect`
- [x] `CGRect.intersection(_ r2: CGRect) -> CGRect`
- [x] `CGRect.divided(atDistance: CGFloat, from fromEdge: CGRectEdge) -> (slice: CGRect, remainder: CGRect)`

### Checking Characteristics
- [x] `CGRect.intersects(_ rect2: CGRect) -> Bool`
- [x] `CGRect.contains(_ point: CGPoint) -> Bool`
- [x] `CGRect.contains(_ rect2: CGRect) -> Bool`
- [x] `CGRect.isEmpty: Bool { get }`
- [x] `CGRect.isInfinite: Bool { get }`
- [x] `CGRect.isNull: Bool { get }`

### 📝 Also fixed 2 bugs in `CGRect : Equatable`
```swift
CGRect(x: 0, y: 0, width: -5, height: -5) == CGRect(x: -5, y: -5, width: 5, height: 5)
// used to return false
// should standardize before comparison first
```
```swift
let a = CGRect(x: CGFloat.infinity, y: 1, width: 2, height: 3)
let b = CGRect(x: 1, y: CGFloat.infinity, width: 2, height: 3)
a == b
// used to return false
// should return true if both `a` and `b` have any origin's value set to +∞
```

### CODE REVIEW

**Comment by ianpartridge** [comment]
@swift-ci please test

**Comment by dplanitzer** [comment]
@parkera it looks like that this PR is still awaiting your review. We too ran into the issue of these missing CGRect APIs and ended up implementing them in our internal fork. However we'd really like to move off our internal fork ASAP as it's a pain to keep that up to date. So the sooner this PR could be merged into the official repo the better. Thanks.

**Comment by alblue** [comment]
@bubski can you rebase these changes onto master so that we can re-run the tests?

@phausler the changes look superficially OK to me but would like confirmation that they are being done in the right place.

**Comment by bubski** [comment]
@alblue done 👌

**Comment by alblue** [comment]
@swift-ci please test

**Comment by alblue** [comment]
@phausler can you opine on the CGRect changes, please?

**Comment by phausler** [comment]
looks pretty reasonable to me, they fit all of the expected behaviors on Darwin.

**Comment by alblue** [comment]
@swift-ci please test and merge

**Pull request merged**
