### PR TITLE
Fix use of optional pattern

### PR DESCRIPTION
**Pull request by jtbandes**
Necessary for https://github.com/apple/swift/pull/3637. cc @parkera

### CODE REVIEW

**Comment by parkera** [comment]
@swift-ci please test

**Comment by parkera** [comment]
```
Foundation/NSXMLNode.swift:924:5: error: switch must be exhaustive, consider adding a default clause
    }
    ^
```

**Comment by jtbandes** [comment]
That one seems like a compiler bug ;)  Let's try it again...

**Comment by parkera** [comment]
@swift-ci please test

**Comment by jtbandes** [comment]
🎉

**Pull request merged**
