### PR TITLE
[SR-6581] Mark FileManager.attributesOfFileSystem unavailable on Android

### PR DESCRIPTION
**Pull request by ruipfcosta**
Fixes [SR-6581](https://bugs.swift.org/browse/SR-6581).

### CODE REVIEW

**Comment by millenomi** [comment]
@ruipfcosta Can you note in the comment that this fixes SR-6581 at a minimum?

@swift-ci Please test.

**Comment by parkera** [comment]
What was the problem with Android here, specifically? It has no way to retrieve this info?

**Comment by millenomi** [comment]
Android was #if'ing just this method to crash — I'm not sure what to do here, but the correct outcome would be that someone implement the Android version of this method.

In the meantime, I wanted to make this apparent to clients rather than not

**Comment by millenomi** [comment]
(It would be real weird if Android couldn't do the equivalent of stat(), though, honestly.)

**Comment by alblue** [comment]
Someone who is working on the Android version should probably opine on this; it's a no-op on other platforms. The question is, are there any places in the Android build that refer to this? Has it been built correctly on the Android platform with this change?

**Comment by millenomi** [comment]
Looks like a similar change already went in.

**Pull request closed without merging**
