### PR TITLE
[5.0][SR-10281] URLSession crash while handling basic authentication

### PR DESCRIPTION
**Pull request by saiHemak**
Cherry picked  from a6226abf50fe547a558ead11f7ff84d77e2bb87b

### CODE REVIEW

**Comment by saiHemak** [comment]
@pushkarnk  @spevans  please review

**Comment by spevans** [comment]
@swift-ci test

**Comment by spevans** [comment]
cc @weissi

**Comment by weissi** [comment]
ouch. thanks very much @saiHemak

**Pull request merged**
