### PR TITLE
Fixed _CFThreadSetName line for Android

### PR DESCRIPTION
**Pull request by amraboelela**

### CODE REVIEW

**Comment by alblue** [comment]
Does Android only allow the current thread's native name to be changed?

**Comment by spevans** [comment]
If might be better to modify `_CFThreadSetName` as that already checks the thread is `pthread_self()` on Darwin platforms, so adding Android in there will keep the checks in one place.

**Comment by amraboelela** [comment]
The error happens in this line **if let thread = _thread {**
Do you want to change  **_CFThreadSetName(thread, name ?? "" )** 
to make the thread parameter optional?

**Comment by alblue** [comment]
Leave the Swift code as is, do the fix in the c function instead was @spevans suggestion, I believe.

**Comment by amraboelela** [comment]
any suggestion of how to fix the c code?

**Comment by spevans** [comment]
@amraboelela I mis-read your original patch and thought the thread name could only be set for the current thread hence my suggestion of fixing `_CFThreadSetName`.

However on re-reading it I think the issue might be because on android the `_thread` is not an optional it is defined as:

```
#if os(Android)
    private var _thread = pthread_t()
#else
    private var _thread: pthread_t? = nil
#endif
```

I wonder if the special case for Android could be removed so it just uses the `pthread_t?` that other platforms use? That may be sufficient to fix it.

**Comment by amraboelela** [comment]
But there must be a reason why they did this code:

```
#if os(Android)
    private var _thread = pthread_t()
#else
    private var _thread: pthread_t? = nil
#endif
```

**Comment by spevans** [comment]
I don't think its correct. It used to be like that for Linux as well however `_thread = pthread_t()` sets _thread to a pthread_t with value 0 which is a valid ID that should not be used for an uninitialised thread ID. I changed it for Linux but not for Android as I could not test it for Android. So I would just try changing it and seeing if the tests still work.

**Comment by amraboelela** [comment]
Ok let me check it later

**Comment by amraboelela** [comment]
@spevans  I made the update and was able to build it successfully for Android

**Comment by spevans** [comment]
@swift-ci please test

**Comment by alblue** [comment]
Can we squash these two commits please?

**Comment by amraboelela** [comment]
Done

**Comment by alblue** [comment]
@swift-ci please test and merge

**Pull request merged**
