### PR TITLE
Change RegularExpression back to NSRegularExpression

### PR DESCRIPTION
**Pull request by pushkarnk**

### CODE REVIEW

**Comment by phausler** [comment]
@swift-ci please test and merge

**Comment by pushkarnk** [comment]
@phausler : The URLSession data task test timed out here :-( Can you please trigger the test again?

**Comment by parkera** [comment]
@swift-ci please test

**Comment by parkera** [comment]
@swift-ci please test and merge

**Comment by colemancda** [comment]
@parkera Any explanation why this was changed? I don't see any JIRA ticket for Swift evolution discussed related to this. Now we have to include a bunch of `typealias` for Swift 3.0 backwards compatibility. e.g https://github.com/OpenKitten/BSON/commit/9f3dfc8baf007eabdf2aaf76afdf95bb059345e2

**Comment by ikesyo** [comment]
@colemancda See https://github.com/apple/swift-evolution/blob/master/proposals/0086-drop-foundation-ns.md#proposed-solution

> If the class is planned to have a value-type equivalent in the near future, then keep the `NS` prefix. Examples: `NSAttributedString`, `NSRegularExpression`, `NSPredicate`.

The class was named as `RegularExpression` mistakenly in swift-corelibs-foundation (Linux). So I think this is a bug fix.

**Comment by parkera** [comment]
Yah, the darwin version is `NSRegularExpression` as of Swift 3.0 and our charter here is to match that.

**Pull request merged**
