### PR TITLE
SR-9550: xdgURLs assumes home directory location for .userDirectory

### PR DESCRIPTION
**Pull request by spevans**
- Parse /etc/default/useradd to find the default home directory,
  falling back to /home.

### CODE REVIEW

**Comment by spevans** [comment]
@swift-ci test

**Comment by spevans** [comment]
cc @compnerd

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by spevans** [comment]
@swift-ci please test

**Comment by spevans** [comment]
@swift-ci please test

**Comment by spevans** [comment]
@swift-ci please test

**Comment by millenomi** [comment]
@swift-ci please test and merge

**Comment by spevans** [comment]
@swift-ci please test and merge

**Comment by spevans** [comment]
@swift-ci please test and merge

**Pull request merged**
