### PR TITLE
Cherry pick changes for NSDecimal to swift-3.1 branch

### PR DESCRIPTION
**Pull request by alblue**
These changes have been merged into master, but contain a couple of important bug fixes that are needed to be on the Swift 3.1 branch

### CODE REVIEW

**Comment by parkera** [comment]
@swift-ci please test

**Comment by alblue** [comment]
The build failures seem orthogonal to the tests, as they are all in C++ code as opposed to Swift code. Is swift-3.1-branch in a good state?

**Comment by parkera** [comment]
Not sure; this is the first time we've tried to put something in that branch as far as I know.

**Comment by alblue** [comment]
Can you kick off the tests again? The swift-3.1-branch has been fixed up externally, so if the test pulls in the latest swift-3.1-branch then it should work.

**Pull request closed without merging**
