### PR TITLE
[SR-6398] Ensure CFSTR() is CFRetained because it is not permanent on Linux.

### PR DESCRIPTION
**Pull request by parkera**

### CODE REVIEW

**Comment by parkera** [comment]
@swift-ci please test

**Comment by jrose-apple** [comment]
Is there a reason not to put that into the CFSTR macro itself?

**Comment by parkera** [comment]
CFSTR has no ability to determine how many times the result will be released.

**Comment by parkera** [comment]
The real fix for this is the ability to mark Swift objects as immortal and have swift_release short-circuit.

**Pull request merged**
