### PR TITLE
Fix misleading local variable names

### PR DESCRIPTION
**Pull request by revolter**

### CODE REVIEW

**Comment by millenomi** [comment]
They're called 'max' because they are essentially the same as what is returned by `NSMaxRange()`, but it makes sense that one not versed in that would be confused.

**Comment by millenomi** [comment]
@swift-ci please test and merge

**Comment by spevans** [comment]
@swift-ci test linux

**Comment by revolter** [comment]
Is it stuck?

**Comment by xwu** [comment]
@swift-ci test

**Comment by revolter** [comment]
This can be merged, as the failing tests are not related to my changes.

**Comment by revolter** [comment]
I rebased it, maybe the tests will pass now.

**Comment by spevans** [comment]
@swift-ci please test and merge

**Pull request merged**
