### PR TITLE
[android] Enable Foundation.Host

### PR DESCRIPTION
**Pull request by drodriguez**
Depends on apple/swift#24286

The implementation of Host was disabled for Android, probably because
Glibc didn't include one header (netdb.h) which was needed to compile
this file. But changing Glibc is not enough, because the Android
implementation of that function and other bits differ slightly from
Linux implementation. For those cases private overrides are provide, to
keep the code unchanged.

There's also a little bit of formatting in one of Windows parts, which
was missing two spaces of indentation (probably checking without
whitespace enabled is good for this diff).

### CODE REVIEW

**Comment by millenomi** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@drodriguez - mind resolving the conflicts?

**Comment by drodriguez** [comment]
It created a merge commit, sadly. I will rebase and squash when I have access to something else but the web editor.

**Comment by drodriguez** [comment]
It should be good to go now.

**Comment by drodriguez** [comment]
@swift-ci please test

**Comment by spevans** [comment]
@swift-ci test

**Pull request merged**
