### PR TITLE
Simplify/Optimize NSSet

### PR DESCRIPTION
**Pull request by Adlai-Holler**

### CODE REVIEW

**Comment by Adlai-Holler** [comment]
@parkera Sorry I force-pushed which removed our comment history. I added that asserting behavior in f22ad8a.

**Comment by parkera** [comment]
I don't know why, but the swift compiler is crashing on the new Set implementation here, on Linux:

```
[85/96] CompileSwift: Foundation/NSSet.swift
FAILED: mkdir -p `dirname ../build/Ninja-DebugAssert/foundation-linux-x86_64/Foundation/Foundation/NSSet.swift.o`; mkdir -p ../build/Ninja-DebugAssert/foundation-linux-x86_64; /home/parkera/Development/build/Ninja-DebugAssert/swift-linux-x86_64/bin/swift -frontend -c Foundation/NSObject.swift Foundation/NSAffineTransform.swift Foundation/NSArray.swift Foundation/NSAttributedString.swift Foundation/NSBundle.swift Foundation/NSByteCountFormatter.swift Foundation/NSCache.swift Foundation/NSCalendar.swift Foundation/NSCFArray.swift Foundation/NSCFDictionary.swift Foundation/NSCFSet.swift Foundation/NSCFString.swift Foundation/NSCharacterSet.swift Foundation/NSCoder.swift Foundation/NSComparisonPredicate.swift Foundation/NSCompoundPredicate.swift Foundation/NSData.swift Foundation/NSDate.swift Foundation/NSDateComponentsFormatter.swift Foundation/NSDateFormatter.swift Foundation/NSDateIntervalFormatter.swift Foundation/NSDecimal.swift Foundation/NSDecimalNumber.swift Foundation/NSDictionary.swift Foundation/NSEnergyFormatter.swift Foundation/NSEnumerator.swift Foundation/NSError.swift Foundation/NSExpression.swift Foundation/NSFileHandle.swift Foundation/NSFileManager.swift Foundation/NSFormatter.swift Foundation/NSGeometry.swift Foundation/NSHost.swift Foundation/NSHTTPCookie.swift Foundation/NSHTTPCookieStorage.swift Foundation/NSIndexPath.swift Foundation/NSIndexSet.swift Foundation/NSJSONSerialization.swift Foundation/NSKeyedArchiver.swift Foundation/NSLengthFormatter.swift Foundation/NSLocale.swift Foundation/NSLock.swift Foundation/NSMassFormatter.swift Foundation/NSNotification.swift Foundation/NSNotificationQueue.swift Foundation/NSNull.swift Foundation/NSNumber.swift Foundation/NSNumberFormatter.swift Foundation/NSObjCRuntime.swift Foundation/NSOperation.swift Foundation/NSOrderedSet.swift Foundation/NSPathUtilities.swift Foundation/NSPersonNameComponents.swift Foundation/NSPersonNameComponentsFormatter.swift Foundation/NSPort.swift Foundation/NSPortMessage.swift Foundation/NSPredicate.swift Foundation/NSProcessInfo.swift Foundation/NSProgress.swift Foundation/NSPropertyList.swift Foundation/NSRange.swift Foundation/NSRegularExpression.swift Foundation/NSScanner.swift -primary-file Foundation/NSSet.swift Foundation/NSSortDescriptor.swift Foundation/NSStream.swift Foundation/NSString.swift Foundation/NSSwiftRuntime.swift Foundation/NSTask.swift Foundation/NSTextCheckingResult.swift Foundation/NSThread.swift Foundation/NSTimeZone.swift Foundation/NSURL.swift Foundation/NSURLAuthenticationChallenge.swift Foundation/NSURLCache.swift Foundation/NSURLCredential.swift Foundation/NSURLCredentialStorage.swift Foundation/NSURLError.swift Foundation/NSURLProtectionSpace.swift Foundation/NSURLProtocol.swift Foundation/NSURLRequest.swift Foundation/NSURLResponse.swift Foundation/NSURLSession.swift Foundation/NSUserDefaults.swift Foundation/NSUUID.swift Foundation/NSValue.swift Foundation/NSXMLDocument.swift Foundation/NSXMLDTD.swift Foundation/NSXMLDTDNode.swift Foundation/NSXMLElement.swift Foundation/NSXMLNode.swift Foundation/NSXMLNodeOptions.swift Foundation/NSXMLParser.swift Foundation/FoundationErrors.swift -I/home/parkera/Development/build/Ninja-DebugAssert/swift-linux-x86_64/lib/swift/linux -target x86_64-pc-linux   -Ibootstrap/common/usr/include -Ibootstrap/common/usr/local/include   -Ibootstrap/x86_64-linux-gnu/usr/include -Ibootstrap/x86_64-linux-gnu/usr/local/include -g -Onone  -I../build/Ninja-DebugAssert/foundation-linux-x86_64/Foundation -I../build/Ninja-DebugAssert/foundation-linux-x86_64/Foundation/usr/lib/swift -I../build/Ninja-DebugAssert/foundation-linux-x86_64 -I../build/Ninja-DebugAssert/foundation-linux-x86_64/Foundation/usr/lib/swift -I/home/parkera/Development/build/Ninja-DebugAssert/xctest-linux-x86_64 -L/home/parkera/Development/build/Ninja-DebugAssert/xctest-linux-x86_64 -module-name Foundation -module-link-name Foundation -o ../build/Ninja-DebugAssert/foundation-linux-x86_64/Foundation/Foundation/NSSet.swift.o -emit-module-path ../build/Ninja-DebugAssert/foundation-linux-x86_64/Foundation/Foundation/NSSet.swift.o.~partial.swiftmodule -emit-module-doc-path ../build/Ninja-DebugAssert/foundation-linux-x86_64/Foundation/Foundation/NSSet.swift.o.~partial.swiftdoc -emit-dependencies-path ../build/Ninja-DebugAssert/foundation-linux-x86_64/Foundation/Foundation/NSSet.swift.o.d -emit-reference-dependencies-path ../build/Ninja-DebugAssert/foundation-linux-x86_64/Foundation/Foundation/NSSet.swift.o.swiftdeps -module-cache-path ../build/Ninja-DebugAssert/foundation-linux-x86_64
0  swift           0x00000000052290de llvm::sys::PrintStackTrace(llvm::raw_ostream&) + 46
1  swift           0x00000000052294d9
2  swift           0x0000000005227df3 llvm::sys::RunSignalHandlers() + 131
3  swift           0x00000000052298ae
4  libpthread.so.0 0x00007fb0dd075340
5  swift           0x0000000000f690bc
6  swift           0x0000000001068ca5
7  swift           0x000000000106093a
8  swift           0x00000000010596d3
9  swift           0x00000000010d2100
10 swift           0x00000000010d3174
11 swift           0x00000000010d16c3
12 swift           0x00000000010d2de0
13 swift           0x00000000010d16ab
14 swift           0x00000000010d1620
15 swift           0x00000000010d3584
16 swift           0x00000000010d16f3
17 swift           0x00000000010d2de0
18 swift           0x00000000010d16ab
19 swift           0x00000000010d1620
20 swift           0x00000000010819c6
21 swift           0x0000000000fdbe4e
22 swift           0x0000000000fd4039
23 swift           0x0000000000fd37f9
24 swift           0x00000000010dc1b9
25 swift           0x00000000010dbbbc
26 swift           0x00000000010db762
27 swift           0x00000000010d988d
28 swift           0x0000000000fdfec4
29 swift           0x0000000000fd82a8
30 swift           0x0000000000fd9307 swift::SILModule::constructSIL(swift::ModuleDecl*, swift::SILOptions&, swift::FileUnit*, llvm::Optional<unsigned int>, bool, bool) + 535
31 swift           0x0000000000fd9907 swift::performSILGeneration(swift::FileUnit&, swift::SILOptions&, llvm::Optional<unsigned int>, bool) + 135
32 swift           0x0000000000ba733d
33 swift           0x0000000000ba624a frontend_main(llvm::ArrayRef<char const*>, char const*, void*) + 2954
34 swift           0x0000000000b95169 main + 3065
35 libc.so.6       0x00007fb0dc288ec5 __libc_start_main + 245
36 swift           0x0000000000b94464
Stack dump:
0.	Program arguments: /home/parkera/Development/build/Ninja-DebugAssert/swift-linux-x86_64/bin/swift -frontend -c Foundation/NSObject.swift Foundation/NSAffineTransform.swift Foundation/NSArray.swift Foundation/NSAttributedString.swift Foundation/NSBundle.swift Foundation/NSByteCountFormatter.swift Foundation/NSCache.swift Foundation/NSCalendar.swift Foundation/NSCFArray.swift Foundation/NSCFDictionary.swift Foundation/NSCFSet.swift Foundation/NSCFString.swift Foundation/NSCharacterSet.swift Foundation/NSCoder.swift Foundation/NSComparisonPredicate.swift Foundation/NSCompoundPredicate.swift Foundation/NSData.swift Foundation/NSDate.swift Foundation/NSDateComponentsFormatter.swift Foundation/NSDateFormatter.swift Foundation/NSDateIntervalFormatter.swift Foundation/NSDecimal.swift Foundation/NSDecimalNumber.swift Foundation/NSDictionary.swift Foundation/NSEnergyFormatter.swift Foundation/NSEnumerator.swift Foundation/NSError.swift Foundation/NSExpression.swift Foundation/NSFileHandle.swift Foundation/NSFileManager.swift Foundation/NSFormatter.swift Foundation/NSGeometry.swift Foundation/NSHost.swift Foundation/NSHTTPCookie.swift Foundation/NSHTTPCookieStorage.swift Foundation/NSIndexPath.swift Foundation/NSIndexSet.swift Foundation/NSJSONSerialization.swift Foundation/NSKeyedArchiver.swift Foundation/NSLengthFormatter.swift Foundation/NSLocale.swift Foundation/NSLock.swift Foundation/NSMassFormatter.swift Foundation/NSNotification.swift Foundation/NSNotificationQueue.swift Foundation/NSNull.swift Foundation/NSNumber.swift Foundation/NSNumberFormatter.swift Foundation/NSObjCRuntime.swift Foundation/NSOperation.swift Foundation/NSOrderedSet.swift Foundation/NSPathUtilities.swift Foundation/NSPersonNameComponents.swift Foundation/NSPersonNameComponentsFormatter.swift Foundation/NSPort.swift Foundation/NSPortMessage.swift Foundation/NSPredicate.swift Foundation/NSProcessInfo.swift Foundation/NSProgress.swift Foundation/NSPropertyList.swift Foundation/NSRange.swift Foundation/NSRegularExpression.swift Foundation/NSScanner.swift -primary-file Foundation/NSSet.swift Foundation/NSSortDescriptor.swift Foundation/NSStream.swift Foundation/NSString.swift Foundation/NSSwiftRuntime.swift Foundation/NSTask.swift Foundation/NSTextCheckingResult.swift Foundation/NSThread.swift Foundation/NSTimeZone.swift Foundation/NSURL.swift Foundation/NSURLAuthenticationChallenge.swift Foundation/NSURLCache.swift Foundation/NSURLCredential.swift Foundation/NSURLCredentialStorage.swift Foundation/NSURLError.swift Foundation/NSURLProtectionSpace.swift Foundation/NSURLProtocol.swift Foundation/NSURLRequest.swift Foundation/NSURLResponse.swift Foundation/NSURLSession.swift Foundation/NSUserDefaults.swift Foundation/NSUUID.swift Foundation/NSValue.swift Foundation/NSXMLDocument.swift Foundation/NSXMLDTD.swift Foundation/NSXMLDTDNode.swift Foundation/NSXMLElement.swift Foundation/NSXMLNode.swift Foundation/NSXMLNodeOptions.swift Foundation/NSXMLParser.swift Foundation/FoundationErrors.swift -I/home/parkera/Development/build/Ninja-DebugAssert/swift-linux-x86_64/lib/swift/linux -target x86_64-pc-linux -Ibootstrap/common/usr/include -Ibootstrap/common/usr/local/include -Ibootstrap/x86_64-linux-gnu/usr/include -Ibootstrap/x86_64-linux-gnu/usr/local/include -g -Onone -I../build/Ninja-DebugAssert/foundation-linux-x86_64/Foundation -I../build/Ninja-DebugAssert/foundation-linux-x86_64/Foundation/usr/lib/swift -I../build/Ninja-DebugAssert/foundation-linux-x86_64 -I../build/Ninja-DebugAssert/foundation-linux-x86_64/Foundation/usr/lib/swift -I/home/parkera/Development/build/Ninja-DebugAssert/xctest-linux-x86_64 -L/home/parkera/Development/build/Ninja-DebugAssert/xctest-linux-x86_64 -module-name Foundation -module-link-name Foundation -o ../build/Ninja-DebugAssert/foundation-linux-x86_64/Foundation/Foundation/NSSet.swift.o -emit-module-path ../build/Ninja-DebugAssert/foundation-linux-x86_64/Foundation/Foundation/NSSet.swift.o.~partial.swiftmodule -emit-module-doc-path ../build/Ninja-DebugAssert/foundation-linux-x86_64/Foundation/Foundation/NSSet.swift.o.~partial.swiftdoc -emit-dependencies-path ../build/Ninja-DebugAssert/foundation-linux-x86_64/Foundation/Foundation/NSSet.swift.o.d -emit-reference-dependencies-path ../build/Ninja-DebugAssert/foundation-linux-x86_64/Foundation/Foundation/NSSet.swift.o.swiftdeps -module-cache-path ../build/Ninja-DebugAssert/foundation-linux-x86_64 
1.	While emitting SIL for getter for allObjects at Foundation/NSSet.swift:190:9
Segmentation fault (core dumped)
```

We'll need to track that down before we can accept the merge, unfortunately.

That code is here:

```
extension NSSet {
    
    public var allObjects: [AnyObject] {
        get { // HERE
            if self.dynamicType === NSSet.self || self.dynamicType === NSMutableSet.self {
                return Array(_storage)
            } else {
                return Array(self)
            }
        }
    }
```

**Comment by parkera** [comment]
swift `6e3e83c`

**Comment by Adlai-Holler** [comment]
@parkera Bummer. I don't have a Linux box to test it on but I bet this works around it. Would you mind trying it?

**Comment by bolshedvorsky** [comment]
@Adlai-Holler you may try to use some of the virtual machines with Ubuntu images

**Comment by Adlai-Holler** [comment]
@bolshedvorsky Thanks, I'll do that this week and comment on here.

**Comment by parkera** [comment]
I merged this manually, with one more diff to satisfy the swift compiler on Linux.

**Comment by Adlai-Holler** [comment]
Whoa thank you very much @parkera

**Pull request closed without merging**
