### PR TITLE
UUID.uuidString should return an upper String like on Darwin

### PR DESCRIPTION
**Pull request by pvieito**
Report for NSUUID: https://bugs.swift.org/browse/SR-865

### CODE REVIEW

**Comment by xwu** [comment]
Could you please write a more descriptive comment above as to what's being fixed? The link is to a bug that's already been fixed for several years.

This PR also needs a test that fails without the patch and passes with the patch. Also, the same change should be committed to the Darwin Foundation [overlay](https://github.com/apple/swift/blob/master/stdlib/public/Darwin/Foundation/UUID.swift).

**Comment by compnerd** [comment]
CC: @millenomi

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by pvieito** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Pull request merged**
