### PR TITLE
[SR-3202] Some of properties of Locale.current object are not filled …

### PR DESCRIPTION
**Pull request by saiHemak**
…on Linux

### CODE REVIEW

**Comment by alblue** [comment]
@swift-ci please test

**Comment by ianpartridge** [comment]
Failure caused by GitHub outage.

**Comment by pushkarnk** [comment]
OK, I get what the problem was. 

`CFLocaleGetValue` called from `object(forKey:)` always returns any AnyObject. Subsequently for the different Locale properties, when we tried to conditionally cast it to a String, a nil was returned (this is what SR-3202 is). 

This fix first converts the AnyObject/NSString to String by using `_SwiftValue.fetch`, due to which a forced downcast in `localeIdentifier` fails . The second part of the fix removes the forced downcast.

**Comment by pushkarnk** [comment]
LGTM

@swift-ci please test and merge

**Pull request merged**
