### PR TITLE
[5.9] Cherry pick "Add Sendable to Date, DateComponents, Data and UUID" 

### PR DESCRIPTION
**Pull request by FranzBusch**
This cherry picks this PR: https://github.com/apple/swift-corelibs-foundation/pull/4777

### CODE REVIEW

**Comment by FranzBusch** [comment]
@swift-ci please test

**Comment by FranzBusch** [comment]
@swift-ci please test Windows

**Review by ktoso — APPROVED** [review]

**Review by parkera — APPROVED** [review]

**Comment by FranzBusch** [comment]
@swift-ci please test

**Comment by FranzBusch** [comment]
@parkera @shahmishal It looks like the 5.9 macOS CI is failing and it seems unrelated to my PR here. Are you aware of this?

**Comment by tomerd** [comment]
@swift-ci please test macOS

**Comment by FranzBusch** [comment]
Looks like something in xctest is failing the CI:

```
FAIL: SwiftXCTestFunctionalTests :: TestCaseLifecycle/Misuse/main.swift (26 of 26)
******************** TEST 'SwiftXCTestFunctionalTests :: TestCaseLifecycle/Misuse/main.swift' FAILED ********************
```

**Pull request merged**
