### PR TITLE
[6.0] Merge Foundation re-core to release/6.0

### PR DESCRIPTION
**Pull request by jmschonfeld**
We will be landing the Foundation re-core in Swift 6. This brings all of the changes to `main` into the `release/6.0` branch in order to lower that recore into Swift 6. This will be a WIP PR that we'll continue to update as we merge work to main (we'll keep merging `main` into this branch), and we will merge to `release/6.0` once all re-core work has landed

### CODE REVIEW

**Comment by jmschonfeld** [comment]
@swift-ci please test Linux platform

**Comment by jmschonfeld** [comment]
@swift-ci please test Windows platform

**Comment by jmschonfeld** [comment]
```
CMake Error at /home/build-user/cmake/Modules/ExternalProject.cmake:3114 (message):
  No download info given for 'swiftfoundationicu-populate' and its source
  directory:

   /home/build-user/swift-foundation-icu

  is not an existing non-empty directory.
```

@shahmishal is there something that we might be missing here to have the checkout work as expected for a `release/6.0` PR?

**Comment by shahmishal** [comment]
Did we cherry-pick the update-checkout changes on swift:release/6.0?

**Comment by jmschonfeld** [comment]
> Did we cherry-pick the update-checkout changes on swift:release/6.0?

Yes, but there isn't an explicit branch listed under the `release/6.0` key in the json file - do we need to explicitly specify the branch or will it default to `main`?

**Comment by shahmishal** [comment]
We will need cherry-pick the changes into `release/6.0` branch otherwise the JSON file will not clone swift-foundation and swift-foundation-icu.

**Comment by jmschonfeld** [comment]
https://github.com/swiftlang/swift/pull/75338

@swift-ci please test

**Comment by jmschonfeld** [comment]
Tests for this are now running on https://github.com/swiftlang/swift/pull/75338 which updates the `update-checkout` config to correctly checkout the right repos

**Comment by parkera** [comment]
https://github.com/swiftlang/swift/pull/75338

@swift-ci please test

**Comment by parkera** [comment]
Test at https://github.com/swiftlang/swift/pull/75338  passed

**Pull request merged**
