### PR TITLE
Use `switch` for type casting and `guard` for preconditions in `isEqual` methods

### PR DESCRIPTION
**Pull request by naithar**

### CODE REVIEW

**Comment by parkera** [comment]
@swift-ci please test and merge

**Comment by naithar** [comment]
@parkera can you please run test again, i've fixed the typo leading to segfault.

**Comment by alblue** [comment]
@swift-ci please test

**Comment by naithar** [comment]
It seems that test didn't run again

**Comment by alblue** [comment]
@swift-ci please test and merge

**Pull request merged**
