### PR TITLE
SR-9454: StringProtocol.lineRange(for:) returns invalid range on Linux

### PR DESCRIPTION
**Pull request by norio-nomura**
Fixes [SR-9454](https://bugs.swift.org/browse/SR-9454)

### CODE REVIEW

**Comment by spevans** [comment]
@swift-ci test

**Comment by norio-nomura** [comment]
We may also need to examine other places that use `String.Index.init(encodedOffset:)`. 🤔

**Comment by norio-nomura** [comment]
> We may also need to examine other places that use `String.Index.init(encodedOffset:)`. 🤔

I filed a separate issue about `encodedOffset`: https://bugs.swift.org/browse/SR-9749

**Comment by milseman** [comment]
@spevans this change looks good to me and is an important fix for Swift 5. But, I'm not familiar with corelibs-foundation, what do you think?

**Comment by spevans** [comment]
I think this needs an extra test on a `SubString` to check that the `_substringOffset` can be removed as the comment for it is:
```// self can be a Substring so we need to subtract/add this offset when
  // passing _ns to the Foundation APIs. Will be 0 if self is String.
```

**Comment by milseman** [comment]
That PR gives new API that you can use instead of having to advance the index yourself. Basically, it will let you simplify your one line of code, but it could be held up for a while awaiting core-team feedback and maybe even some SE work. This change is good and important no matter what happens with that PR, are you ok to merge it @spevans?

**Comment by spevans** [comment]
Yup, thanks for the explanation, lets get this fix in.

**Comment by spevans** [comment]
@swift-ci test and merge

**Comment by norio-nomura** [comment]
Thanks!

**Pull request merged**
