### PR TITLE
Use `Hashable.hash(into:)` over `hashValue` to silence the deprecation warnings

### PR DESCRIPTION
**Pull request by ikesyo**
There are some remaining warnings, but this should be a good start.

### CODE REVIEW

**Comment by ikesyo** [comment]
@swift-ci Please test

**Comment by ikesyo** [comment]
@lorentey Thanks for your review and the suggestions! I'll address those.

**Comment by ikesyo** [comment]
@swift-ci Please test

**Comment by ikesyo** [comment]
@swift-ci Please test

**Comment by parkera** [comment]
> Thanks a lot for working on this!
> 
> The `Foundation` overlay on Apple platforms has not been updated yet, but there is no reason corelibs-Foundation can't do the transition first.

We're trying to keep these in sync as much as possible.

**Comment by lorentey** [comment]
I'll submit a PR to update the Foundation overlay soon -- it makes sense to hold this PR until then.

**Comment by lorentey** [comment]
Apologies for the delay. I split out your `NSObject.hashValue` commit into a separate PR -- https://github.com/apple/swift-corelibs-foundation/pull/1850. I believe this can land immediately, pending review.

Switching to `hash(into:)` will need a bit of coordination; my PR for the overlays is still in progress.

**Comment by millenomi** [comment]
@swift-ci please test and merge

**Pull request merged**
